### ISSUE TITLE
Allow stopping the upload

### ISSUE THREAD

**Issue by tehoko** [rr-/szurubooru#101]
There's no *user-friendly* way of stopping the upload, meaning one can't change the safety/anonymity *in a user-friendly way* unless the process is stopped by found duplicate post.

From GUI pov, this could be achieved by changing the current `Upload all` button's text to `Stop upload`. It could also change the style to basic text, like `Stop tagging` button in posts list.

The partially-uploaded post would stay on the upload queue, and any data already transferred would be discarded.

**Comment by rr-** [comment]
(You could always close the tab)

**Comment by tehoko** [comment]
Edited the original post to reflect the comment.

**Comment by rr-** [comment]
Implemented in https://github.com/rr-/szurubooru/commit/7862fecbc990a580970aaeef9de5667da268cc9f
