### ISSUE TITLE
Unable to tag post with a tag that contains an apostrophe

### ISSUE THREAD

**Issue by tehoko** [rr-/szurubooru#104]
The `'` character is being escaped to `&apos;` when the post changes are saved.

I tried to tag a post with `Mahou_Shoujo_Lyrical_Nanoha_A's` (the tag had existed before), and this action created a new tag, `Mahou_Shoujo_Lyrical_Nanoha_A&apos;s`, upon saving. Before saving, the tag selected from autocomplete had correct punctuation.

**Comment by tehoko** [comment]
I'm also unable to search for the original tag when it's selected from autocomplete. I can get correct results when I manually change &apos;` to `'` back.

**Comment by rr-** [comment]
That's a separate issue

**Comment by tehoko** [comment]
Created #105.

**Comment by rr-** [comment]
So it goes like this:

1. Post is tagged with `Nanoha's`
2. Click edit
3. Save without changes
4. The post is now tagged with `Nanoha&apos;s`

Is that correct?

**Comment by tehoko** [comment]
No, this scenario works properly.

The issue appears when trying to add the `Nanoha's` tag to a post that didn't contain it.

**Comment by tehoko** [comment]
Looks like the fix for #105 also solved this one. Thanks.

**Comment by rr-** [comment]
Yay
