### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by h6dy** [rr-/szurubooru#107]
Hello author.

thank you for your works.

I got an error  when uploading audio or video files: Unhandled file type: ‘application/octet-stream’
could you tell me how to fix it ?

Details: All the required software has been installed;
             The entire installation process runed well except five errors about api when runed the test;
             The permissions for creating user are modified to administrators only;

**Comment by rr-** [comment]
What kind of video and audio? Only WEBM and MP4 are supported.

**Comment by h6dy** [comment]
Flv and Mp3,  after reading the introduction again, now I understand.

**Comment by rr-** [comment]
I currently don't plan to support audio-only streams and I don't plan to support FLV videos either:

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

Note that Flash is supported via SWF only by popular demand. Likewise, if there's enough interest in FLV or audio, I can add support for these in the future.
