### ISSUE TITLE
Notes disappear after rating/faving a post

### ISSUE THREAD

**Issue by tehoko** [rr-/szurubooru#108]
If a post has notes, voting on the post (thumbs up / down) or adding it to favorites causes all notes to disappear. They're not removed though - they can be brought back by entering the edit mode or refreshing the page.

![disappearing-notes](https://cloud.githubusercontent.com/assets/2924029/20240669/8f2a3fa2-a91e-11e6-9487-5bdc5a8e204e.gif)

**Comment by rr-** [comment]
I have the weirdest bug now
