### ISSUE TITLE
Unable to create users, Can log in as anyone, cannot upload

### ISSUE THREAD

**Issue by cam-peterson** [rr-/szurubooru#109]
Hello

Sorry to bug you. I've been troubleshooting this for a while and I can't get anywhere.

I can't make an account, it just says "Not allowed". I tried grepping the source code for that and can't find it in the code so i don't know why it happens.

But then I can log in using any username/password combination, but when i do thaht i cannot upload. I have checked the permissions in config.yaml and they look right.

Do you know what could be wrong or how I can debug this? thank you

**Comment by rr-** [comment]
Sounds like the server isn't wired well (though "I can login as anyone" sounds confusing).

You can inspect the communication between the server and the client with developer tools in your browser, in the "network" tab - that could shed some light.

**Comment by cam-peterson** [comment]
For wiring I am just using the nginx configuration from the install instructions, with my domain name in.

Looking at the developer tools when I tried to make an account it was to request URL: `https://booru.spqrchan.org/null/users`` and the response is
```
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

From google I found that some people put `error_page 405 =200 $uri;` in the nginx config but this did not make my szuru instance work: I get 200 instead 205, and instead of "Not Allowed" the text boxes become locked.

Thank you for the advice and suggestions

**Comment by rr-** [comment]
Are you sure it should be `/null/` and not `/api/`?

**Comment by cam-peterson** [comment]
I guess it should be /api/, I can't work out why it is /null/ instead. I tried rebuilding the client. My config.yaml has `api_url: http://booru.spqrchan.org/api/` and I cannot find null anywhere..

**Comment by rr-** [comment]
Can you test what happens if you put:

```
api_url: 'http://booru.spqrchan.org/api/'
```

instead? (note single quotes)

(If that's the case, I'll make sure to document it)

**Comment by cam-peterson** [comment]
With the single quotes (and rebuilding the client),  I am still seeing `http://booru.spqrchan.org/null/users`

**Comment by rr-** [comment]
FWIW here's what my `config.yaml` looks like:

```
debug: 1
transpile: 0
show_sql: 0
api_url: 'http://booru-dev/api/'
base_url: 'http://booru-dev/'
data_url: 'http://booru-dev/data/'
data_dir: /home/rr-/src/maintained/szurubooru/client/public/data

tag_name_regex: ^\S+$

thumbnails:
    post_width: 300
    post_height: 300

smtp:
    (censored)

database: postgres://user:password@localhost:5432/szuru
```

**Comment by cam-peterson** [comment]
I just noticed something really weird in `.config.autogen.json`:  `{"name":"szurubooru","debug":0,"showSql":0,"transpile":1,"apiUrl":null,"baseUrl":null,"dataUrl":null,"dataDir":null,"`

**Comment by cam-peterson** [comment]
I must have had a broken yaml before which created those nulls, but now the booru seems to work completely. Thank you very much for your kind help!
