### ISSUE TITLE
Upload: Re-adding a file blocks reordering

### ISSUE THREAD

**Issue by tehoko** [rr-/szurubooru#111]
Steps to reproduce:

1. Go to Upload.
2. Add file1 to the list.
3. Add file2 to the list. It's shown at the bottom of the list, with file1 at the top.
4. Try to reorder the files - it works.
5. Remove file1 from the list by clicking X.
6. Add file1 to the list again. It's shown at the bottom, with file2 at the top.
7. Try to reorder the files.

After 7., either no visible action is performed, or reordering can be done once (by clicking at `v` for file2 at the top). After that, clicking "Upload all" will result in something like this:

![image](https://cloud.githubusercontent.com/assets/2924029/21750514/dc18818a-d5b4-11e6-90d7-5aac88dc566a.png)

Note how file2 is given the error, as if it was at the top of the upload queue. Clicking "Resume upload" doesn't change that.

**Comment by rr-** [comment]
The upload is actually moved but DOM is not updated because of some BS
