### ISSUE TITLE
Unable to change tag category color

### ISSUE THREAD

**Issue by kotcrab** [rr-/szurubooru#119]
1. Go to tag categories
2. Click on any color field
3. Select new color using color picker, press OK
4. Color field is not updated

Tested on Win10, latest Firefox and Chrome.

By the way, Windows color picker is horrible. It's literally [MS Paint picker](https://i.imgur.com/43y3LLJ.png). Maybe it will be better to allow direct input?

**Comment by rr-** [comment]
I'm for plain text color editing, especially that the default text category comes with `default` color that's handled by `<input type=color/>` sketchily at best.

**Comment by rr-** [comment]
![20170207_203143_uac](https://cloud.githubusercontent.com/assets/1045476/22707864/74ee9f44-ed74-11e6-8fc9-510b50a37e0c.png)

**Comment by kotcrab** [comment]
@rr- looks neat 👍

**Comment by rr-** [comment]
Pushed~
