### ISSUE TITLE
URL search query is not preserved

### ISSUE THREAD

**Issue by kotcrab** [rr-/szurubooru#120]
1. Enter some search query
2. On result list open any post. You can see that target URL still contains search query
3. On post page query is removed from URL

This makes navigating between posts with active search query feature unusable.

**Comment by rr-** [comment]
Are you sure about this?
I explicitly remove the query from the URL via special history API to make links pretty (especially for clipboard), but the previous/next post links should retain that search query underneath in the HTML.

**Comment by kotcrab** [comment]
Ah I see, I saw query removed and assumed that it's not working... You are right, it's working fine.
