### ISSUE TITLE
Feature request: mass delete

### ISSUE THREAD

**Issue by Darksonn** [rr-/szurubooru#123]
Deleting a lot of posts is pretty tedious right now.

**Comment by rr-** [comment]
Why would you want to do that though?

**Comment by Darksonn** [comment]
Someone I'm using the image board with just went "yeah, let's upload every image in my downloads folder". It's also what caused this: https://github.com/rr-/szurubooru/issues/122

**Comment by rr-** [comment]
TBH, I can't think of how to create a decent GUI for this...

maybe you would be okay with a CLI script that takes post IDs?

**Comment by Darksonn** [comment]
It would be kinda tedious to select them with a CLI script, but it's certainly better than the current situation.

**Comment by rr-** [comment]
@Darksonn I think you could efficiently select the posts by

1. Opening the data directory thumbnails in your favorite graphical file manager (In case of a headless server you could SSHFS into it)
2. Examine the post thumbnails
3. Select the relevant files
4. Copy their paths
5. Fish IDs from paths with `sed` or similar
6. Paste it as arguments for the script

Here's the script itself (needs `pip install requests`):

```
#!/usr/bin/env python3
import argparse
import logging
import json
from getpass import getpass
from typing import List
import requests


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        'Remove posts from szurubooru by their IDs.')
    parser.add_argument(
        '--api-url', required=True,
        help='API url (e.g. https://example.com/api)')
    parser.add_argument(
        '--user', '-u', required=True, help='szurubooru user')
    parser.add_argument(
        '--password', '--pass', '-p', default=None,
        help='szurubooru password (leave empty for interactive input)')
    parser.add_argument('post_id', nargs='+', type=int)
    return parser.parse_args()


def main() -> None:
    logging.getLogger().setLevel(logging.INFO)

    args = parse_args()
    post_ids: List[int] = args.post_id
    api_url: str = args.api_url
    api_user: str = args.user
    api_pass: str = args.password or getpass('Password: ')

    for post_id in post_ids:
        try:
            response = requests.get(
                api_url + '/post/%d' % post_id,
                headers={'Accept': 'application/json'},
                auth=requests.auth.HTTPBasicAuth(api_user, api_pass))

            if response.status_code != 200:
                raise RuntimeError(response.json()['description'])

            version = response.json()['version']

            response = requests.delete(
                api_url + '/post/%d' % post_id,
                data=json.dumps({'version': version}),
                headers={'Accept': 'application/json'},
                auth=requests.auth.HTTPBasicAuth(api_user, api_pass))

            if response.status_code != 200:
                raise RuntimeError(response.json()['description'])

            logging.info('%d: ok', post_id)

        except Exception as ex:
            logging.error('%d: error (%s)', post_id, ex)


if __name__ == '__main__':
    main()
```

Example session:

```console
rr-@tornado:~$ ./delete-szuru-posts --api-url http://booru-dev/api --user eax -p PASS 2521
INFO:root:25217: ok
rr-@tornado:~$ ./delete-szuru-posts --api-url http://booru-dev/api --user eax -p PASS 2521
ERROR:root:25217: error (Post 25217 not found.)
```

**Comment by Darksonn** [comment]
This fails:

    ./delet-this --api-url https://--snip--/ --user alice 2038
    ERROR:root:2038: error (Expecting value: line 1 column 1 (char 0))

Though wouldn't a reasonable gui be a button like the mass tag button which then allows you to select images and then a button with "delete all"?

**Comment by rr-** [comment]
(Are you using the `/api` URL or just the main site?)

Regarding deleting via GUI: what about pagination?

0. Page size = 10
1. Mark posts 1, 2, 3, 4
2. Hit delete
3. Posts 1, 2, 3, 4 disappear and get deleted; 5, 6, 7, 8, 9 and 10 are still present
4. Request next page
5. Rather than seeing posts 11 to 20, the server returns posts 15 to 24, and you never get to see posts 11, 12, 13 and 14. This is because after deleting the posts, the new first page should display posts 5, 6, 7, 8, 9, 10, **11, 12, 13, 14**

I'd need to refresh the current page after each mass deletion, and this is going to be huge PITA in case of endless paging...

**Comment by Darksonn** [comment]
I think the underlying problem in why this is hard is that the server takes a page number and returns some number of images.

If, instead of the request being "give me the images on page 2", the request would be "give me the images starting from post 11", this problem seems rather easy to solve.

**Comment by Darksonn** [comment]
Also yeah, the script not working was my fault.

**Comment by Darksonn** [comment]
Also this currently being an issue implies endless pagination is probably currently broken: what happens if someone deletes an image I've currently loaded on my endless paginated page?

**Comment by rr-** [comment]
>If instead of "give me the images on page 2", the request was "give me the images starting from post 11", this problem would mostly go away.

This isn't going to work because of `sort:*`; probably could be done with some subselects but the queries would work very slowly.

>Also this currently being an issue implies endless pagination is probably currently broken: what happens if someone deletes an image I've currently loaded on my endless paginated page, and I then try to load more images?

That's true, TBH, the images on our installation are deleted once in a blue moon, so we never cared about that thus far.

**Comment by Darksonn** [comment]
How did you engineer sorting to work well with paginated requests? 

While deletions are rare, what about new uploads? They should break it too.

**Comment by rr-** [comment]
Yes, it breaks on new uploads too (so does gelbooru and danbooru BTW). Personally I think it's a very minor issue given the upload pace at our installation and would like to avoid over-engineering this just to address this specific issue.

Query for `sort:comment-count` is pretty straightforward:

```
SELECT
    post.id AS post_id,
    post.image_width AS post_image_width,
    post.image_height AS post_image_height,
    post."mime-type" AS "post_mime-type",
    post.image_width * post.image_height AS anon_1,
    CAST(post.image_width AS FLOAT) / CAST(post.image_height AS FLOAT) AS anon_2,
    (SELECT coalesce(sum(post_score.score), %(coalesce_2)s) AS coalesce_1 FROM post_score WHERE post_score.post_id = post.id) AS anon_3,
    (SELECT count(post_favorite.post_id) AS count_1 FROM post_favorite WHERE post_favorite.post_id = post.id) AS anon_4,
    (SELECT count(comment.post_id) AS count_2 FROM comment WHERE comment.post_id = post.id) AS anon_5,
    (SELECT count(post_relation.child_id) AS count_3 FROM post_relation WHERE post_relation.parent_id = post.id OR post_relation.child_id = post.id) AS anon_6,
    post.user_id AS post_user_id,
    post.version AS post_version,
    post.creation_time AS post_creation_time,
    post.last_edit_time AS post_last_edit_time,
    post.safety AS post_safety,
    post.source AS post_source,
    post.flags AS post_flags,
    post.type AS post_type,
    post.checksum AS post_checksum,
    post.file_size AS post_file_size
FROM post
ORDER BY anon_5 DESC, post.id DESC
LIMIT %(param_1)s
OFFSET %(param_2)s
```

(`LIMIT` and `OFFSET` are obviously applied after `ORDER BY`)

I didn't denormalize the tables since we didn't need to do so thus far.

**Comment by Darksonn** [comment]
Querying an interval of posts or a page seems like two different methods of querying posts, where one is a strictly less powerful version of the other with a more unpredictable api. I see you're controlling what pages are returned from the query with `OFFSET`, which takes the index of the first post, not the page number, which means the page number is just another indirection on top of accessing the posts.

I do not see how pages help with the performance of different `sort:*` queries at all compared to pages, since you're just inserting the index of the first post on the page anyway.

Since it seems you're not interested in changing this (which is fair enough—it looks like a rather big change), I'll instead ask for some pointers on what files I should look in if I want to add gui mass deletion myself (I'm also not currently interested in changing the api to use post indexes, so I'd just make a version that reloads the page).

**Comment by rr-** [comment]
>I do not see how pages help with the performance of different sort:* queries at all compared to pages, since you're just inserting the index of the first post on the page anyway.

I don't understand this sentence? Earlier I meant switching to post ID based paging rather than row number based paging will be difficult, since that's what I thought you were suggesting. The client knowing how to precisely offset the collection (e.g. use indexes rather than page numbers) won't help with desync coming from upstream changes.

>Since it seems you're not interested in changing this (which is fair enough—it looks like a rather big change)

I can easily change the API to use post indexes rather than pages, that's not a problem, but I can't think of an easy way to work around the desync that comes with new/deleted posts :-(

>pointers on what files I should look in if I want to add gui mass deletion myself

- `html/posts_header.tpl` contains HTML for post list header
- `js/views/posts_header_view.js` contains JS for post list header DOM events and such
- `js/controllers/post_list_controller.js` contains JS that orchestrates the dialog between view and the API

**Comment by Darksonn** [comment]
Uh, well I don't really care with row index vs post ID, since post ID can be turned into row based with O(log n) time after sorting, which is instant compared to actually sorting the list. I don't know how postgresql does binary search though.

Regardless: Row numbers solve the gui problem almost as well as post IDs, you just need to update the next page links when you do a deletion.

However it doesn't solve the problem when other tabs/users edit the database, which might explain why danbooru/gelbooru also have that problem (I don't know how they do it, but I'd guess at least one of them uses row number).

**Comment by Darksonn** [comment]
I'm sorry for being harsh, but I was getting frustrated from what turns out to be a misunderstanding.

**Comment by rr-** [comment]
@Darksonn I'll replace `page` and `pageSize` API parameters for paged collections with just `index` and `limit` then; pinging @kotcrab for knowledge.
I'll try to do finish the changes by Friday night.

**Comment by rr-** [comment]
1. Every place in the site that features paging is about results from paged API collection
2. Every API collection stores results in `results` field
3. Every API collection has its model in the client code
4. Every such model derives from `AbstractList` interface
5. `AbstractList` knows when an element from it is removed

Basing on this, in the endless and manual pager code, I'm going to bind to item removal, and update the next pages links by decrementing their offsets by one.

Example of what I'm talking about - binding to removal of a point from note's polygon that keeps DOM in sync with the model:

```
        note.polygon.addEventListener('remove', e => {
            this._deleteEdgeNode(e.detail.point, note);
            this.dispatchEvent(new CustomEvent('change'));
        });
```

**Comment by rr-** [comment]
Done, I wonder how many bugs I have introduced:

fdad08e176b52f1b47930a5e9b22116c70c542a8
eda6d6d02a4e09a61b05b5ad1b06f4594e15b602

**Comment by Darksonn** [comment]
It seems to work.
