### ISSUE TITLE
Unable to upload a file which was previously uploaded, then deleted

### ISSUE THREAD

**Issue by seanakabry** [rr-/szurubooru#128]
When I try to upload an image which was previously uploaded and deleted, I get:

> One of the posts needs your attention; click “resume upload” when you’re ready.

and

> Post # not found.

where `#` is the number of the original post.

I've tried:
- checking that the post was actually deleted from the `post` table in the database (it was); and
- deleting the image and thumbnail from the filesystem (which were still there),

but to no avail.

A savvier friend has helped me lock down the `user` table to prevent new user registrations, but I'm able to upload new images without issue.

Are checksums stored/cached somewhere else?

Thanks for the excellent software. (FWIW, I'm hoping to use szurubooru as an architectural reference pastebook and don't know why boorus aren't used more widely.)

**Comment by rr-** [comment]
Hmm maybe it's cached in elasticsearch? Investigating

**Comment by rr-** [comment]
Hmm, I can't reproduce the issue and I am able to reupload the same file after deleting it first without problems.

Can you show me the way you locked down the `user` table?

The correct way to restrict creating new user registration is to configure the booru by putting in the `config.yml` file a stub like this:

```
privileges:
    'users:create':                 administrator
```

and then recompiling the front-end and restarting the server.

**Comment by seanakabry** [comment]
User registrations were locked at nginx level (`POST` to `/api/users`), but the problem seems to persist even when this is removed.

From the logs, when I try to re-upload an image which was previously uploaded and then deleted:

> Exception ignored in: <generator object scan at 0x7f1edad4bd58> Traceback (most recent call last): File "/opt/szurubooru/server/python_modules/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 324, in scan client.clear_scroll(body={'scroll_id': [scroll_id]}, ignore=(404, )) File "/opt/szurubooru/server/python_modules/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped return func(*args, params=params, **kwargs) File "/opt/szurubooru/server/python_modules/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 976, in clear_scroll params=params, body=body) File "/opt/szurubooru/server/python_modules/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout) File "/opt/szurubooru/server/python_modules/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request self._raise_error(response.status, raw_data) File "/opt/szurubooru/server/python_modules/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info) elasticsearch.exceptions.RequestError: <exception str() failed> [2017-03-12 10:53:55] szurubooru.middleware.request_logger POST /posts/reverse-search (user=test1, queries=2)

Software versions:

* Build 2.2-64-g49feb93 - szuru build
* psql (PostgreSQL) 9.5.6
* nodejs -v v7.7.1
* Python 3.5.2

> Elasticsearch info: { "status" : 200, "name" : "Fly", "cluster_name" : "elasticsearch", "version" : { "number" : "1.7.3", "build_hash" : "NA", "build_timestamp" : "NA", "build_snapshot" : false, "lucene_version" : "4.10.4" }, "tagline" : "You Know, for Search" }

Thanks for looking into this, and your fast reply.

**Comment by rr-** [comment]
Something's up with elasticsearch - is it up?

**Comment by seanakabry** [comment]
Yep, elasticsearch is definitely running. This is what I see:

<img width="712" alt="screen shot 2017-03-12 at 13 04 59" src="https://cloud.githubusercontent.com/assets/6645292/23831642/d6a3af3a-0779-11e7-8611-804141e8354e.png">

**Comment by rr-** [comment]
I've pushed https://github.com/rr-/szurubooru/commit/7044d2aaee5733a9d9b0f242ee98e8d4a3750264 that ignores elasticsearch results that refer to deleted posts. 

Deleted posts should get removed from ES to avoid exactly this issue, and [this is the code](
https://github.com/rr-/szurubooru/blob/master/server/szurubooru/func/posts.py#L376-L380) that takes care of it:

```python
@sa.events.event.listens_for(model.Post, 'before_delete')
def _before_post_delete(
        _mapper: Any, _connection: Any, post: model.Post) -> None:
    if post.post_id:
image_hash.delete_image(post.post_id)
```

I have no idea why they seem to stay in your DB. In any case, it's a good idea to protect against corrupt ES index anyway.

Does the patch help?

**Comment by seanakabry** [comment]
Thanks, that did it!

I'm not sure if this is related, but we noticed what appears to be a bug after starting with a fresh database and config in the latest version of Chrome on OSX (56.0.2924.87, 64-bit), where thumbnails don't appear on the upload page:

<img width="730" alt="screen shot 2017-03-13 at 15 14 54" src="https://cloud.githubusercontent.com/assets/6645292/23859007/66e93fa6-0856-11e7-9ca8-9dbd3d09b3d2.png">

I hesitate to mention it though, because while this happens on my friend's machine, I can't reproduce the issue in the same version of Chrome in OSX or Windows.

I'll post again if we work out what's causing it. Thanks again for this fix!

**Comment by rr-** [comment]
This is known behavior and there's no practical way to have the image appear in the upload form.

The site pasted in the upload form checks for `Referer:` HTTP header, which the browser sets to the address of the booru. This behavior cannot be overridden. The target site doesn't like that URL and probably shows something like "no hotlinking!" or redirects the request to their main page - in both cases the HTML `<img/>` tag is unable to render the image and defaults to the dummy transparency grid that's rendered underneath it.

This problem doesn't prevent you from uploading the image though - the `Referer` read-only restriction doesn't apply outside the browsers world, and thus the booru server can spoof the `Referer` header effectively bypassing the hotlink protection.
