### ISSUE TITLE
Feature request: Disable content safety ratings / Hide content safety UI elements

### ISSUE THREAD

**Issue by seanakabry** [rr-/szurubooru#129]
Because content safety ratings are so prominent in the UI, I think it would be useful for boorus intended only for SFW content to have the option of switching safety ratings off in config.yaml.

(I'll take no offence is this isn't taken on and the issue is closed.)

**Comment by rr-** [comment]
Hmm, I'll add it but it's nontrivial how to treat API requests.

I have no idea regarding the UTF-8 problem though

**Comment by rr-** [comment]
I guess I won't be making changes to API. Rationale: if the users decide to turn on content safety ratings after all, and someone was purposefully uploading unsafe content through API rather than the site, the users will have less work to do with readjusting the safety for existing posts.

**Comment by seanakabry** [comment]
Thank you!

And thank you anyway re: the UTF-8 issue. I'll comment again on #121 if I find out what's happening.

**Comment by rr-** [comment]
Do you wish to remove the safety from upload form and posts sidebar as well?

**Comment by rr-** [comment]
I've taken the liberty to guess and removed the safety from upload form and posts sidebar in 77bf3bdc3c0c1b9e5746e0f3f63281360c3e5a03.

To disable safety ratings, please set `enable_safety` to `false` in `config.yaml`.

**Comment by seanakabry** [comment]
Thank you for implementing this so quickly, and sorry for my slow reply.

**Comment by seanakabry** [comment]
This doesn't bother me personally, but the content safety radio buttons still remain in the 'Basic info' when editing an individual post. Would it make sense to hide this also?
