### ISSUE TITLE
Internal server error when no data

### ISSUE THREAD

**Issue by tyxieblub** [rr-/szurubooru#130]
There is actually an error that is raised on a fresh install with no data. It is due to the assert in _get_disk_usage():
Since the value is initialized to 0, the assert is meant to fail when data_dir is empty.

```python
def _get_disk_usage() -> int:
    global _cache_time, _cache_result  # pylint: disable=global-statement
    threshold = timedelta(hours=48)
    now = datetime.utcnow()
    if _cache_time and _cache_time > now - threshold:
        assert _cache_result
        return _cache_result
    total_size = 0
    for dir_path, _, file_names in os.walk(config.config['data_dir']):
        for file_name in file_names:
            file_path = os.path.join(dir_path, file_name)
            total_size += os.path.getsize(file_path)
    _cache_time = now
    _cache_result = total_size
    return total_size
```
Is a there a reason for having an assert here instead of a simple `if` like this?:
 
```python
if _cache_time and _cache_time > now - threshold:
    if _cache_result:
        return _cache_result
```

**Comment by rr-** [comment]
Thanks for the report.
I believe that `assert` was introduce to silence mypy about cast of `Optional[int]` to `int`.
I've changed it to a more valid assertion in a1b762c65fe5bc309bbbec8be2873a660e905a62.

**Comment by tyxieblub** [comment]
I just tested it in a new instance and it works fine.
Thanks for the quick fix!
