### ISSUE TITLE
Detailed API guides on how the clients process JSON

### ISSUE THREAD

**Issue by DonaldTsang** [rr-/szurubooru#131]
The Hydrus Network would like to use the Szurubooru web client for its own database.
It would be great if there is a detailed description of how the web client process JSON,
so that the Hydrus database can create a similar JSON API to use the same web client.
https://hydrusnetwork.github.io/hydrus/

**Comment by rr-** [comment]
I don't understand what's being asked. The API used by the frontend is described here: https://github.com/rr-/szurubooru/blob/master/API.md

Also if you're planning on using verbatim szurubooru's code, you need to relicense Hydrus to GPL.

**Comment by DonaldTsang** [comment]
Assuming Szurubooru directly do client-server communication through the JSON API...
The Hydrus server (using WTFPL, GPLv3 compatible) will need to adapt to have a compatible API with Szurubooru web client, while being separate codebases.

**Comment by rr-** [comment]
>WTFPL, GPLv3 compatible

Sorry, I didn't know it. I vaguely remembered that GPL recommends against using it and I unconsciously just assumed they must be incompatible.

Anyway, the frontend communicates using only the API described in the document above and thus I'm closing this issue. The only undocumented exception, as far as I remember, is how the page that shows a specific post retrieves the ID of the next post and the previous post.

Please bear in mind that I still recommend against using verbatim szurubooru code. I'm not proud of its code in the slightest - it uses a home-made MVC framework, whereas these days I would try to go for something like AngularJS, or something better than JS that compiles to web assembly (I believe the latter will become a thing very soon). I think you'll have hard time adjusting the existing code it to your project's needs. I'd only borrow CSS and design and would write the code from the ground up.
