### ISSUE TITLE
Certain actions require manual browser refresh

### ISSUE THREAD

**Issue by mserajnik** [rr-/szurubooru#134]
This might not be a bug and instead working as intended, but it is quite annoying.

Example: after adding a new tag category, you can't apply it to a tag before refreshing the window (it simply isn't there in the select box).

Another example: after choosing a tag category for a tag it won't show the tag category's color without refreshing the window.

I understand that this is a little bit more complicated than in your usual web applications because szurubooru is using XHRs for everything but I thought that it would fetch an updated set of data containing the changes after such actions.

**Comment by mserajnik** [comment]
Okay, this is most likely some client-side caching issue, because when I open the dev console in Chrome, I can actually see it fetching the updated tags.json and everything works fine (I have caching disabled when the console is open).

Any way to circumvent this issue other than by setting `Cache-Control: no-cache`?

<img width="1438" alt="updated_tags" src="https://user-images.githubusercontent.com/28833155/29244955-08dcf08e-7fc9-11e7-8d80-670732a6c8d5.png">

**Comment by rr-** [comment]
`tags.json` gets cached as per nginx rules for GET requests for plain text files.
It might make sense to configure nginx so that it always invalidates the cache.

**Comment by mserajnik** [comment]
Thanks for the information, this makes sense.
