### ISSUE TITLE
Installing Failure 

### ISSUE THREAD

**Issue by KarelWintersky** [rr-/szurubooru#139]
I'm trying install szurubooru inside docker.

BASE image: base/archlinux

Installation failed at step 'systemctl start postgresql'

```
[root@565180e785eb /]# sudo -i -u postgres initdb --locale en_US.UTF-8 -E UTF8 -D /var/lib/postgres/data
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgres/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgres/data -l logfile start

[root@565180e785eb /]# systemctl start postgresql
Failed to connect to bus: No such file or directory
```

Any hints?
What about **correct** dockerfile?

**Comment by rr-** [comment]
Looks like you're trying to put all the services behind a single docker instance. This makes no sense. More on that: https://stackoverflow.com/a/39169889

The installation guidelines describe the process how to set up szurubooru *on a vanilla arch linux*; if you're planning to use docker, the set up will be different. Basically you should use separate docker instances for each dependency (postgres, elasticsearch etc.) and create a custom dockerfile only for szurubooru itself (without using systemd, mind you).

**Comment by KarelWintersky** [comment]
My host system is gentoo. 

I **must** use separate docker processes for each dependency or can implement all in one container?

**Comment by KarelWintersky** [comment]
inside docker i have _vanilla_ arch linux :D

**Comment by KarelWintersky** [comment]
Multiply containers for each dependency is a good idea for production server. And is NOT a good idea for testing.

**Comment by rr-** [comment]
You won't be able to emulate certain features in docker and the error you are getting is an example of that.
The installation guidelines are just an example, I don't see why you couldn't install the same software in gentoo.

**Comment by KarelWintersky** [comment]
My sys/admin skills is not too high. May be you can deploy demo version of your engine?

**Comment by rr-** [comment]
No, I do not have the time to do that.
