### ISSUE TITLE
How to get more feedback than just thumbs up/down

### ISSUE THREAD

**Issue by HeikoTietze** [rr-/szurubooru#142]
I want to present images and ask people on a couple of scales how they like it. Something like "How well does this image fit into the system?" 1=not at all..5=perfect; "How easy can this image be modified?" 1..5 etc. Is that possible out of the box?

**Comment by rr-** [comment]
Not really, you can get such feedback only through comments under the images. Users may vote for comments in similar fashion, which should reduce comment redundancy/duplication somewhat.

**Comment by HeikoTietze** [comment]
Thanks for your feedback, will consider your solution. Sorry for late reply.
