### ISSUE TITLE
Automatic resizing for featured posts

### ISSUE THREAD

**Issue by mserajnik** [rr-/szurubooru#144]
It seems like the automatic resizing isn't working for featured posts. All elements with class `resize-listener` currently just get the original size of the image assigned. This causes the image to be displayed in full size regardless of the window size. No JS errors in the console.

<img width="729" alt="featured_post_resizing" src="https://user-images.githubusercontent.com/28833155/34054347-ccfb0524-e1ca-11e7-9c99-cc22d2e1e16d.png">

I assume the resizing on the frontpage should probably always behave like the fit mode "both" on post views? Or is this a missing feature rather than a bug?

**Comment by mserajnik** [comment]
Okay, I noticed it just uses what fit mode is selected in post views.

I think it would still be better to just have it use the "both" mode on the frontpage since the user can just open the post view via the link below the featured post if he wants to view it in full size. I can create a PR for that if you want me to.

**Comment by rr-** [comment]
Please send a PR.
