### ISSUE TITLE
File hash searching

### ISSUE THREAD

**Issue by DonaldTsang** [rr-/szurubooru#148]
Able to search files using `hash:` with these types
* MD5 (128 bits)
* SHA1 (160 bits)
* SHA256 (256 bits)

**Comment by rr-** [comment]
Why?

**Comment by DonaldTsang** [comment]
Those features exists in many boorus like danbooru, gelbooru and sanakau,  
so that you can find the carbon-copy of a file.  
also, it can prevent file duplicates.

**Comment by rr-** [comment]
You can't upload duplicates either way, the server already checks for it during file upload.
(It also performs reverse search for you in the frontend so even if the files are only similar, it presents you with choice whether to upload the image or not.)

SHA1 checksums are already implemented via `content-checksum` token in post search.
https://github.com/rr-/szurubooru/blob/master/API.md#listing-posts

I don't see any need to store anymore hashes.

**Comment by DonaldTsang** [comment]
I would say cross-compatibility with Gelbooru, which uses MD5,  
and by extension, many other *boorus uses MD5 as a standard.  
Danbooru and Sankaku will accept SHA1 though.

**Comment by rr-** [comment]
OK

**Comment by DonaldTsang** [comment]
For further reference: https://ibsearch.xxx/

**Comment by sgsunder** [comment]
Closing this for now. If there seems to be a high demand for this feature, please make a PR.

**Comment by sgsunder** [comment]
MD5 checksums now returned in 2bdb072296633e444ec63eee45eea33272dfaefc and searchable in 2dfd1c2192961065fc27785c31cd86f7ceb82412
