### ISSUE TITLE
Proposal: use CSS-based resizing

### ISSUE THREAD

**Issue by mserajnik** [rr-/szurubooru#149]
The current JavaScript-based resizing has some issues, especially on mobile/iOS devices (see #133).

There are also sporadic hiccups in desktop browsers where it calculates the width or height a few pixels off (mostly when resizing the viewport) resulting in imaginary lines drawn between the elements not aligning and the view looking off.

Therefore, I'd like to propose replacing the JS-based solution with a pure CSS solution. I've prepared a simple mockup that should give an idea of how this could work: https://codepen.io/mserajnik/full/ypaMZV/

This solution would be viable for the post view where the medium can take the full height of the viewport minus the navigation bar (which could simply be calculated using `calc()`).

It's a little more difficult in the home view where there are text elements which can of course be dynamic in height. A possible solution for that would be to lay out the vertical structure in the home view with Flexbox and give the container containing the medium the `flex: 1` property to use the remaining available space (of course, there should still be a minimum height even if that causes scrolling on very small screens like landscape phones). This would make it possible to use a form of the `both` mode there as well (as it's currently the case too, although not working perfectly, especially on smaller screens).

Browser support shouldn't need to be considered since I've not used any CSS features more advanced than what's already in use somewhere; therefore, the requirements wouldn't change.

**Comment by rr-** [comment]
OK sounds good

**Comment by rr-** [comment]
Just remember about the 'upscale small posts' setting in user settings

**Comment by mserajnik** [comment]
Thanks for reminding me – I'll look into that in the coming days to see how this currently behaves and how I can replicate it for the new resizing.

**Comment by mserajnik** [comment]
Merging and closing #164 didn't close this one as well for some reason even though I've used an [issue closing keyword](https://help.github.com/articles/closing-issues-using-keywords/).

Therefore: closed.
