### ISSUE TITLE
Getting "Error connecting to elastic search" when trying to upload anything

### ISSUE THREAD

**Issue by Granddao** [rr-/szurubooru#150]
Hello,

I set up szuru on my Debian 8 box with everything from postgresql to elasticsearch. I can verify my elastic search is running and I here a sample response. 

> dao@dere:~/szuru/server$ curl localhost:9200
> {
>   "name" : "V3mI3aK",
>   "cluster_name" : "elasticsearch",
>   "cluster_uuid" : "hk0IFOE1Q5qFAP8DunCIgQ",
>   "version" : {
>     "number" : "6.1.2",
>     "build_hash" : "5b1fea5",
>     "build_date" : "2018-01-10T02:35:59.208Z",
>     "build_snapshot" : false,
>     "lucene_version" : "7.1.0",
>     "minimum_wire_compatibility_version" : "5.6.0",
>     "minimum_index_compatibility_version" : "5.0.0"
>   },
>   "tagline" : "You Know, for Search"
> }

Everything is up and running. I run the api server using gunicorn. Here's my config.yml

> name: <name>
> debug: 0
> show_sql: 0
> transpile: 1
> secret: kdnfskdfsi00
> api_url: 'https://domainhere/api'
> base_url: 'https://domainhere/'
> data_url: 'https://domainhere/data/'
> data_dir: '/home/userhere/szuru/client/public/data/'
> user_agent:
> 
> database:
>     postgres://user:pass@localhost:5432/db
> 
> thumbnails:
>     avatar_width: 300
>     avatar_height: 300
>     post_width: 300
>     post_height: 300
> 
> smtp:
>     host: smtp.gmail.com
>     port: 587
>     user: email
>     pass: pass
> 
> contactEmail: <email>
> 
> elasticsearch:
>     host: localhost
>     port: 9200
>     index: szurubooru
> 
> enable_safety: yes
> 
> tag_name_regex: ^\S+$
> tag_category_name_regex: ^[^\s%+#/]+$
> 
> password_regex: '^.{5,}$'
> user_name_regex: '^[a-zA-Z0-9_-]{1,32}$'
> 
> default_rank: regular
> 
> privileges:
>     'users:create':                 anonymous
>     'users:list':                   regular
>     'users:view':                   regular
>     'users:edit:any:name':          moderator
>     'users:edit:any:pass':          moderator
>     'users:edit:any:email':         moderator
>     'users:edit:any:avatar':        moderator
>     'users:edit:any:rank':          moderator
>     'users:edit:self:name':         regular
>     'users:edit:self:pass':         regular
>     'users:edit:self:email':        regular
>     'users:edit:self:avatar':       regular
>     'users:edit:self:rank':         moderator # one can't promote themselves or anyone to upper rank than their own.
>     'users:delete:any':             administrator
>     'users:delete:self':            regular
> 
>     'posts:create:anonymous':       regular
>     'posts:create:identified':      regular
>     'posts:list':                   anonymous
>     'posts:reverse_search':         regular
>     'posts:view':                   anonymous
>     'posts:view:featured':          anonymous
>     'posts:edit:content':           power
>     'posts:edit:flags':             regular
>     'posts:edit:notes':             regular
>     'posts:edit:relations':         regular
>     'posts:edit:safety':            power
>     'posts:edit:source':            regular
>     'posts:edit:tags':              regular
>     'posts:edit:thumbnail':         power
>     'posts:feature':                moderator
>     'posts:delete':                 moderator
>     'posts:score':                  regular
>     'posts:merge':                  moderator
>     'posts:favorite':               regular
>     'posts:bulk-edit:tags':         power
>     'posts:bulk-edit:safety':       power
> 
>     'tags:create':                  regular
>     'tags:edit:names':              power
>     'tags:edit:category':           power
>     'tags:edit:description':        power
>     'tags:edit:implications':       power
>     'tags:edit:suggestions':        power
>     'tags:list':                    regular
>     'tags:view':                    anonymous
>     'tags:merge':                   moderator
>     'tags:delete':                  moderator
> 
>     'tag_categories:create':        moderator
>     'tag_categories:edit:name':     moderator
>     'tag_categories:edit:color':    moderator
>     'tag_categories:list':          anonymous
>     'tag_categories:view':          anonymous
>     'tag_categories:delete':        moderator
>     'tag_categories:set_default':   moderator
> 
>     'comments:create':              regular
>     'comments:delete:any':          moderator
>     'comments:delete:own':          regular
>     'comments:edit:any':            moderator
>     'comments:edit:own':            regular
>     'comments:list':                regular
>     'comments:view':                regular
>     'comments:score':               regular
> 
>     'snapshots:list':               power
> 
>     'uploads:create':               regular

Still don't know why it can't connect to elasticsearch...

**Comment by mserajnik** [comment]
Hmm, I‘m also running it on Debian without issues.

I‘m not currently at home so I can‘t look into it further, but if you want you can take a look at my installation script to see if that basically matches your setup: https://scripts.mserajnik.at/stash/szurubooru/install.debian

It‘s missing some last steps like nginx configuration and gunicorn/supervisor installation though which I always do manually.

**Comment by Granddao** [comment]
@mserajnik Yep, I basically did the same thing and only things are different is szuru is run from my home directory and I am running elasticsearch v. 6.1.2 also I am missing dirmngr, not sure what that do?

**Comment by mserajnik** [comment]
@Granddao It's been a while since I've written that script, but I think I needed dirmngr for running `wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -` because otherwise I'd get the error `gpg: keyserver receive failed: No dirmngr`. Not 100% sure about that, I'm not a sysadmin expert by any stretch. ^^

Here's my whole installation process that describes how to install szurubooru after setting up a new Debian box. I've taken it directly from a guide I wrote for myself. I've also just noticed I'm actually running Debian 9, so it might be a little different for you: https://scripts.mserajnik.at/stash/szurubooru/szurubooru_installation.md

I always install Debian from a full disk image before following that guide, selecting just the "SSH tools" (I'm not sure what they're actually called, something like that) when prompted, no GUI and no web servers.

Hope that's somewhat helpful to you, I'm sure there are better/easier ways to set this up but that's what has worked for me in the past (and I regularly set up a new box every 2-3 months). As I've said, I'm no expert and I'm not experience enough with elasticsearch to tell you what's going wrong. :/

**Comment by mserajnik** [comment]
And here's my `config.yaml`:

```
# rather than editing this file, it is strongly suggested to create config.yaml
# and override only what you need.

name: szurubooru # shown in the website title and on the front page
debug: 0 # generate source maps for JS debugging?
show_sql: 0 # show sql in server logs?
transpile: 1 # generate bigger JS to support older browsers?
secret: secret # used to salt the users' password hashes
api_url: https://server.com/api/ # where frontend connects to, example: http://api.example.com/
base_url: https://server.com/ # used to form links to frontend, example: http://example.com/
data_url: https://server.com/data/ # used to form links to posts and avatars, example: http://example.com/data/
data_dir: /var/www/szurubooru/client/public/data # absolute path for posts and avatars storage, example: /srv/www/booru/client/public/data/
user_agent: # user agent name used to download files from the web on behalf of the api users


# usage: schema://user:password@host:port/database_name
# example: postgres://szuru:dog@localhost:5432/szuru_test
# example (useful for tests): sqlite:///:memory:
database: postgres://szuru:password
test_database: 'sqlite:///:memory:' # required for running the test suite


thumbnails:
    avatar_width: 300
    avatar_height: 300
    post_width: 300
    post_height: 300


# used to send password reset e-mails
smtp:
    host: smtp.server.com # example: localhost
    port: 587 # example: 25
    user: admin@server.com # example: bot
    pass: password # example: groovy123
    # host can be left empty, in which case it is recommended to fill contactEmail.


contactEmail: admin@server.com # example: bob@example.com. Meant for manual password reset procedures


# used for reverse image search
elasticsearch:
    host: localhost
    port: 9200
    index: szurubooru


enable_safety: yes

tag_name_regex: ^\S+$
tag_category_name_regex: ^[^\s%+#/]+$


# don't make these more restrictive unless you want to annoy people; if you do
# customize them, make sure to update the instructions in the registration form
# template as well.
password_regex: '^.{5,}$'
user_name_regex: '^[a-zA-Z0-9_-]{1,32}$'

default_rank: regular


privileges:
    'users:create':                 regular
    'users:list':                   regular
    'users:view':                   regular
    'users:edit:any:name':          moderator
    'users:edit:any:pass':          moderator
    'users:edit:any:email':         moderator
    'users:edit:any:avatar':        moderator
    'users:edit:any:rank':          moderator
    'users:edit:self:name':         regular
    'users:edit:self:pass':         regular
    'users:edit:self:email':        regular
    'users:edit:self:avatar':       regular
    'users:edit:self:rank':         moderator # one can't promote themselves or anyone to upper rank than their own.
    'users:delete:any':             administrator
    'users:delete:self':            regular

    'posts:create:anonymous':       power
    'posts:create:identified':      power
    'posts:list':                   regular
    'posts:reverse_search':         regular
    'posts:view':                   regular
    'posts:view:featured':          regular
    'posts:edit:content':           power
    'posts:edit:flags':             power
    'posts:edit:notes':             power
    'posts:edit:relations':         power
    'posts:edit:safety':            power
    'posts:edit:source':            power
    'posts:edit:tags':              power
    'posts:edit:thumbnail':         power
    'posts:feature':                moderator
    'posts:delete':                 moderator
    'posts:score':                  power
    'posts:merge':                  moderator
    'posts:favorite':               regular
    'posts:bulk-edit:tags':         power
    'posts:bulk-edit:safety':       power

    'tags:create':                  power
    'tags:edit:names':              power
    'tags:edit:category':           power
    'tags:edit:description':        power
    'tags:edit:implications':       power
    'tags:edit:suggestions':        power
    'tags:list':                    regular
    'tags:view':                    regular
    'tags:merge':                   moderator
    'tags:delete':                  moderator

    'tag_categories:create':        moderator
    'tag_categories:edit:name':     moderator
    'tag_categories:edit:color':    moderator
    'tag_categories:list':          regular
    'tag_categories:view':          regular
    'tag_categories:delete':        moderator
    'tag_categories:set_default':   moderator

    'comments:create':              power
    'comments:delete:any':          moderator
    'comments:delete:own':          power
    'comments:edit:any':            moderator
    'comments:edit:own':            power
    'comments:list':                regular
    'comments:view':                regular
    'comments:score':               power

    'snapshots:list':               power

    'uploads:create':               power
```

**Comment by rr-** [comment]
Please try adding `action.auto_create_index: true` at the end of `/etc/elasticsearch/elasticsearch.yml`. That's the only thing that comes to my mind.

**Comment by Granddao** [comment]
Hey thanks for all the help, I will try that rr- and report back. And thanks mserajnik for that script I am thinking of just redoing install. Will come in handy there.
