### ISSUE TITLE
Passwords Containing ':' Cause a Malformed Authentication Header

### ISSUE THREAD

**Issue by TehTotalPwnage** [rr-/szurubooru#152]
I ran into this issue when setting up my own installation of szurubooru. I use KeePassX (a password manager) to generate all my passwords, so when one of my passwords contained a ':' character, the installation proceeded to say: `Basic authentication header value are not properly formed.`

The specific error that came up was this: `ValueError: too many values to unpack`

I proceeded to pull my hair out over this issue for roughly 15 minutes before reading up on Basic Authentication on [Wikipedia](https://en.wikipedia.org/wiki/Basic_access_authentication), realizing that the last colon in the password field was what was likely causing Python to flip out on authentication.

While I do understand this is a rare use case, I think it might be worth considering addressing this problem in the case that someone manages to run into the same thing. It's really a matter of deciding how to deal with the possibility of colons in a password, whether it be rewriting the authentication function to not flip out on additional colon characters or simply adding validation on both the client and server side to guarantee that a colon can't accidentally be registered in the database (I ended up having to use psql to change my password to a working one to log into my instance).

Speaking of validation, I haven't looked at more of the code, but is there any chance that the username isn't being validated for the colon character either?

**Comment by rr-** [comment]
Thanks for the report. The issue has been fixed in a1fbeb91a0984f5daf477a8813dc03979d4ae136 .
User names are not affected as long as you don't change the default user name mask, `^[a-zA-Z0-9_-]{1,32}$`, which does not allow colons.
