### ISSUE TITLE
"Parameter ‘tags’ must be a list of string values" when copying tags from existing post

### ISSUE THREAD

**Issue by TehTotalPwnage** [rr-/szurubooru#153]
I uploaded two versions of the same picture onto my personal booru setup and the uploader warned me about the two images having a very high similarity. I opted to add a relation between the two images and to copy the tags from the old image to the new one, but when pressing upload, the uploader states `One of the posts needs your attention; click “resume upload” when you’re ready.` with the error on the image being `Parameter ‘tags’ must be a list of string values.`.

I've managed to reproduce this with other images, which seems to suggest that the issue isn't limited to just that image. Aside from that, I can't think of much else that might be the cause of the issue.

**Comment by ReAnzu** [comment]
It looks like the issue was in the client sending all of the tag data, when the API expected only a list of tag names.

**Comment by rr-** [comment]
Fix merged in HEAD. Thanks
