### ISSUE TITLE
Allow for fetching of client side configs during runtime?

### ISSUE THREAD

**Issue by sgsunder** [rr-/szurubooru#168]
Is there any reason why some of the client-side configurations have to be built beforehand, instead of being fetched from the server at runtime?

Specifically, the privileges and password, username, and tag regexes in the config.yaml file could be fetched from the server as needed, instead of being baked into a JSON file at buildtime. I also noticed that `info_api.py` on the server side already provides this functionality.

The reason I ask this is because being able to hold off on providing the config.yaml file until runtime will make it much easier to run within Docker. I'm already using a Docker deployment and it works quite well and plays nicely with official postgres and elasticsearch images, however the fact that I can't run `node build.js` until after I've passed a config file in makes orchestration really clunky.

**Comment by rr-** [comment]
There's no real reason other than the info API being an afterthought (hence the technical debt you pointed out). If you wish to change this behavior, I encourage you to fire a PR.
