### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by MaxValue** [rr-/szurubooru#173]
I am currently in the process of installing szurubooru for the first time.

After setting up the python venv I installed the requirements.txt. Nearly every module threw this error. A short google research told me that I have to install the 'wheel' package first. Hmm.

Can you add this 'wheel' package somehow to the requirements/dependencies so it just installs itself?

Thanks in advance!

**Comment by ev1l0rd** [comment]
`wheel` is installed during a normal `pip` install. Not having it would indicate that your `pip` installation is broken. Try reinstalling `pip`.

If it is properly installed, then your venv might not have it installed. Try recreating the venv.

**Comment by MaxValue** [comment]
I redid the whole installation again and now no error is thrown during installing `requirements.txt`. Weird.

But it works now!
