### ISSUE TITLE
npm module ' babel-preset-es2015' is deprecated in favor of 'babel-preset-env'

### ISSUE THREAD

**Issue by MaxValue** [rr-/szurubooru#174]
When going through the normal [installation process](https://github.com/rr-/szurubooru/blob/master/INSTALL.md#preparing-environment) and running `npm install`, it gives the following error message (building works fine though):
`npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!`

**Comment by mserajnik** [comment]
Yup, it's just a deprecation warning and the build should still work fine.

@rr- Think we should update the dependencies soon? I can look into that if you want me to, maybe after #172 is merged?

**Comment by rr-** [comment]
@mserajnik yeah, I'd appreciate a PR. I left a couple of notes for #172; the soonest they get addressed I'll test it on my instance and merge it.

**Comment by rr-** [comment]
#172 Merged

**Comment by mserajnik** [comment]
Thanks, I'll see to get to it in the coming days, @rr-.
