### ISSUE TITLE
Installation process: 'test' script for running tests does not exist

### ISSUE THREAD

**Issue by MaxValue** [rr-/szurubooru#179]
In the [installation guide](https://github.com/rr-/szurubooru/blob/master/INSTALL.md#preparing-szurubooru-for-first-run), the last step asks to run the tests through `(python_modules) USERNAME@MACHINE:~/Path-To-Git-Clone/server$ ./test`.
This test script does not exist. Going to the repo root and doing `find . -name 'test'` only returns files and dirs under `client/node_modules/` which I guess are not the meant files.

**Comment by rr-** [comment]
Fixed in https://github.com/rr-/szurubooru/commit/320c16743d8bef19f0f88c614b1336add1f7db87
