### ISSUE TITLE
Proposal: add web app manifest

### ISSUE THREAD

**Issue by mserajnik** [rr-/szurubooru#181]
Having a web app manifest would allow users to add szurubooru to the home screen on their mobile devices, making it behave somewhat like a native app in the sense that it could have its own app icon, and opening it would first show a splash screen and then a "fullscreen" browser without status bar (_standalone mode_).

It's basically just a single JSON file (`manifest.json`) that needs to be placed into `public`, plus some stuff we can put inside `<head>` to make it play even nicer (iOS needs some special treatment here).

It would be a quick addition that makes using szurubooru on mobile devices just a bit better. If approved, I can start a PR.

See [here](https://developers.google.com/web/fundamentals/web-app-manifest/) for more information. I would leave out the icon stuff for now, unless you have a high res version of the favicon (let's say 512x512) ready or want to use a different one. The icon would be used as the app icon as well as on the splash screen that would show when opening szurubooru in standalone mode (via the app icon).

If we don't have one, it will just use a screenshot of the application as the app icon, at least that's how it is on iOS. I don't really care because it doesn't affect functionality, but if we had an icon we could use, even better.

**Comment by rr-** [comment]
Yeah, this is something I'm willing to merge.
I'd use the favicon, which features Hiiragi Tsukasa from Lucky Star.

I believe I found a fairly close image to the one used by the favicon:
![-tsukasa-hiiragi-22346637-512-512](https://user-images.githubusercontent.com/1045476/42593422-ac65a32a-854c-11e8-8594-40fdad0e39a5.jpg)

**Comment by mserajnik** [comment]
Fyi, I'm gonna wait until #180 is merged.

**Comment by mserajnik** [comment]
@rr- Testing #180 you mean? Sure, I can do that. Will probably have to wait until Tuesday or Wednesday though.

**Comment by rr-** [comment]
That'd be great. Thanks :+1:
