### ISSUE TITLE
Tag on Upload

### ISSUE THREAD

**Issue by xeon927** [rr-/szurubooru#182]
Hey - just a quick question to see if there's any way to tag on upload - ie, when adding files/links, you have the option to choose "Safe", "Sketchy", or "Unsafe". Is there planned to be anything (like a text box in this general area) where I can add tags in while sorting out things to upload, then just press upload and walk away?

Thanks in advance :)

**Comment by rr-** [comment]
The project used to have this feature, but it ended up being in the way of our users, so I removed it.

It is possible to tag the images on upload through the API, of course.

I'm not against readding this feature, but it probably should be configurable. At any rate, I recommend PRs.

**Comment by mserajnik** [comment]
@xeon927

This is not exactly what you're looking for, but I've written a tool a while back that's intended for mass-importing files into szurubooru and can add tags automatically, if provided for a given media file. It can also create new tag categories and update tags for existing files.

The tool might work as a workaround for you – you can find it [here](https://github.com/mserajnik/szuruporter).

**Comment by legionfrontier** [comment]
I will appreciate it, Hydrus is hilariously uber complicated
