### ISSUE TITLE
Feature request: Update implications retroactively

### ISSUE THREAD

**Issue by noirscape** [rr-/szurubooru#189]
Currently, when making a tag structure (with implications), implications are not updated/applied/removed retroactively.

Example:
- Tag `ridley` is implicated towards the tag `metroid_(series)`.
- I upload several images and tag it as `ridley` after uploading, which adds the implication for `metroid_(series)`.
- Later I decide to implicate the tag `metroid_(series)` to a more global `nintendo` tag.
- I now have to update all these images by hand, which if the amount of images is exceptionally large (and assume that of course, I have more than one tag that `metroid_(series)` implicates), will take a large amount of time, even when I use the batch tagging feature).

**Comment by rr-** [comment]
That's what mass tag exists for

**Comment by noirscape** [comment]
> That's what mass tag exists for, I know it's not automated but it still saves a lot of time.

I'm aware it does, and up to a point, it certainly does, but eventually I just end up hitting a point where I have to retag a large amount of images.

> Maybe there could be a button for this.

I'm fine with this being a toggleable feature or adding an approve warning that this retroactively updates stuff and that caution(/backups) should be made.

> This is insane, how do you tell if something was tagged by hand or by a tag implication?

Admittedly... looking at it, that part was very poorly phrased, and indeed, looking at it seems to make little sense. I'll remove it from my original issue.

**Comment by GlassedSilver** [comment]
Good idea!
