### ISSUE TITLE
Docker version: API server port?

### ISSUE THREAD

**Issue by MaxValue** [rr-/szurubooru#191]
Hi!

How can I find out the port of the API server in the docker version? Using port 6666 returns this (using python3 requests):

> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6666): Max retries exceeded with url: /tag/bla (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa670346dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))

I used this request (python3 requests):
```python3
headers = {'Content-Type': 'application/json','Accept': 'application/json','Authorization':base64.b64encode(b'5761972d-5970-46f3-8e07-ac5d524625f0')}
test = requests.get('http://localhost:6666/tag/bla',headers=headers)
```

Maybe I specified something incorrectly? Or can I just use port 8080? (Which does only reply with empty html pages)

**Comment by MaxValue** [comment]
Okay, so I found out my mistakes. For anyone having similar problems:

- You can use `'Authorization'` in the headers dict when you make the request, no need to make that seperately. Of course it also works by using the `auth` parameter of the corresponding requests method (meaning like `requests.get` or `requests.delete`).
- You have to prefix all API calls with `/api/` so for example to get a specific post, this is the correct way:

```python3
headers = {'Content-Type': 'application/json','Accept': 'application/json','Authorization':'Token {}'.format(base64.b64encode(b'USERNAMEHERE:APITOKENHERE').decode('utf-8'))}
result = requests.get('http://127.0.0.1:8080/api/post/1',headers=headers)
```

Silly me.

**Comment by mserajnik** [comment]
@MaxValue

Fyi, you can also query all the API routes via basic authentication if that makes it easier for you to accomplish what you're trying to do, no need to generate tokens. See [here](https://github.com/mserajnik/szuruporter/blob/master/src/Helpers/ApiWrapper.php) for an example (in PHP, but it's the same in Python of course).

The benefit of basic authentication is that you don't have to worry about token expiration/refreshing, which can be a hassle (e.g., when running automated file imports that can take a very long time).

Of course, you're transmitting username and password in plaintext with every request in that case, so make sure you're using HTTPS if the traffic leaves your LAN.

That said, I do recommend using tokens over basic authentication whenever you're querying against an installation over a WAN (especially ones that you don't control). But if the traffic stays inside the local network it doesn't really matter and makes things a bit simpler.

**Comment by mserajnik** [comment]
@MaxValue

 Sorry, I didn't mean to confuse you.

> Why should the API tokens expire? I created the token through the GUI, therefore I expect it to be permanent. Maybe you mean sessions? But the documentation states that there are no sessions from server perspective.

Tokens expire at the end of the session by default. If the "remember me" option is used, the token expires after 365 days, iirc. You may be right that tokens won't expire if you have created them manually (instead of on login) or at least won't expire until after an arbitrarily long amount of time – but you should be able to check the expiration time in the GUI as well.

> Could we prefix all API paths in the documentation with „/api/“?

With #172, the `api_url` parameter is hardcoded to `/api` and no longer configurable via configuration. You would need to change [this](https://github.com/rr-/szurubooru/blob/master/client/js/api.js#L259) and [this](https://github.com/rr-/szurubooru/blob/master/client/nginx.conf.docker#L29-L34) to change it, iirc.

Probably won't hurt to add a small section called `Base URL` or something like that to `API.md` where it's mentioned where to find the API. Sure, we could always say just look at how the web frontend accesses it, but why do we have the API docs at all then?

Not sure if we need an actual code example in there, but I'm not against having it.

@rr-, what do you think?

**Comment by MaxValue** [comment]
> Tokens expire at the end of the session by default. If the "remember me" option is used, the token expires after 365 days, iirc. You may be right that tokens won't expire if you have created them manually (instead of on login) or at least won't expire until after an arbitrarily long amount of time – but you should be able to check the expiration time in the GUI as well.

Ah I know what you mean. This field when creating the token where you can set the expiration date. Yeah, I left it free and after saving, it showed "Forever". So you are saying even then tokens can expire? Can we document that somewhere or even better: add a note in the GUI?

> With #172, the api_url parameter is gone and the path is instead hardcoded to /api and no longer configurable via configuration. You would need to edit this and this to change it, iirc.

Thats actually good news! This means we can prefix all API routes/paths in the API documentation with `/api`! If its not changeable why even hide it? From my perspective, this is normal practice; All API documentations I used usually include the path prefix to access their API. See for example [Philips Hue](https://developers.meethue.com/philips-hue-api), [LIFX](https://api.developer.lifx.com/) or [Imgur](https://apidocs.imgur.com/). I will give you a pull request just to illustrate what I mean exactly.

> Sure, we could always say just look at how the web frontend accesses it, but why do we have the API docs at all then?

I agree totally. I tried to make sense of the docs, but legastenic/impatient me just wanted to see if the API works as expected. Thats why I had to use this unorthodox approach. Docs are always better.

**Comment by mserajnik** [comment]
> This field when creating the token where you can set the expiration date. Yeah, I left it free and after saving, it showed "Forever". So you are saying even then tokens can expire? Can we document that somewhere or even better: add a note in the GUI?

Nope, they shouldn't expire in that case (unless deleted manually). Sorry, I wasn't aware that creating tokens without any expiration date at all was a thing. :D
