### ISSUE TITLE
Feature request: Embed meta tags

### ISSUE THREAD

**Issue by jimmyy4** [rr-/szurubooru#203]
Meta tags so posts will embed in social media and chat platforms.

Twitter summary cards: https://dev.twitter.com/cards/types/summary
Open Graph tags: http://ogp.me/

**Comment by sgsunder** [comment]
Our client is written as a single-page web application, and those metatags only seem to be usable on static or server-generated web pages. I can't find a trivial way of accomplishing this.

Open to PRs if you can create an elegant way of accomplishing this, but closing this for now.
