### ISSUE TITLE
Feature request: Link to source image (Pixiv/DeviantART/Twitter)

### ISSUE THREAD

**Issue by Flanamo** [rr-/szurubooru#204]
Feature request for the ability to link a source to an image, as in to the original post of the art, like a Pixiv link or a twitter link.

**Comment by raku-cat** [comment]
I noticed when I was messing with the API there's actually a `source` field, and in fact if you update or create a post using the API you can set a source
https://github.com/rr-/szurubooru/blob/master/API.md#creating-post
https://github.com/rr-/szurubooru/blob/master/API.md#updating-post
There's nothing in the webui for this though, I might just be blind though.

**Comment by sgsunder** [comment]
Seems like you're right, this feature is already implemented in the backend. REST calls for this field gets mapped to a `source` column in the `post` table in the database. Just to make sure it's not meant for something else I ran a query `SELECT * FROM post WHERE source IS NOT NULL;`, which returns nothing, so it seems like an unused feature unless you're making external API calls.

Just need to implement it into the frontend then. A simple link called 'Source' can show up in the post view when this field is non-null, next to the reverse image search links. And a simple text field can be used for the post edit view.

**Comment by rr-** [comment]
We used to have this feature, but the users of our instance weren't really using it, so I had removed it back in the days when szurubooru was not so popular. I didn't touch the backend, though.

**Comment by Flanamo** [comment]
Ah so it's just the frontend that's missing it, didn't realize the API even mentioned a source I must've skimmed over it too fast.

**Comment by raku-cat** [comment]
I couldn't find anything in the commit history of where this was removed on the front-end, I have viewing at least working so far on my branch https://github.com/raku-cat/szurubooru/commit/1bfc7170b11d389cfdcf3a72ecf5fc400e6b5bf5
Haven't been able to get actually setting the source working yet though past having the field to do it show up.
![image](https://user-images.githubusercontent.com/1125449/50466261-26911c80-0962-11e9-9143-8c0451c6db3f.png)
![image](https://user-images.githubusercontent.com/1125449/50466266-298c0d00-0962-11e9-860b-aa26b97d6368.png)
![image](https://user-images.githubusercontent.com/1125449/50466270-327cde80-0962-11e9-858a-31a3c2a63578.png)

**Comment by rr-** [comment]
It's in the archived 1.x branch:
https://github.com/rr-/szurubooru/blob/1.x/public_html/templates/post.tpl#L166-L178
