### ISSUE TITLE
API adapter to allow for compatibility with Danbooru/Gelbooru/Moebooru/Shimme/MyImouto

### ISSUE THREAD

**Issue by DonaldTsang** [rr-/szurubooru#205]
List of apps that uses "standard APIs":
http://www.animebox.es/ (Android and iOS)
https://www.mignori.com/ (iOS only)
https://www.patreon.com/kinoshitaproductions (Android only)
https://github.com/tjg1/nori and https://github.com/onlymash/moebooru-android (FOSS Android)

**Comment by rr-** [comment]
Closing for the same reasons as in https://github.com/mserajnik/hydrusrv/issues/11 .

**Comment by joshqou** [comment]
The mentioned hydrus issue no longer exists wasn't archived by archive.is or archive.org, what were the reasons?

**Comment by skybldev** [comment]
There are a few libraries out there that support both protocols and I imagine it wouldn't be too hard to make a bridge using those. 

Also if it helps in any way fro your situation, I can clean up and gist a crude read-only danbooru->szurubooru API bridge I made for Anime Boxes a few years ago.

**Comment by decatetsu** [comment]
@skybldev Can you share API bridge without clean up? I want to use Anime Boxes with my szurubooru instance.

**Comment by skybldev** [comment]
Sure thing. I'll polish it up and publish it tomorrow.

**Comment by skybldev** [comment]
@decatetsu https://github.com/skybldev/szuru-danbooru-ro-bridge It's done

**Comment by decatetsu** [comment]
@skybldev Thank you!

**Comment by skybldev** [comment]
Wait a sec I just discovered a couple huge bugs, fixes coming up
