### ISSUE TITLE
So close to a successful install...

### ISSUE THREAD

**Issue by princessGasmask** [rr-/szurubooru#206]
I managed to get through the install process that's listed in the README. All of the dependencies installed properly and when I check running containers, all of the processes for Szuru are running perfectly fine. However, when I go to access the URL, I get the message "Could not fetch basic configuration from server." I feel like there's probably something super simple that I'm just missing out on. Would anyone be willing to nudge me in the correct direction? I'm running through Docker on Windows if that makes any difference. I can also provide a copy of the logs if that would help.

**Comment by DavidDeprost** [comment]
Most likely you just forgot step 1 of 'Running the application' in the INSTALL.md file: setting the vm.max_map_count parameter for ElasticSearch.
(See https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode)

On windows it should be as simple as entering the following 2 commands:
$ docker-machine ssh
$ sudo sysctl -w vm.max_map_count=262144

**Comment by noirscape** [comment]
Try starting docker with `docker-compose up` as well.

**Comment by WychWitch** [comment]
Hello! I'm having this problem as well. I also forgot step 1 when I was first setting up the server and set it now, despite that it's still not working correctly.

Here is the output of docker-compose up:
```
$ docker-compose up
Starting szuru_elasticsearch_1 ... done
Starting szuru_sql_1           ... done
Starting szuru_backend_1       ... done
Starting szuru_frontend_1      ... done
Attaching to szuru_elasticsearch_1, szuru_sql_1, szuru_backend_1, szuru_frontend_1
elasticsearch_1  | standard_init_linux.go:190: exec user process caused "exec format error"
sql_1            | 2018-12-22 20:55:00.100 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
sql_1            | 2018-12-22 20:55:00.101 UTC [1] LOG:  listening on IPv6 address "::", port 5432
sql_1            | 2018-12-22 20:55:00.198 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
sql_1            | 2018-12-22 20:55:00.721 UTC [17] LOG:  database system was shut down at 2018-12-22 20:40:17 UTC
sql_1            | 2018-12-22 20:55:01.111 UTC [1] LOG:  database system is ready to accept connections
szuru_elasticsearch_1 exited with code 1

```
Here is the output of grep and cat to show the settings were applied correctly.

```
$ grep vm.max_map_count /etc/sysctl.conf
vm.max_map_count=262144

$ cat /proc/sys/vm/max_map_count
262144
```

And finally, my system hardware:

```
OS: HypriotOS (v2.0.1) [Raspbian Stretch]
Hardware: Raspberry Pi 1 (ARM6l)
```

I can supply more information if needed!

**Comment by WychWitch** [comment]
I almost had it... I discovered [this](https://hub.docker.com/r/ind3x/rpi-elasticsearch/) docker image and figured out where the elasticsearch image was being pulled from! In the docker-compose.yml file I just had to change the images as follows:

```elasticsearch:
    image: ind3x/rpi-elasticsearch
```

After it pulled the image it worked fine until! I ran into this error

```
sql_1            | 2018-12-22 23:24:11.853 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
elasticsearch_1  | Java HotSpot(TM) Client VM warning: INFO: os::commit_memory(0x95000000, 520093696, 0) failed; error='Cannot allocate memory' (errno=12)
elasticsearch_1  | #
sql_1            | 2018-12-22 23:24:11.853 UTC [1] LOG:  listening on IPv6 address "::", port 5432
sql_1            | 2018-12-22 23:24:11.959 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
elasticsearch_1  | # There is insufficient memory for the Java Runtime Environment to continue.
sql_1            | 2018-12-22 23:24:12.547 UTC [17] LOG:  database systemwas shut down at 2018-12-22 20:57:54UTC
elasticsearch_1  | # Native memory allocation (mmap) failed to map 520093696 bytes for committing reserved memory.
elasticsearch_1  | # An error reportfile with more information is saved as:
elasticsearch_1  | # /tmp/hs_err_pid1.log
sql_1            | 2018-12-22 23:24:12.746 UTC [1] LOG:  database system is ready to accept connections
szuru_elasticsearch_1 exited with code 1
```

My tiny rpi simply isn't strong enough to run it. I'll edit this comment if I'm able to add a working swap partition! Otherwise I think it's time to throw the towel and get a rpi3 b+

**Comment by sgsunder** [comment]
You'd need an elasticsearch docker image that's compatible with ARM.

Perhaps this would help? https://stackoverflow.com/questions/46543198/running-elasticsearch-container-on-raspberry-pi-3

If not, you can also see if you can run the elasticsearch service on a seperate x86 machine or on the cloud, and talk to it over a network.

**Comment by WychWitch** [comment]
@sgsunder  That's exactly what I found! And after adding more memory with a swap the elastic seems to work fine!

However, now when going to the site itself (on my local area network) I got this error:

```
frontend_1       | 192.168.1.9 -> GET / HTTP/1.1 [200] - referer: - -
frontend_1       | 192.168.1.9 -> GET /css/app.min.css HTTP/1.1 [304] - referer: http://192.168.1.22:8080/ -
frontend_1       | 192.168.1.9 -> GET /css/vendor.min.css HTTP/1.1 [304] - referer: http://192.168.1.22:8080/ -
frontend_1       | 192.168.1.9 -> GET /js/vendor.min.js HTTP/1.1 [304] - referer: http://192.168.1.22:8080/ -
frontend_1       | 192.168.1.9 -> GET /js/app.min.js HTTP/1.1 [304] - referer: http://192.168.1.22:8080/ -
frontend_1       | 2018/12/23 00:22:59 [error] 7#7: *4 connect() failed (111: Connection refused)while connecting to upstream, client: 192.168.1.9, server: , request: "GET /api/info HTTP/1.1", upstream: "http://[external ip]:6666/info", host: "192.168.1.22:8080", referrer: "http://192.168.1.22:8080/"
frontend_1       | 2018/12/23 00:22:59 [error] 7#7: *3 connect() failed (111: Connection refused)while connecting to upstream, client: 192.168.1.9, server: , request: "GET /api/tag-categories HTTP/1.1", upstream: "http://[externalip]:6666/tag-categories", host: "192.168.1.22:8080", referrer: "http://192.168.1.22:8080/"
frontend_1       | 192.168.1.9 -> GET /api/info HTTP/1.1 [502] - referer: http://192.168.1.22:8080/ -
frontend_1       | 192.168.1.9 -> GET /api/tag-categories HTTP/1.1 [502] - referer: http://192.168.1.22:8080/ -
frontend_1       | 2018/12/23 00:22:59 [error] 7#7: *2 connect() failed (111: Connection refused)while connecting to upstream, client: 192.168.1.9, server: , request: "GET /api/info HTTP/1.1", upstream: "http://[externalip]:6666/info", host: "192.168.1.22:8080", referrer: "http://192.168.1.22:8080/"
frontend_1       | 192.168.1.9 -> GET /api/info HTTP/1.1 [502] - referer: http://192.168.1.22:8080/ -
```

As you can see how I censored, it seems to be trying to connect upstream with some external ip (which isn't mine, as I've checked, ) and failing. I'm not sure what's causing this error? It displays the same error on the client side as well "Could not fetch basic configuration from server."

**Comment by sgsunder** [comment]
It's probably the IP address of the Docker container containing the Python REST application (`backend`). Usually in the range 172.*.*.*

Docker containers function kinda-but-not-really like virtual machines linked through a virtual network. So you have one container that runs NGINX which serves the static web content and is accessible from the outside via the exposed port 8080. 

The NGINX container also proxies API calls made from the web browser to the REST application container. So when your browser makes a `GET` on the URI `/api/info` NGINX will proxy that as a call to `http://[IP address of REST container]:6666/info`. If this works, you should get a `HTTP 200` response with the JSON that you requested from the REST application. However, you are getting a `HTTP 502` response, which indicates that the REST API has crashed or is not functioning properly for some reason.

I'm not sure why it's crashed, but hopefully that would help you troubleshoot.

**Comment by WychWitch** [comment]
Oh! That makes so much sense! Thank you so much for the explanation, that's exactly what it was.

I found a raspberrypi specific NGINX docker image [here](https://hub.docker.com/r/tobi312/rpi-nginx/) which might fix my problems, but I'm not sure. I'll rebuild everything again after I add it to the Dockerfile and update if it makes any difference.

But before that, here is my full log when launching the server, specifically the backend exits with code 1 which I'm not sure is supposed to happen or not

<details>
<summary>
running without connecting
</summary>
<p>

```bash
$ docker-compose up
Starting szuru_sql_1           ... done
Starting szuru_elasticsearch_1 ... done
Starting szuru_backend_1       ... done
Starting szuru_frontend_1      ... done
Attaching to szuru_elasticsearch_1, szuru_sql_1, szuru_backend_1, szuru_frontend_1
elasticsearch_1  | [2018-12-24 17:01:09,073][WARN ][bootstrap                ] jvm uses the client vm, make sure to run `java` with the server vm for best performance by adding `-server` to the command line
sql_1            | 2018-12-24 17:00:41.252 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
sql_1            | 2018-12-24 17:00:41.253 UTC [1] LOG:  listening on IPv6 address "::", port 5432
sql_1            | 2018-12-24 17:00:41.399 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
sql_1            | 2018-12-24 17:00:41.964 UTC [17] LOG:  database system was shut down at 2018-12-24 16:57:58 UTC
sql_1            | 2018-12-24 17:00:42.087 UTC [1] LOG:  database system is ready to accept connections
elasticsearch_1  | [2018-12-24 17:01:14,681][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
elasticsearch_1  | [2018-12-24 17:01:26,114][INFO ][node                     ] [James Jaspers] version[2.4.0-SNAPSHOT], pid[1], build[b00c0b0/2016-09-12T16:19:49Z]
elasticsearch_1  | [2018-12-24 17:01:26,121][INFO ][node                     ] [James Jaspers] initializing ...
elasticsearch_1  | [2018-12-24 17:01:46,296][INFO ][plugins                  ] [James Jaspers] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
elasticsearch_1  | [2018-12-24 17:01:46,871][INFO ][env                      ] [James Jaspers] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/root)]], net usable_space [45.2gb], net total_space [56.1gb], spins? [possibly], types [ext4]
elasticsearch_1  | [2018-12-24 17:01:46,878][INFO ][env                      ] [James Jaspers] heap size [510.5mb], compressed ordinary object pointers [unknown]
elasticsearch_1  | [2018-12-24 17:02:32,465][INFO ][node                     ] [James Jaspers] initialized
elasticsearch_1  | [2018-12-24 17:02:32,472][INFO ][node                     ] [James Jaspers] starting ...
elasticsearch_1  | [2018-12-24 17:02:33,861][INFO ][transport                ] [James Jaspers] publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2018-12-24 17:02:33,962][INFO ][discovery                ] [James Jaspers] elasticsearch/6PxkhVhbQsOfG4JM3BDprg
elasticsearch_1  | [2018-12-24 17:02:38,055][INFO ][cluster.service          ] [James Jaspers] new_master {James Jaspers}{6PxkhVhbQsOfG4JM3BDprg}{172.18.0.2}{172.18.0.2:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
elasticsearch_1  | [2018-12-24 17:02:38,334][INFO ][http                     ] [James Jaspers] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2018-12-24 17:02:38,351][INFO ][node                     ] [James Jaspers] started
elasticsearch_1  | [2018-12-24 17:02:38,876][INFO ][gateway                  ] [James Jaspers] recovered [0] indices into cluster_state
szuru_backend_1 exited with code 1
```
</details>

<details>
<summary>
The <i>uncensored</i> error when trying to connect (only appears if the attempt to connect is before when the backend exits.)
</summary>

```bash
frontend_1       | 192.168.1.9 -> GET / HTTP/1.1 [200] - referer: - -
frontend_1       | 2018/12/24 17:10:47 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.9, server: , request: "GET /api/info HTTP/1.1", upstream: "http://172.18.0.4:6666/info", host: "192.168.1.22:8080", referrer: "http://192.168.1.22:8080/"
frontend_1       | 192.168.1.9 -> GET /api/info HTTP/1.1 [502] - referer: http://192.168.1.22:8080/ -
frontend_1       | 192.168.1.9 -> GET /api/tag-categories HTTP/1.1 [502] - referer: http://192.168.1.22:8080/ -
frontend_1       | 2018/12/24 17:10:47 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.9, server: , request: "GET /api/tag-categories HTTP/1.1", upstream: "http://172.18.0.4:6666/tag-categories", host: "192.168.1.22:8080", referrer: "http://192.168.1.22:8080/"
frontend_1       | 2018/12/24 17:10:47 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.9, server: , request: "GET /api/info HTTP/1.1", upstream: "http://172.18.0.4:6666/info", host: "192.168.1.22:8080", referrer: "http://192.168.1.22:8080/"
frontend_1       | 192.168.1.9 -> GET /api/info HTTP/1.1 [502] - referer: http://192.168.1.22:8080/ -
```
</details>

**Comment by sgsunder** [comment]
`docker-compose build backend` will only rebuild the backend, for example.

The backend container is not supposed to exit. But it seems like the backend isn't outputting a stacktrace or any error messages either, which makes this difficult to debug.

**Comment by WychWitch** [comment]
Ah okay thank you! And yeah I thought that was weird... The last thing I'll do is make sure that all of the apt-get and pip packages  are correct for my architecture in the backend.

If that doesn't work, I'm not sure what else to do. Still, thanks for all your help so far! I'll update once I have another crack at it.

**Comment by rr-** [comment]
> (Also had to downgrade python to 3.5 rather than 3.6 for it to work correctly).

Well, that's why you're seeing `SyntaxError`.

**Comment by WychWitch** [comment]
Yeahhh that's what I figured. I set it back to 3.6 right after but unfortunately now I'm outta ideas...

**Comment by sgsunder** [comment]
Closing for now. Please open a new issue if you or anyone else is having problems with installation.
