### ISSUE TITLE
Permission error during Docker installation

### ISSUE THREAD

**Issue by w1kl4s** [rr-/szurubooru#214]
Build goes throu just fine, but whenever i try to start the application with `docker-compose up -d` i get permission error: 
```
➜  szuru git:(master) docker-compose up -d
Starting szuru_elasticsearch_1 ... 
Starting szuru_sql_1           ... error
Starting szuru_elasticsearch_1 ... done
ERROR: for szuru_sql_1  Cannot start service sql: b"error while creating mount source path '/var/local/szurubooru/sql': mkdir /var/local/szurubooru: read-only file system"

ERROR: for sql  Cannot start service sql: b"error while creating mount source path '/var/local/szurubooru/sql': mkdir /var/local/szurubooru: read-only file system"
ERROR: Encountered errors while bringing up the project.
➜  szuru git:(master) 
```
I don't really have experience with docker, so i have no idea if it means my machine, docker container, or whatever is actually there.

**Comment by TiredSysOp** [comment]
dirty fix to get it running

chmod -R 777 /var/local/szurubooru

**Comment by w1kl4s** [comment]
Isn't that location in Docker container? That location does not exist on my server, i tried creating it and doing exactly that but with no luck.

**Comment by TiredSysOp** [comment]
It's a mount point, it should be an area on your disk which is not containerised. Bare with, I'll fire up my vm and see what I did.

**Comment by TiredSysOp** [comment]
Running as root or a normal user? Did you follow the current install instructions?

**Comment by w1kl4s** [comment]
I followed the instructions, first as normal user then tried redoing it with sudo.

**Comment by TiredSysOp** [comment]
Can you confirm the permissions for the offending folder

**Comment by w1kl4s** [comment]
Good old dirty 777, as said before

**Comment by TiredSysOp** [comment]
I've recorded the whole thing too, I think there may have been an error in the installation steps at your end as I got mine to start up, but then had to sort out the inability to upload at the end. I'll stick a video up here when it's sorted and you can see if anything jumps out at you.

**Comment by TiredSysOp** [comment]
Don't take it the wrong way. It's just worked for me.

https://youtu.be/dbcJrXLYI3I

If there's anything incriminating just ignore it

**Comment by w1kl4s** [comment]
Seems i managed to get it working by nuking all docker containers and redoing with sudo.
