### ISSUE TITLE
Feature request: Bulk upload via URL list

### ISSUE THREAD

**Issue by TiredSysOp** [rr-/szurubooru#219]
Feature request for bulk uploading media by form of URL lists

Bulk uploads are possible if media is sourced locally however not so if multiple URLs are presented, each URL having to be entered manually.

**Comment by AkgunFatih** [comment]
i have done it
#228

**Comment by TiredSysOp** [comment]
Get in mate, you massive legend!

**Comment by sgsunder** [comment]
Closing. Make further discussions on the PR #228
