### ISSUE TITLE
BUG REPORT: Video upload failure

### ISSUE THREAD

**Issue by TiredSysOp** [rr-/szurubooru#225]
Extract from the log, same error regardless of direct connection or through reverse proxy.
https://pastebin.com/gfQNz6Ti Sorry I couldn't grab a more detailed log

Content appears to download to the server, but falters when waitress tries to identify whether it has audio or not and sends out a error message to the frontend as "Internal Server Error"

The offending clips [WARNING CONTAINS RICARDO] : https://cdn.discordapp.com/attachments/520949261676838932/543755507375144971/good_joe_open_your_eyes_2.webm
and
https://cdn.discordapp.com/attachments/520949261676838932/543751340262817793/good_joe_open_your_eyes_2.webm
and
https://cdn.discordapp.com/attachments/520949261676838932/543770666114220040/good_joe_open_your_eyes_4.webm

Live site @ https://ricardo.tgtl.fun/ [MORE RICARDO]

**Comment by sgsunder** [comment]
Looking at what some [other projects have done](https://github.com/slhck/ffmpeg-normalize/blob/bdb312731aa9cb4d968df9c128141073cfeca6a2/ffmpeg_normalize/_streams.py#L88-L93) in scripting volumedetect in python, it seems that they add the flags `-vn -sn` (which ignore any video or subtitle streams). Indeed, this seems to fix OP's error, but I'm not exactly sure why.

The scripting implementation (both in this project and the one I linked) to parse volumedetect is very hacky TBH. It would be nice if you could ingest it as JSON like how ffprobe does it but volumedetect only ouputs it's info to the conversion logs of a ffmpeg command. So you end up having to capture those logs and run a regex on them to get the useful data, and this seems to be giving problems for some users.

If anyone knows of a more robust way of implementing this function, that would help a lot. If not, I'll make a PR for this fix:

```diff
--- a/server/szurubooru/func/images.py
+++ b/server/szurubooru/func/images.py
@@ -157,6 +157,7 @@ class Image:
             '-i', '{path}',
             '-af', 'volumedetect',
             '-max_muxing_queue_size', '99999',
+            '-vn', '-sn',
             '-f', 'null',
             '-y', '/dev/null',
         ], get_logs=True).decode('utf-8', errors='replace')
```
