### ISSUE TITLE
how to edit client and or server files when dockered ?

### ISSUE THREAD

**Issue by AkgunFatih** [rr-/szurubooru#227]
So after reading install.md how do we edit the files instead of ssh to docker ?
i would like to customize it to suit my needs

**Comment by TiredSysOp** [comment]
There's too many variables in your question. Use ftp or sftp to edit config files. Nano should be enough to do light work of it anyway.

What is the server environment, would you like the front and backend on different machines? What customisations are you looking to make

**Comment by sgsunder** [comment]
Unless I'm completely misreading this question...

Fork the repo, make whatever changes you want to the source code, then re-run `docker-compose build` and `docker-compose up -d` to run with your new changes. You shouldn't be changing application files inside the docker container once it's built. They will not persist on restart.

**Comment by AkgunFatih** [comment]
> Unless I'm completely misreading this question...
> 
> Fork the repo, make whatever changes you want to the source code, then re-run `docker-compose build` and `docker-compose up -d` to run with your new changes. You shouldn't be changing application files inside the docker container once it's built. They will not persist on restart.

Thank you, this is what i was looking for

**Comment by Hunternif** [comment]
Looks like I also need to revert this commit if I want to rebuild the server with my changes: https://github.com/rr-/szurubooru/commit/91f5a4245941ee460580f92bd73fe5e81b6bcfac
