### ISSUE TITLE
Recovering passwords for accounts without email?

### ISSUE THREAD

**Issue by dryshirt** [rr-/szurubooru#229]
Hi,

I've got a local installation of szuru running, using Docker. I was just wondering if there is any way to recover lost passwords for an account with no e-mail configured? The issue came up after I set up an administrator account which I promptly forgot the password to; there isn't any data I'm afraid of losing but I'm still curious. (Not sure if an issue is the best way to frame this question but there isn't another forum to ask questions on)

**Comment by rr-** [comment]
Try going to the db and setting `password_hash` of your admin account to `SHA1("1A2/$_4xVa" + "derp" + "NEW PASSWORD")` and its `password_salt` to `derp`. You should now be able to log in with `NEW PASSWORD`.
