### ISSUE TITLE
Minor client bug: when setting color for category, uppercase letters lead to "invalid color"

### ISSUE THREAD

**Issue by Hunternif** [rr-/szurubooru#239]
E.g. #4aaee9 is valid, but #4AAEE9 is not. Both should be valid.

**Comment by ReAnzu** [comment]
How about instead of allowing both representations, we simply force the user input on the tag categories page to be lowercased?

ReAnzu/szurubooru@3ff6bc0f8afdef68d86a96bac1afcb9d5e54919d
