### ISSUE TITLE
Bug: clicking on tag with ':' doesn't escape character in query

### ISSUE THREAD

**Issue by Hunternif** [rr-/szurubooru#240]
E.g. I have a tag "artist:craig_mullins". When I click the link to this tag on a post page, or when I click "usages" on the tag description page, it lands me on a query `/posts/query=artist%3Acraig_mullins`, where the ':' character is not escaped, and leads to the `Unknown named token` error.

**Comment by rr-** [comment]
Fixed in https://github.com/rr-/szurubooru/commit/93910a1655f0f536d8927415935ab316bcad376f
