### ISSUE TITLE
Can't create tag categories

### ISSUE THREAD

**Issue by SamusAranX** [rr-/szurubooru#241]
Is there really no way to create tag categories in the Web interface?

I can't even get past the authentication part of the API, so that's a no-go for me.

**Comment by rr-** [comment]
There is.

**Comment by rr-** [comment]
![20190407_180741_itm](https://user-images.githubusercontent.com/1045476/55686329-2391c900-5960-11e9-8614-a9db132771bb.png)

→

![20190407_180751_qdn](https://user-images.githubusercontent.com/1045476/55686330-27255000-5960-11e9-8182-41ade0490a61.png)

**Comment by SamusAranX** [comment]
Welp, that was a major failure on my part. Apologies.
