### ISSUE TITLE
Unknown error (delete_by_query() got an unexpected keyword argument ‘doc_type’).

### ISSUE THREAD

**Issue by warsix4** [rr-/szurubooru#248]
I am unable to upload any type of file to my szurubooru installation. The error I receive is as in the title: 

`Unknown error (delete_by_query() got an unexpected keyword argument ‘doc_type’).`

Any suggestions? Thanks!

**Comment by warsix4** [comment]
After further testing, this only happens with `.jpg` and `.png` files.

**Comment by Hunternif** [comment]
I encountered the same error when running unit test `test_image_hash.py`

**Comment by Hunternif** [comment]
I'm guessing this is because of an incompatible version of the `elasticsearch` library. @warsix4 did you install szurubooru with Docker?

**Comment by warsix4** [comment]
Yes I did. Is there any specific logs or info I can provide?
___


Cody Warmbo
warmbo.com

**Comment by Hunternif** [comment]
I'm speculating as I'm not super familiar with these technologies, but perhaps you could try and install again on a clean system and share the output fom these steps:
```
docker-compose pull
docker-compose build --pull
```

**Comment by warsix4** [comment]
I'd like to resort from recreating a VM but will do so in a few hours I guess if I can't find any solutions or at least causes.

**Comment by warsix4** [comment]
I spun up a new Ubuntu Server 18.04 instance and installed docker/docker-compose. During the 

`docker-compose build --pull` command I get the error:   
'elasticsearch-dsl 6.3.1 has requirement elasticsearch<7.0.0,>=6.0.0, but you'll have elasticsearch 7.0.0 which is incompatible.'

This time after installation I also am unable to actually start the sql container... /var/local/szurubooru does not seem to exist.

**Comment by warsix4** [comment]
Now after ANOTHER attempt I am facing this issue

```
urubooru/sql': mkdir /var/local/szurubooru: read-only file system"

ERROR: for sql  Cannot start service sql: b"error while creating mount source path '/var/local/szurubooru/sql': mkdir /var/local/szurubooru: read-only file system"
```
I have chmod'd the directory, and run everything as sudo, but no go. :( 

I really wish the documentation was more specific or suggested a distro to use.

**Comment by warsix4** [comment]
I have spun up a Debian9 VM instead of Ubuntu this time and now face the exact same error as in the post title again.

**Comment by Hunternif** [comment]
As I understand it, the current setup process fetches the latest version of every dependency (Docker image?) Elasticsearch 7.0 came out just 5 days ago: https://www.elastic.co/blog/elasticsearch-7-0-0-released, so maybe it changed its API (removed argument 'doc_type'), and I haven't experienced issues because my server was set up before this release. I guess it should be possible to update `docker-compose.yaml` and set a specific version of elasticsearch there.

**Comment by Hunternif** [comment]
I stand corrected: it was not in docker-compose, but in API requirements. You can use my branch until it's merged.

**Comment by warsix4** [comment]
Thanks so much! I modified the `requirements.txt` to specify the ElasticSearch version and when I ran `docker-compose build` again everything put itself into place and I can upload all supported filetypes again!
