### ISSUE TITLE
sqlite3 error in unit tests

### ISSUE THREAD

**Issue by Hunternif** [rr-/szurubooru#250]
Apologies if my issue is a result of blatant misuse of programs.
In my attempt to run unit tests for the server, I followed the manual in `INSTALL-OLD.md`. Initial running `pytest` caused half of the tests to fail, and as I stepped through the first one, I encountered this error:
```
sqlite3.InterfaceError: Error binding parameter 6 - probably unsupported type
```
Which seemed to be pointing to the parameter `flags` with a value of `[]`.
I managed to fix it and get only 5 tests to fail by changing a value in `config.yaml`:
```
test_database: postgresql://szuru:dog@localhost:5432/szuru_test
```
~This suggests that perhaps the default settings in the configs are not working as intended?
Or maybe my installation on Ubuntu uses some incompatible package versions.~

**Comment by Hunternif** [comment]
I think this is caused by `post.flags` represented as array in the application, but string in the database.

**Comment by sgsunder** [comment]
Seems related to #252, then? I think that I should rewrite the Post model then in `model/post.py`. Right now the translation between the string type stored in the database and the array type that's used by response/requests is happening later on in the translation layer, but this possible can happen directly in the Post model itself.
