### ISSUE TITLE
[Suggestion] Stats page

### ISSUE THREAD

**Issue by warsix4** [rr-/szurubooru#253]
After getting my szurubooru instance setup properly, I'm now wondering how I can find metrics about the site. e.g., How many posts, how many safe, sketchy, unsafe, size of content on disk. A stats page sounds useful to me.

**Comment by sgsunder** [comment]
For number of total posts and storage usage, the API [already provides this](https://github.com/rr-/szurubooru/blob/master/API.md#getting-global-info) and it's displayed on the bottom of the home page:

![image](https://user-images.githubusercontent.com/16943235/56246133-1d41d200-606f-11e9-94bb-631a02433a60.png)
