### ISSUE TITLE
Fix pyyaml loader deprecation warning

### ISSUE THREAD

**Issue by sgsunder** [rr-/szurubooru#254]
Logger spits out the following warning when loading the config files:

`/opt/app/szurubooru/config.py:50: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.`

I'll try and look into this when I get the chance (hopefully this weekend) but if someone else wants to tackle this in the meantime, feel free. I can't imagine this being a terribly difficult fix.

**Comment by noirscape** [comment]
I'd like to note that you can also use `yaml.safe_load()` instead of this
method.
