### ISSUE TITLE
Easiest/Best way to backup szurubooru?

### ISSUE THREAD

**Issue by WychWitch** [rr-/szurubooru#255]
Hello! After using the booru for about 4 months I realized I need to be able to back it up in case anything goes wrong. While I could make a clone of the SD card it's running off of (rpi3), I can't imagine that's the most optimal way.

Has anyone else been backing up their boorus? How? Thank you do much in advance, and I'm sorry if this question is too off topic

**Comment by noirscape** [comment]
Backup the folders from your mounts if you're using docker as well as your `.env` file.

That's all there is to it.

Restoring is then just a case of replacing your `.env` file with the one from your backup and pointing the mounts to your restored backup.

**Comment by sgsunder** [comment]
1) **Image files**. Back this folder up using whatever normal methods that you wish. If you are using the provided docker-compose file, then it should be located where you set `$MOUNT_DATA` in the .env file.

2) **Database**. You can either back up the folder set to `$MOUNT_SQL` or use any other methods available for backing up a PostgreSQL database.

The Elasticsearch Index *does not* need to be backed up, as it can be regenerated on server start-up.

**Comment by WychWitch** [comment]
Thank you so much! That was indeed *much* faster and smaller than resorting to copying the entire drive!
