### ISSUE TITLE
Unhandled file type: ‘application/octet-stream’

### ISSUE THREAD

**Issue by warsix4** [rr-/szurubooru#257]
When uploading .jpg files I encounter this error. Any solution?

**Comment by sgsunder** [comment]
Can you post an example file which gives this error?

**Comment by warsix4** [comment]
**NSFW**: https://imgur.com/a/eh4MGX2

It's not just this file though, it's the majority of .jpg files I've tried to upload. Others have indicated the same error happening to them for my server as well.

**Comment by sgsunder** [comment]
Unfortunately, I can't seem to reproduce this error on my end. Your file uploads just fine on my test server.

Possible troubleshooting steps: 
- Did you check that you were on the latest commit?
- Is there a proxy being used to send the requests out to the server?
- If you are downloading the file through inputting the URL, can you post what User-Agent string you are using in the `config.yaml` file?

The server detects the mime type of the file in this function (https://github.com/rr-/szurubooru/blob/master/server/szurubooru/func/mime.py) if that helps with your troubleshooting

**Comment by warsix4** [comment]
I'm a few behind, I am using Caddy but with the `transparent` function in place for the proxy. This is a direct upload I am attempting, I will attempt uploading it via URL now though!

**Comment by warsix4** [comment]
So after uploading the image to Imgur and then downloading it again, I have a copy that is able to be uploaded? I'm not sure what that could've changed.

I'm just going to assume there is some issue with my files.

**Comment by sgsunder** [comment]
Closing for now as it doesn't seem to be an issue with szurubooru. You can open a new issue if you feel that there's a bug.

**Comment by neobooru** [comment]
For future reference, I got this exact same error when I queued the file for upload (when you can select safe, sketchy, etc) -> renamed the file on pc (or moved/deleted) -> click upload (to actually start uploading the file).

**Comment by MilkyPL** [comment]
I had a similar issue with an MP4 file. I checked it in a hex editor and it had `ftypM4V` at the beginning of the file. After changing it to `ftypmp42` (as seen in https://github.com/rr-/szurubooru/blob/master/server/szurubooru/func/mime.py) the upload worked. I suppose someone should add support for those files in the function.
