### ISSUE TITLE
Default tag on upload

### ISSUE THREAD

**Issue by Metal-Mighty** [rr-/szurubooru#259]
Gelbooru, and maybe other *booru boards, add a default "tagme" tag to uploads when no tag is specified at first.
Since, according to other issues, tagging on upload doesn't seem to be coming soon to szurubooru, could it be possible to add the option to add a default tag on new posts, so that untagged posts can be found easily later on?

**Comment by noirscape** [comment]
Just search for `tag-count:0`.
