### ISSUE TITLE
Bug: Clicking "Mass tag -> Start" or "Mass edit safety" resets current page number

### ISSUE THREAD

**Issue by neobooru** [rr-/szurubooru#274]
Go to any page other than the first page -> start any of the mass edit actions -> page number resets to 1, so now you have to navigate back to where you wanted to mass edit.

Just adding it here for completeness. I'll probably fix this myself sometime, but I can't self assign.

**Comment by sgsunder** [comment]
Fixed in commit eb49aea and PR #286
