### ISSUE TITLE
Feature request: Enable CORS for /api/* endpoints

### ISSUE THREAD

**Issue by neobooru** [rr-/szurubooru#275]
When calling the API from within a browser (e.g. from a WebExtension with XMLHttpRequest) you are subject to Cross-Origin Resource Sharing (CORS). This means that the web server needs to send some special headers otherwise the browser will deny the request.
More specifically the following is needed:

All api endpoints have to send the following headers
```
Access-Control-Allow-Origin "*"
```

Furthermore the server has to respond to the OPTIONS request with the following headers
```
Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers "Authorization, Content-Type"
```

For my setup I've got this covered with some [apache2 settings](https://github.com/neobooru/SzuruChrome#I-cant-connect-to-a-szurubooru-instance-because-it-complains-about-CORS), but maybe we want to do this correctly in the server code?

[Basic safe CORS protocol setup](https://fetch.spec.whatwg.org/#basic-safe-cors-protocol-setup)
[Preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)

_The values used above are speculation and only based on my apache2 config, so no real testing._

**Comment by sgsunder** [comment]
69922fc should enable CORS for docker users who are accessing the API through the client/nginx container (the 'default' installation). Let me know if that doesn't work.

**Comment by 59716123** [comment]
@sgsunder 
Doesn't seem to work.  

Quick test with fetch from another domain:

```
fetch("http://example.com/api/posts/?limit=10&fields=id%2CthumbnailUrl", {
  "headers": {
    "accept": "application/json",
    "authorization": "Token myBase64Token",
    "content-type": "application/json"
  },
  "body": null,
  "method": "GET",
  "mode": "cors"
}).then(a => a.json()).then(a => console.log(a));
```


comes with an error message

> Access to fetch at 'http://example.com/api/posts/?limit=1&fields=id%2CthumbnailUrl' from origin 'http://anotherdomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.


It seems to be working when I edit the nginx.conf.docker as follows:
```
        [...]
        location ~ ^/api/(.*)$ {
            tcp_nodelay on;

            add_header 'Access-Control-Allow-Origin' '*';
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
                add_header 'Access-Control-Allow-Headers' 'Origin,Content-Type,Accept,Authorization';
                add_header Content-Length 0;
                add_header Content-Type text/plain;
                return 200;
            }
            [...]
```
Seems like add_header has to be called again in the if-clause, I also added 'Origin' and 'Accept' to the allowed headers.
