### ISSUE TITLE
Help with base_url

### ISSUE THREAD

**Issue by SirFireNewt** [rr-/szurubooru#277]
I feel bad for having to ask this, since I did have it working at one point, but I managed to lose the folder with git repository and can't figure out how to set it up again
Install.md says  
> "simply set `BASE_URL="/szuru/"` in the frontend container" 

Unfortunately it doesn't say *where* or *how* to set that, I have it in my .env file but that doesn't seem to change anything, I added `BASE_URL: /szuru/` to my docker-compose.yml, that took the response  from  `/img/favicon.png` to `/szuru/img/favicon.png` but the server returned favicon.png as the same html as the base url, and any css or js file is 0 bytes, adding the same line under api doesn't change anything.

All the above is true through a direct connection or through my nginx proxy.  
However on direct connect without the docker-compose.yml edit the site loads fine but images in posts or thumbnails do not load.

Any help would be appreciated

**Comment by sgsunder** [comment]
Pushed a commit that should help simplify this a bit.

If you are using the provided docker compose setup: You need to change the value of `BASE_URL` in your `.env` file. (As a reminder, `.env` should be copied over from `example.env` and should be in the same directory as `docker-compose.yml`)

You also _need_ to have a reverse proxy. For example, let's say you are using `BASE_URL="/szuru/"` and `PORT=7777` in your `.env` file, and that you are running your reverse proxy application on the same machine as your docker containers. 

Then, your reverse proxy needs to be configured such that: `http(s)://example.com/szuru/` points to `http://localhost:7777/`

**Comment by SirFireNewt** [comment]
I managed to get it to work, apparently at some point I removed the trailing / in my nginx config, I had a feeling it would be a dumb mistake....  

I have one last issue, as I said earlier I did have it working at some point previously, currently all my post & thumbnail ids appear to mismatch the actual files, is it possible to fix that easily or would I need to edit the image names by hand?  
ex: real image is `9_ec0b0f3dfd5d5ad5.jpg` but server links `9_f3515469ac729272.jpg`

**Comment by sgsunder** [comment]
The file names will change if you change the value for `secret` stored in `config.yaml` so if you are able to change it back to what it was then you will restore your old file names. If not, then you probably have to write a script to change the values of it manually.

**Comment by SirFireNewt** [comment]
That was my suspicion, thank you for the help!
