### ISSUE TITLE
Official Docker Hub Images

### ISSUE THREAD

**Issue by sgsunder** [rr-/szurubooru#281]
@rr- Any thoughts on opening up a Docker Hub account so that users would have the option to pull the images from an 'official' repository instead of having to build it themselves?

I also wrote up a build hook for the server-side portion of the code so that the unit tests can be automatically run for any pull-requests as well.

**Comment by rr-** [comment]
Hmm, I've never used docker hub before. Is it a free service?

**Comment by noirscape** [comment]
DockerHub is free for public repositories.

The main advantage is that it can automatically build containers on each commit (this is also what gives users faster build times, since they can pull these build containers) if you set it up to do so.

The disadvantage is that a build can sometimes take up to 6 hours to be ran after it is queued (it's a free service so there's a lot of builds going on).

**Comment by noirscape** [comment]
Also, this probably wouldn't work without making `server/config.yaml` a mountpoint, since as it stands it is copied into a build container.

**Comment by sgsunder** [comment]
> Hmm, I've never used docker hub before. Is it a free service? 

Yes, free for public repos.

> Other than faster build times, are there other benefits of this?

- Users can get updates directly through docker or it's various frontends, instead of having to run a separate `git pull` command
- Even better, users wouldn't even need to clone the repo to run this, they would only need to copy `docker-compose.yml` (or write their own that's tailored to their use case) and supply a `config.yaml` file
- I've added hooks to neatly tag these images, and automatically set the build info on the homepage (See `client/hooks/` and `server/hooks/`)
- I've added a hook to automatically run the server-side unit tests after the image is built.
    - Can also be configured to build and test any incoming PRs, which would give Travis/Jenkins-like functionality

> Also, this probably wouldn't work without making server/config.yaml a mountpoint, since as it stands it is copied into a build container.

The config file gets excluded from the build via `server/.dockerignore`. Users should already be mounting their config file like this right now, see [here](https://github.com/rr-/szurubooru/blob/c9eae00c8c91ffbebb63e694cbc6af21f78afc9a/docker-compose.yml#L34).

**Comment by sgsunder** [comment]
@rr-, My suggestion would be to:
- Open a Docker Hub account and link your Github account to it
- Make a Docker Hub repository called: **szurubooru-client**, and set up an automated build like this:
![image](https://user-images.githubusercontent.com/16943235/65880240-75d80380-e35f-11e9-9d63-31cafad22376.png) then hit 'Save & Build'
- Make another Docker Hub repository called **szurubooru-server** and set it up the same way, except change the build context from `/client/` to `/server/`

That should set it up to automatically build on every commit pushed, as well as test build any PRs

**Comment by rr-** [comment]
I see. I agree it definitely would be useful. @sgsunder thanks for the instructions; I added two repositories in DockerHub called `rrdash/szurubooru-client` and `rrdash/szurubooru-server`. I've set them up like explained. Do I need to set up anything else?

**Comment by sgsunder** [comment]
Hmm, did you hit 'Save and Build' or just 'Save'? I see the repositories but there are no completed builds within it. Might have to click to 'Builds' > 'Trigger' on both repositories to start it up for the first time.

**Comment by rr-** [comment]
@sgsunder scheduled a build. I would like to add you to the collaborators, if you'd like that please let me know your Docker ID.

**Comment by sgsunder** [comment]
My profile page is https://hub.docker.com/u/sgsunder so I'm guessing that my ID would be `/u/sgsunder` (unless it's asking for a numeric ID)
