### ISSUE TITLE
Feature Request: Right-Click to Save-As for posts

### ISSUE THREAD

**Issue by Pathos14489** [rr-/szurubooru#289]
Currently, you cannot save images from the Booru without a long, tedious process. I feel that this is detrimental to the usage of a booru, if the users of it cannot download from it. Either a download button, or the context menu returning would be appreciated greatly.

**Comment by sgsunder** [comment]
This link that I've circled is a direct hotlink to each post's image. You should be able to Right Click -> "Save Link As..." on it.

![image](https://user-images.githubusercontent.com/16943235/68079359-b394d580-fdbe-11e9-8568-56fac73e5a5d.png)

**Comment by sgsunder** [comment]
Closing, please re-open if the fix listed does not work for you.

**Comment by viasux** [comment]
> Closing, please re-open if the fix listed does not work for you.

I'd appreciate if you could still right click > save image as, as it's a lot easier and more accessible! :)

**Comment by po5** [comment]
@Pathos14489 @viasux This can be solved with one line of CSS https://github.com/po5/szurubooru/commit/288d1851cd058641a6faa77cf6cea79b618cc1a2, lets you right click anywhere a note isn't present.
