### ISSUE TITLE
Link GitHub to Docker Account

### ISSUE THREAD

**Issue by sgsunder** [rr-/szurubooru#294]
@rr- I set up an organization account for szurubooru on Docker Hub and added you as an admin. Would you be able to link this repository to it?

https://hub.docker.com/orgs/szurubooru

**Comment by rr-** [comment]
@sgsunder apparently you can only have one account linked at a time, can you unlink your account first? I seem to be unable to do it.

Also, thanks for the invitation.

**Comment by sgsunder** [comment]
@rr- Hmm, the disconnect button doesn't seem to work for me. I'll send another email out to Docker support...

**Comment by sgsunder** [comment]
@rr- I think I managed to clear my linked account. Can you see if it works now?

**Comment by rr-** [comment]
@sgsunder sorry for the delay. I linked my account. Would you like me to do anything more?

**Comment by sgsunder** [comment]
@rr- Okay, everything should be set up on the organization account now.

I would recommend that you delete the repos under 'rrdash' so that users don't keep inadvertently using them.

**Comment by rr-** [comment]
Done, thanks
