### ISSUE TITLE
Feature request: ios inline playback

### ISSUE THREAD

**Issue by TiredSysOp** [rr-/szurubooru#295]
Feature request: ios inline playback

Done through use of the "inline" attribute, possible modifier on the settings page

https://stackoverflow.com/questions/41512200/how-do-some-websites-play-video-inline-in-ios-safari

**Comment by sgsunder** [comment]
I'm (probably) willing to add this in but I'm confused as to what this does, as I don't have any iOS device to test on. Does iOS force all HTML5 videos to play fullscreen unless it has this modifier in the `<video>` tag?

**Comment by TiredSysOp** [comment]
From what I'm aware of, all browsers on IOS have to use webkit to be able to be on the appstore, all webkit browsers force fullscreen video unless the inline attribute in the video tag. It's the latest way to do it as the other methods were for older versions of IOS. Apple added support for "inline" in ios 10.

For some reason I remembered the attribute as being "inline" but it looks like it's "playsinline" instead

<video playsinline>
  <source src="video.mp4">
</video>

**Comment by neobooru** [comment]
I could take a look at it, currently all `type:video` content opens a full screen window (so no inline play). `type:animated` plays inline, which is what you also want videos to do? Apple also forces all developers to use the same (built-in) WebKit engine, so if it works in Safari it should also work on all other browser.

**Comment by sgsunder** [comment]
Ok, this should be implemented in the latest build on Docker Hub now. No checkbox option needed to activate. Let me know if you have any issues.
