### ISSUE TITLE
Improve the Help/About/Wiki to Explain More Specifically the Details of the Project

### ISSUE THREAD

**Issue by da3dsoul** [rr-/szurubooru#297]
The biggest issue I see with basically every tag based system is that very few people actually know what they are, let alone the specific implementation of the system in a given project.

What I want to do:
- Keep my current file structure, as it's used in more than just one service. Deduplication is a really cool part of tag-based systems, but it's irrelevant for my needs.
- Provide a searchable backend for tagging and displaying the files.
- Share my files with others, using this nice search system.
- Look nice, duh.

Nextcloud can do all of these things...poorly. No offense to them, but tagging seems to be the least of their worries. I would just help them with my programming expertise, but it's written in PHP and heavily rooted in web-dev ideals.

This continuously drives me toward booru-style systems, which are generally far more aimed to be websites with upload features and social network ideals, maintained by a large community. It's fine if I can just turn those off.

These things are very hard to find information on in every project I've found. Usually, my best bet is just to find the dev and ask. Usually, the answer is "no", but having this information in a clear, readable format can help anyone trying to get into a project.

**Comment by sgsunder** [comment]
I'm not sure I really understand what you're asking for, but hopefully this helps:

> Keep my current file structure, as it's used in more than just one service.
 
Szurubooru would not be able to maintain your file structure or your filenames. It completely forgoes the directory-tree paradigm and only uses tagging for post data organization. The implementation of this is that all images are stored in a flat directory and named purely based on the post ID. The entire tag structure is stored in a SQL database instead. 

> Deduplication is a really cool part of tag-based systems, but it's irrelevant for my needs.

The fuzzy image matching option can be disabled (by setting permission `posts:reverse_search` to `nobody`), however the exact duplicate match (where the SHA checksums are looked for) can not be turned off.

> Provide a searchable backend for tagging and displaying the files.

This is available.

> Share my files with others, using this nice search system.

If you make your Szurubooru instance as public facing, then you can share the link to any post.

> This continuously drives me toward booru-style systems, which are generally far more aimed to be websites with upload features and social network ideals, maintained by a large community. It's fine if I can just turn those off.

- Szurubooru is capable of handling multiple users, yes, but is perfectly functional with just one user. You don't necessarily need a large community to maintain it.
- Szurubooru doesn't really have any "social network" features besides the ability to make comments under posts. Even this can be masked by setting the `comments:view` permission to `nobody`
- Szurubooru is a web application, yes, but there's no need to have it be public-facing. You can easily just run it on your laptop and make your browser point to localhost, or run it on RPi (or similar) and have it only be available on LAN.

**Comment by da3dsoul** [comment]
Thank you. This is the kind of post that I'd like to see on the main page of projects, in general.
I already knew that some of these are supported by szurubooru by its very nature, such as being a web server and sharing files. The other things, like how the back end fits into the workflow for someone looking to move from a large folder of images to a web service, are what I was looking for.
You answered my questions well. You can close this, but personally, I'd leave it open or move the info to another easy to find place, as I imagine other people looking to get started will want to know these things, as well.
In case you weren't aware, at least right now, if you search for self hosting a booru or an image tagging system, it generally give szurubooru as the first actually relevant result.

**Comment by noirscape** [comment]
I should point out that szurubooru does have an extensive API that's pretty easy to use (at least, with Python's `requests`, and if you already have your images sorted by rating, it's somewhat trivial to write an application that uploads the images for you, optionally with extra criteria (ie. you could make your filenames tags or plug it in with external reverse image servers to have it retrieve tags and sources from other boorus).

**Comment by da3dsoul** [comment]
Yeah, if I was to attempt it, I would probably make an edit to upload mechanic to find the file in my filesystem and symlink it
