### ISSUE TITLE
Changing Styles/Images not working

### ISSUE THREAD

**Issue by Andre19926** [rr-/szurubooru#302]
Greetings,
I have the problem that whatever I change in the .styl files doesn't apply/change.
Eg: changing "$window-color = white" to "$window-color = black" in the colors.styl doesn't change the color on the site.

Perhaps I am missing something or doing something fundamentally wrong.

**Comment by sgsunder** [comment]
If you are making source code edits to customize, then you should modify the `docker-compose.yml` file to build your own source instead of using the prebuilt images:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 1da23bd6..ae32c514 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -7,7 +7,8 @@ version: '2'
 services:
 
   server:
-    image: szurubooru/server:latest
+    build:
+      context: ./server
     depends_on:
       - sql
     environment:
@@ -26,7 +27,10 @@ services:
       - "./server/config.yaml:/opt/app/config.yaml"
 
   client:
-    image: szurubooru/client:latest
+    build:
+      context: ./client
+      args:
+        BUILD_INFO: <your string here>
     depends_on:
       - server
     environment:
```

**Comment by Andre19926** [comment]
I have done the above listed changes and it worked.
The only problem right now is, when I want to "update" the style/css It doesn't build the new version.
Tried setting the BUILD_INFO to 1.2, didn't work.

**Comment by sgsunder** [comment]
I'm thinking it's still using the cached version?
Try running `docker-compose build` before `docker-compose up -d` to force it to rebuild.

FYI, the "BUILD_INFO" just sets the information string used on the homepage. It doesn't affect any functionality.

**Comment by Andre19926** [comment]
Thanks, It's working now.
