### ISSUE TITLE
Site Clears on Restart

### ISSUE THREAD

**Issue by princessGasmask** [rr-/szurubooru#314]
Hello! I got this installed and running fine on Windows using Docker. However, when I shut down the server and then restart it, the site resets to being blank, as though nothing is uploaded. However, the actual uploaded files still exist on my drive in the correct pathing that I'd set in the config. I'm not sure how to fix this myself and was looking to see if there was any advice you guys could help with.

**Comment by sgsunder** [comment]
Hmm, are you sure if the SQL database is also being stored in a persistent location and not being wiped on restart?

**Comment by princessGasmask** [comment]
I'm not sure how to check. I don't know where I would check that using Docker.

**Comment by sgsunder** [comment]
You can log in directly to the Postgres database by executing:
```
docker-compose exec -u postgres <postgres container name> psql <postgres schema name>
```
The default container name (as defined in the docker-compose file) is `sql`, and the schema name would typically be the same as the postgres user defined in your `.env` file (default of `szuru`)

From there you can run the command `\d` to see if szurubooru's tables exist, and you can run SQL queries to verify data is present, i.e. `SELECT count(*) FROM post;` should give you the number of posts you created.

If you're tables are empty/nonexistent, then you probably are having some issue with database persistance.

**Comment by dekarrin** [comment]
@princessGasmask for repro, are you running this Docker Desktop for Windows (via Hyper-V), or the legacy way of Docker Toolbox?

Can you share what commands you are using to start your server, as well as what you are using to shut it down? If you are typing shell commands directly, what shell are you using for that?

Additionally, can you confirm the contents of your docker-compose.yml and .env?

**Comment by sgsunder** [comment]
Closing, please re-open if this is still an issue.
