### ISSUE TITLE
Uploading via youtube-dl throws an internal server error

### ISSUE THREAD

**Issue by TiredSysOp** [rr-/szurubooru#315]
Problem with this video https://www.youtube.com/watch?v=Bs3jVWiNJRE
max_dl_filesize: 500.0E+6 is greater than the above videos size. On another note the test video (https://www.youtube.com/watch?v=C0DPdy98e4c) downloads with no problems

server_1  | [2020-04-05 21:47:20] szurubooru.middleware.request_logger POST /uploads (user=admin, queries=1)
server_1  | [2020-04-05 21:47:20] waitress Exception while serving /uploads
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/lib/python3.8/site-packages/waitress/channel.py", line 349, in service
server_1  |     task.service()
server_1  |   File "/usr/lib/python3.8/site-packages/waitress/task.py", line 169, in service
server_1  |     self.execute()
server_1  |   File "/usr/lib/python3.8/site-packages/waitress/task.py", line 439, in execute
server_1  |     app_iter = self.channel.server.application(environ, start_response)
server_1  |   File "/opt/app/szurubooru/rest/app.py", line 99, in application
server_1  |     response = handler(ctx, match.groupdict())
server_1  |   File "/opt/app/szurubooru/api/upload_api.py", line 10, in create_temporary_file
server_1  |     content = ctx.get_file(
server_1  |   File "/opt/app/szurubooru/rest/context.py", line 55, in get_file
server_1  |     return net.download(
server_1  |   File "/opt/app/szurubooru/func/net.py", line 27, in download
server_1  |     return _youtube_dl_wrapper(url)
server_1  |   File "/opt/app/szurubooru/func/net.py", line 50, in _youtube_dl_wrapper
server_1  |     if ydl_info['filesize'] > config.config['max_dl_filesize']:
server_1  | TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by sgsunder** [comment]
I think the last commit that I pushed would have fixed this issue as well. Try re-pulling the container images and reopen if you still have this issue.

**Comment by TiredSysOp** [comment]
I should have clarified, This occurred on build v2.3-edge-cd6683c (latest as of now). I'll do an idiot check to make sure I didn't do anything obvious

**Comment by sgsunder** [comment]
Wow, youtube-dl is pretty annoying to deal with. Once 377fe52 finishes autobuild, test and let me know if it works.

**Comment by TiredSysOp** [comment]
Works brilliantly, fyi it isn't pulling the highest quality available

**Comment by sgsunder** [comment]
> it isn't pulling the highest quality available

I'm assuming you are talking specifically about Youtube, not any other site.

The problem is that youtube serves the high-bitrate content as two separate audio and video streams, and expects the client to mux them together.

In the current way I call youtube-dl, it chooses to instead capture the lower bitrate single MP4 filestream. I'm not sure how I can fix this for youtube without compromising usability with many other sites
