### ISSUE TITLE
Migrating from 2.2-95 to current version

### ISSUE THREAD

**Issue by Lett1** [rr-/szurubooru#316]
Hey there, I'm running an old szurubooru instance on http://gondbooru.lett.at/ and I want to upgrade to the new docker version, my main question is: how do I migrate to the new version?  Can I just point the docker container to the old postgres DB and have it migrate automatically? And if that's not possible, export and reimport all the posts/users and so on?

**Comment by sgsunder** [comment]
Yes. There are alembic migration scripts that are called on startup to migrate the database. I would still highly recommend making a database backup first, given how old the revision you are currently running is.

**Comment by Lett1** [comment]
I take it that this does migrate the data from elasticsearch as well?

**Comment by sgsunder** [comment]
It regenerates the image signature data again. It takes a bit of time and CPU to do, but is done when the site is online. No data is lost (elasticsearch didn't really store any data that couldn't be computed again) so you can safely delete the index even before the migration.

**Comment by Lett1** [comment]
Ok so I'm done, here's what I did:

- Make a dump of the database
- Follow INSTALL.md until you start the containers, at this point _only start_ the sql container
- Restore dump into the sql container
- Continue setup, you might want to upgrade nginx
