### ISSUE TITLE
Mass tag 'add' button is too hard to press, causing reduced tagging speed

### ISSUE THREAD

**Issue by Ruin0x11** [rr-/szurubooru#322]
When mass tagging would it be better if the 'add' button has a larger size, or at least the ability to open a post's details is disabled? I find that it's too hard to press since I have to 'aim' the cursor to avoid clicking on the image thumbnail by accident.

Somewhat related is I found that the mass tagging state is reset if you click on "Posts" in the top bar after viewing a post's details, but not when using the browser's back button.

**Comment by sgsunder** [comment]
This is a pretty simple one-line fix in CSS.

@Ruin0x11 Can you try out PR #324 and let me know if that's enough?

**Comment by Ruin0x11** [comment]
I tried it out and it definitely helps. However the thing I was having in mind was making the button cover the entire thumbnail and making it more transparent. If I have time I can try writing a PR demonstrating. Thanks for merging this change also.
