### ISSUE TITLE
Add related projects?

### ISSUE THREAD

**Issue by FoxxMD** [rr-/szurubooru#326]
Wanted to make you aware of some projects that make of szurubooru in case you wanted to add them to docs/wiki/readme/whatever. I love this software and it would be cool to see more real-world showcases of how it's being used.

[Community App on Unraid](https://forums.unraid.net/topic/79126-support-foxxmd-szurubooru/) -- [Unraid](https://unraid.net/) is a linux OS geared for [JBOD](https://en.wikipedia.org/wiki/Non-RAID_drive_architectures#JBOD) NAS/VM/Docker server. Community Apps are basically templates for configuring docker containers that essentially give the Unraid community a way to one-click install apps (docker images). Disclaimer: I wrote the CA templates for szurubooru.

[imgbrd-grabber](https://github.com/Bionus/imgbrd-grabber) -- batch downloader for imageboard/boorus. They have recently [provided a script](https://github.com/Bionus/imgbrd-grabber/blob/develop/docs/_docs/commands/szurubooru.md) for use with szurubooru.

**Comment by sgsunder** [comment]
Good idea, I added the links you provided to the wiki [here](https://github.com/rr-/szurubooru/wiki/Related-projects)
