### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by Persistent13** [rr-/szurubooru#327]
Hello!

I've taken a look at and performed the steps in #217 (it's not possible to do the exact same as posted then but I did what it took to change the client_max_body_size value to 0, rebuilt the container, and update the compose file to use the new image) but I still cannot upload large files without getting the error `Request Entity Too Large`.

I tried searching around but it seems what throws that exact message isn't in the code base.

I'd like to be able to upload multi-gigabyte files, if possible.

Is there anything that can be done? If it is known where I could try my hand at it and submit a PR.

Thanks!

**Comment by sgsunder** [comment]
Are you operating behind a reverse proxy that limits file upload size?

You shouldn't have to change anything on our end to POST/PUT large files through the API, as the `client_max_body_size` is already set to 0

**Comment by Persistent13** [comment]
No, this is direct to the host running the containers. I'm uploading via the web client, should the API be used for large files?

**Comment by sgsunder** [comment]
OK, I think I found the issue. Waitress has a default max body size of 1 GB. You can change it to be higher by editing `docker-start.sh` with this ([ref](https://docs.pylonsproject.org/projects/waitress/en/stable/runner.html)): 

```
exec waitress-serve-3 --port ${PORT} --max-request-body-size <NUM> szurubooru.facade:app
```

However, I tried testing a 3 GB upload with this and Waitress ended up crashing. Not sure if such large uploads are really possible, unfortunately. You could try uploading with a hotlinked URL instead, if that workaround is feasable for you.

**Comment by Persistent13** [comment]
Oh well. Thank you for looking into it!

**Comment by WiggidyW** [comment]
> 
> 
> OK, I think I found the issue. Waitress has a default max body size of 1 GB. You can change it to be higher by editing `docker-start.sh` with this ([ref](https://docs.pylonsproject.org/projects/waitress/en/stable/runner.html)):
> 
> ```
> exec waitress-serve-3 --port ${PORT} --max-request-body-size <NUM> szurubooru.facade:app
> ```
> 
> However, I tried testing a 3 GB upload with this and Waitress ended up crashing. Not sure if such large uploads are really possible, unfortunately. You could try uploading with a hotlinked URL instead, if that workaround is feasable for you.

I believe the problem to lie here:
https://github.com/rr-/szurubooru/blob/f5111483af73595f8485f9c2b2a377fe2c549b3c/server/szurubooru/model/post.py#L220

After changing the type to "BigInt", I have been able to upload upwards of 15GB.
