### ISSUE TITLE
How to transfer an (outdated) booru between architectures

### ISSUE THREAD

**Issue by WychWitch** [rr-/szurubooru#330]
Hello, I've been trying to work on this for a while now but I need some help because I'm at a complete loss.

I have a booru running off my raspberry pi 3 (using my custom and probably very out of date compose/dockerfiles [here](https://github.com/rr-/szurubooru/issues/192#issuecomment-476897156)) until I got a standalone more traditional server, and I finally did this past week.

At first I just tried to copy/pasting the directories and .env as laid out [here](https://github.com/rr-/szurubooru/issues/255#issuecomment-487373997), but I quickly got the following error:
```
The database cluster was initialized without USE_FLOAT8_BYVAL but the server was compiled with USE_FLOAT8_BYVAL.
```
Which I soon found out was the result of the databases being made on different architectures. I then found out that I should be able to transfer between the two databases with pg_dump/pg_restore, but once I attempted that, it seemed to work at first, but once I launched the server I then got *this* error:
```
szurubooru.func.posts Unable to generate image hash data.
```
and when checking on the booru in the web browser, all of my tags and posts were there, but the images were not. I made sure to check that the images directory was in the correct place and there were no permissions issues, however it still didn't work.

I figured that maybe the imagehash problem was because the build was so old (old enough that `14377933` was the latest git commit, I don't know how to find the exact version number) that restoring the db probably wouldn't work,  so I made a backup of all of my booru folders and attempted to pull the latest images. When I did, I got this error with the sql:
```
The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.3.
```
At this point I'm at a loss on what to do. If I didn't have so many tags I probably would've just started over from scratch, but I don't want to lose over a year of tags if I don't have to.

Thank you in advance for any help anyone can give me, and tell me if there are any details I need to provide.

**Comment by sgsunder** [comment]
```
The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.3.
```

Hmm, I'm not really sure about the PostgreSQL error. You could pull and work with Postgres v11 instead of v12.3, and that should still be compatible with the latest commit of this project.

```
szurubooru.func.posts Unable to generate image hash data.
```

My immediate guess is that you didn't set the value of `secret` in the `config.yml` file to what it was in the previous installation. 

If you forgot what the `secret` value is, then you can run the admin tools (See [here](https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md#additional-features)) with the `--reset-filenames` flag. Note that this would rename all the files and break any direct hotlinks to the images.

**Comment by WychWitch** [comment]
> My immediate guess is that you didn't set the value of secret in the config.yml file to what it was in the previous installation.

THAT WAS IT THANK YOU SO MUCH I didn't know that the `secret` value affected more than Just salting the user's passwords. After trying it again it worked flawlessly!

In case anyone else runs into this problem, or just wants to know how I was able, here it is:

First, on the server with your booru, make a directory to store your backup. Next, open your `docker-composer.yml` file and put this line in the sql's volumes section:
```
- "<path/to/local.backup/folder>:/backup"
```
Next, launch *just* your database with the following command:
```
sudo docker-compose up sql
```

Once that's done running, be sure to note the name of the docker container. Open up another window, and type the following to log into your docker container:
```
sudo docker exec -it <name of docker-container> bash
```

move to the /backup folder, and type this:
```
pg_dump -U <databaseUser> -F t <databaseName> | gzip > dump.tar
```

Now, type `exit` to log out of docker and stop the running sql.

Next, zip the location of the `{MOUNT_DATA}` folder (in your .env file)

Now that you're done open up your favorite FTP program to download the zipped data folder and the dump.tar.

Now on your next server, follow the instructions as normal except make sure that your secret (in the server/config.yml file) is the exact same, create a local backup folder, add `- "<path/to/local.backup/folder>:/backup"` to the sql volumes location just like before, but finally stop at the part where you launch the sql docker.

Next, be sure to upload the dump.tar to your local backup folder, and upload and unzip the data folder to the correct location.

Now, log into your docker just like before:
```
sudo docker exec -it <name of docker-container> bash
```

cd to your `/backup` folder and type the following:
```
pg_restore -c -i -U  <databaseUser> -d <databaseName> -v "dump.tar" -W
```

Once that's done running, `exit` out of docker and finish running the installation!

There you have it! It should be restored to exactly the state you left it in.  Again, thank you sgunder for solving my problem
