### ISSUE TITLE
Bug: History page fails to render after adding a pool

### ISSUE THREAD

**Issue by robobenklein** [rr-/szurubooru#333]
https://github.com/rr-/szurubooru/blob/d420609f97e81d3bb696ec1b8bad927ae15b5c7b/client/js/util/views.js#L238

![image](https://user-images.githubusercontent.com/5423266/86294714-1f844380-bbc3-11ea-9cc0-75b636b3be4d.png)

```
app.min.js:formatted:14977 Uncaught (in promise) TypeError: Cannot read property 'names' of undefined
    at Object.O [as makePoolLink] (app.min.js:formatted:14977)
    at Object.l [as makeResourceLink] (app.min.js:formatted:19436)
    at snapshots-page (app.min.js:formatted:1091)
    at app.min.js:formatted:15149
    at new e (app.min.js:formatted:19486)
    at Object.e [as pageRenderer] (app.min.js:formatted:4226)
    at app.min.js:formatted:16067
```

My intuition says that both `pool` and `name` shouldn't be undefined, so I don't think my first idea approach of just checking whether `pool` is set and use `"unknown"` would be a real solution, though it might at least allow the page to render at least some content.

**Comment by zakame** [comment]
I also experience this when a post is deleted; `o` (`pool`) simply does not exist for an already-deleted post.

**Comment by robobenklein** [comment]
Oh, does this happen *only* for deleted posts? If so then I can probably fix it myself.
