### ISSUE TITLE
Mass edit does not apply implied tags

### ISSUE THREAD

**Issue by Kangaroux** [rr-/szurubooru#334]
Implied tags are not added when doing mass tag editing. It only seems to add them when editing a single image.

**Comment by sgsunder** [comment]
I believe this is by design. @rr- can you confirm?

If not I'll try to author a fix to it.

**Comment by rr-** [comment]
This intended, but could be configurable

**Comment by TangentFoxy** [comment]
I would like mass tagging to use implications as well.
