### ISSUE TITLE
Feature Request: Adding "Implied By" for Multiple Tag support

### ISSUE THREAD

**Issue by ArchiusPendragon** [rr-/szurubooru#337]
As the title suggests, this is a request for an extension to the Tag implications system, such that a tag can be implied by group of tags.

At present, the system only supports a direct 1-to-1 Parent>Child system, where-in the privileged user would create a tag; <tagA> to imply <tagB>. However, one cannot go to <tagB> and set an implication. For tags that directly imply the existence of another, this system works just fine. 

However, for tags that are implied only when a group of tags are used, this becomes a bit problematic. 
For example "<TagA> and <TagB> don't inherently imply anything, but together, they imply <TagC>" - within the current system this isn't possible.

I understand this may be difficult, as the way the imply system works is relying on the addition of the parented tag to then add the child tag. 
Is this within scope for this, or would this be considered something to complex or to resource intensive to implement?

**Comment by sgsunder** [comment]
Can you briefly explain how this could be implemented? It seems like it would require a major change in our database schema.

**Comment by KuwuroUsagi** [comment]
This sounds nice in theory but in practicality there would most likely be a lot of false positives. The current implication system covers a lot, and users will fill the gaps anyway.
My current usage of implications would cause, for example, certain combinations of tags to suggest a specific character. Which would cause false positives frequently if character designs were similar enough between media.
The usage feels quite niche, and would only exist to assist taggers who don't know additional tags to use, which again, can be covered by others as time passes.

**Comment by sgsunder** [comment]
Marking as won't fix. This requires too drastic of a database schema change for too small of an edge case.
