### ISSUE TITLE
[Feature Request] Webhook support

### ISSUE THREAD

**Issue by noirscape** [rr-/szurubooru#339]
Basically, what it says on the title. Right now, if I want to use an external tool to do something when something changes in the history, it means I would have to periodically poll the Snapshots API endpoint. This to me seems rather inefficient.

One solution to this would be to allow administrators to set up a webhook URL which is then expected to be able to receive a snapshot resource, so that I can set up my external tool to simply monitor requests made to the URLs endpoint and process snapshot resources that way.

**Comment by sgsunder** [comment]
Would you be able to look at PR #341 and see if that works or if there's something more that can be done?

**Comment by noirscape** [comment]
Looks good to me at a glance.
