### ISSUE TITLE
Feature request: Delete one's own post

### ISSUE THREAD

**Issue by lastrosade** [rr-/szurubooru#346]
Currently the 'post;delete' setting in config.yaml covers the deletion of any posts.
It would be nice to have a 'post:self-delete' or similar that allows users to remove their own posts.

**Comment by sgsunder** [comment]
Can you describe the use case in more detail? Creating/modifying/curating posts in a booru are usually meant to be a collaborative effort, I don't think it's appropriate for users to end up deleting posts that they created but others have put effort into curating. So it makes sense for users who want to delete self-posts to also have global deletion privileges. But perhaps there's an edge case where this would be appropriate.
