### ISSUE TITLE
Feature request: "Unconfirmed tags"

### ISSUE THREAD

**Issue by noirscape** [rr-/szurubooru#360]
This needs a better name, but here goes.

I, as well as from what I've seen repeatedly with other people, don't directly tag my images. Rather, I use a script that automatically attempts to fetch tags from other sites and apply them to posts. Unfortunately, as with any such tool, there comes a moment when you just get a misfire. Maybe saucenao's response was totally off for example, which results in image tags being way off, which can be annoying to clean out (and sometimes a wrong source, but that's far less annoying).

To this end, it would be useful to have the option on the API only (this wouldn't have to be something to be editable on the frontend besides confirming the tag) to be able to set "unconfirmed tags". These tags would then be returned seperately from normal tags, and in the frontend could then be marked in a slightly greyer shade or with a different label icon than confirmed tags. Then, in the edit interface, make it possible to confirm tags if they are correctly applied.

This would then also come with a special search filter to either only look at posts with unconfirmed tags or only look at posts with confirmed tags.

In a similar sense, this would also make it possible to allow for implementing retroactive implications, as these tags could then be marked as unconfirmed. (Something which I suggested before in #189).

**Comment by sgsunder** [comment]
This seems needlessly complicated for a very specific edge case. Wouldn't it be easier just to have a "check_tags" tag to a post that was tagged by a script, which a human can later come by and delete once they confirm the tags are good?

**Comment by noirscape** [comment]
Ah yeah, I might just do that.

I'll leave it open at least for the recursive implications thing, it's still useful for that.

**Comment by sgsunder** [comment]
I think it is best to avoid doing anything that automatically changes the tags/properties on multiple posts like that. I think it's better to have people use the mass tagger to manually add missing implications if desired, or a customized script if finer control is needed.
