### ISSUE TITLE
Helpdesk: Reverse proxy-ing using a PHP script

### ISSUE THREAD

**Issue by Pruffer** [rr-/szurubooru#361]
Hello- this might sound like an odd thing to do, but in my super specific use case, it's probably the best solution.
I've been trying to use [https://github.com/michaelfranzl/no.php](url) to create a reverse proxy for Szurubooru, but it seems just doing `BASE_URL=/no.php/` and `domain: https://domain.tld/no.php` isn't quite enough.

It seems every .js / .css file returns as the loading page, and all Szurubooru shows is: `client_1  | 172.27.0.1 -> GET //no.php/ HTTP/1.1 [200] - referer: - xx.xx.xx.xx`. It doesn't show requests for all the static files, but that might just be because they're being cached. No API requests either, though, only that one request for the `client` part.

I've tried different combinations for the `BASE_URL` setting just in case, but `/no.php`, `no.php/` and `no.php` all do the same.

My config.yaml and .env files are, apart from those 2 settings, the same as they are in the examples, with the port being set to 8080. 

My no.php settings:
```
$backend_url = "http://localhost:8080/";
$backend_info = parse_url($backend_url);
$host = $_SERVER['HTTP_HOST'];
$request_uri = $_SERVER['REQUEST_URI'];
$uri_rel = "no.php"; # URI to this file relative to public_html
```
-so Szurubooru would be accessed by going to `https://domain.tld/no.php/`. With the posts being at `https://domain.tld/no.php/posts`, etc. 

I do apologize if there's some obvious mistake I'm making, or if I'm asking in the wrong place. But after a day of trying to figure out what I'm doing wrong, I'm at a loss.

**Comment by sgsunder** [comment]
Hmm, not familiar with no.php, but it might be possible that it's not stripping the base url prefix when it passes to szurubooru.

What *should* happen:
- Browser requests to no.php: `https://domain.tld/no.php/posts/1`
- no.php requests to szurubooru client container: `https://localhost:8080/posts/1`

What seems to be happening in your case:
- Browser requests to no.php: `https://domain.tld/no.php/posts/1`
- no.php requests to szurubooru client container: `https://localhost:8080/no.php/posts/1`

Again, I'm not sure how to configure no.php to do the right thing, but I hope this points you in the right direction

**Comment by Pruffer** [comment]
Thank you for the help! I'm not sure what the actual issue was, but I believe it was something with no.php.. or Cloudflare? 
Before, even when `GET /` was being requested, nothing happened- but suddenly, everything works. 
There were content encoding errors all over the place as well. Those disappeared out of nowhere.

But.. it works now. somehow. For anyone else having this issue, I'm adding my working configuration below:
no.php:
```
$backend_url = "http://localhost:8080";
$backend_info = parse_url($backend_url);
$host = $_SERVER['HTTP_HOST'];
$request_uri = $_SERVER['REQUEST_URI'];
$uri_rel = "/no.php/"; # URI to this file relative to public_html
$request_includes_nophp_uri = false;
```
.env:
```
BASE_URL=/booru.php/
```
config.yaml:
```
domain: https://domain.tld
```

Thanks again for the help!
