### ISSUE TITLE
Cannot update from 2.3 to 2.4

### ISSUE THREAD

**Issue by Hunternif** [rr-/szurubooru#364]
I had a working instance of szurubooru that I haven't used for a while. On the homepage the version is displayed like this:
`Build v2.3-edge-6a95a66 from 7 months ago`

Then I do the following:
```
1. git pull
2. (manually update server/config.yaml, copying in the new permissions)
3. sudo docker-compose pull
4. sudo docker-compose up -d
```
I'm seeing builds get pulled successfully, and run successfully.
However, the home page still displays the same version, and I'm not seeing any new functionality like Pools.

I also tried building locally following this manual, but I got the same result: https://github.com/rr-/szurubooru/wiki/ARM-and-Raspberry-Pi-Support-for-Docker-builds

I verified that git pull actually worked, and the last commit is https://github.com/rr-/szurubooru/commit/59452711668b9f7a7aeea3c57301b22882987c2b

Please help 🙏

**Comment by noirscape** [comment]
Do `docker-compose down`, then `docker-compose up -d`. That might be needed I think for properly recreating the image?

**Comment by Hunternif** [comment]
I tried all those commands in different combinations. Could be something wrong with my VM.

**Comment by sgsunder** [comment]
1. Clear browser cache
2. If using a reverse proxy, clear any cache on that
3. In `docker-compose.yml` make sure that the server image and client image being pulled is either
     a. The latest from the docker repo `image: szurubooru/server:latest` and `image: szurubooru/client:latest`
     b. The image is being built directly from the local source code
