### ISSUE TITLE
Additional "Search On:"  links for external *boorus

### ISSUE THREAD

**Issue by ShockDW** [rr-/szurubooru#367]
It would be nice to add functions to the "Search On:" section of the Post sidebar for searches on external boorus via md5 checksum.
Naturally this is a more "strict" search vs a perceptual hash based approach used by IQDB or Google Images, but it would offer both an alternative search method for those of us running Szurubooru on a local network, and easy access to reference points for tags and the like.

Example (client/html/post_readonly_sidebar.tpl)
```html
<section class='search'>
    Search on
    <a href='http://iqdb.org/?url=<%- encodeURIComponent(ctx.post.fullContentUrl) %>'>IQDB</a> &middot;
    <a href='https://www.google.com/searchbyimage?&image_url=<%- encodeURIComponent(ctx.post.fullContentUrl) %>'>Google Images</a>
    <a href='https://danbooru.donmai.us/posts?tags=md5:<%- MD5FUNC %>'>Danbooru</a>
    <a href='https://e621.net/posts?tags=md5:<%- MD5FUNC %>'>e621</a>
    <a href='https://gelbooru.com/index.php?page=post&s=list&tags=md5:<%- MD5FUNC %>'>Gelbooru</a>
</section>
```

I'm not sure how to call the necessary function to get the current image's MD5, else I'd just make a pull request for this.  If someone wants to point me in the right direction, I'll do just that.

**Comment by sgsunder** [comment]
Hmm, we already compute/store the SHA1 for each post on server-side, so it might be smart to also server-side compute the MD5 hash for cross-compatibility as well. ( See #148 )

It would then be pretty trivial to implement this feature on top of that.

**Comment by ShockDW** [comment]
Looks like we already have [the necessary function in util.py](https://github.com/rr-/szurubooru/blob/143f633eaac6b762bcae7877d98fec5e2f1a994c/server/szurubooru/func/util.py#L65) so I think the largest change would be to store it alongside the sha1 hash in Postgres.

**Comment by noirscape** [comment]
In support of storing the MD5 out of purely selfish reasons.

I maintain a library intended to reverse search image tags on sites like saucenao, danbooru and so on, and right now Paheal (although any danbooru API enabled shimmie instance really) is the only library that requires me to actually grab the image from the booru and calculate it's MD5 before sending it to their API. Having it precomputed on upload would save me some time.

**Comment by ShockDW** [comment]
> In support of storing the MD5 out of purely selfish reasons.
> 
> I maintain a library intended to reverse search image tags on sites like saucenao, danbooru and so on, and right now Paheal (although any danbooru API enabled shimmie instance really) is the only library that requires me to actually grab the image from the booru and calculate it's MD5 before sending it to their API. Having it precomputed on upload would save me some time.

To be completely honest, I'd like to build something similar to use in combination with the Szuru API in order to tag my (frankly massive) image collection.  Looking into that is what lead me to realize "Hey, this would bne a good fit for the main project as well".

**Comment by sgsunder** [comment]
Added danbooru to the list, as it's one of the more popular and general purpose boorus out there (Commit 8fa84abdc458e6d67031868f178af64aee62be8d). I don't want to add every single booru ever made, but it should be fairly easy to access the API directly if you need that level of customization.
