### ISSUE TITLE
youtube-dl sources

### ISSUE THREAD

**Issue by Kille250** [rr-/szurubooru#372]
If you try to download sources other than youtube, an exeption occurs with this message: Could not extract content location from xxx.

**Comment by sgsunder** [comment]
Can you provide an example link which doesn't work?

**Comment by Kille250** [comment]
Sure, try this out. https://twitter.com/officialtiz/status/1346525418690637824?s=21

**Comment by sgsunder** [comment]
> https://twitter.com/officialtiz/status/1346525418690637824?s=21

Szurubooru downloads media content in one of two ways:
1) A direct hotlink to a media file, which should always work regardless of it being a video or image.
2) A website with an embedded video. Szurubooru will use youtube-dl to fetch the embedded content URL and download that. Unfortunately, youtube-dl only works on embedded videos and [does not support embedded pictures](https://github.com/ytdl-org/youtube-dl/issues/9337#issuecomment-215442034). Because it's an upstream decision, I don't know of a good workaround for this (unless there's a good alternative to youtube-dl that supports images).

For your twitter link, you would have to "copy image location" and use that: https://pbs.twimg.com/media/Eq_RuxrXEAIeYkg?format=jpg&name=small

> https://vm.tiktok.com/ZSvnexBp/

This one just seems to be TikTok not playing nicely. I get a HTTP 403 even when I try and extract it manually

**Comment by Kille250** [comment]
yea, my fault for trying images out with youtube-dl. Really forgot about that. But one thing bothers me anyway. What exactly happens if you put on an instagram video. The logs are saying nothing but an post request.

ex. https://www.instagram.com/p/CJqw7R_lgjD/?utm_source=ig_web_copy_link

**Comment by sgsunder** [comment]
> https://www.instagram.com/p/CJqw7R_lgjD/?utm_source=ig_web_copy_link

This link works fine for me on the commit I just pushed (c732e62844719f4baf881ff0b9562701f736959e). Try pulling the new containers and checking if there's still an issue

**Comment by Kille250** [comment]
That is strange. I pulled your commit but the same error happens.

**Comment by sgsunder** [comment]
Can you post the logs / error message?

**Comment by Kille250** [comment]
sure

`server_1  | [2021-01-06 20:33:11] szurubooru.middleware.request_logger GET /tag-categories (user=SolidWolfe, queries=1)
client_1  | 192.168.0.1 -> GET /api/tag-categories HTTP/1.1 [200] - referer: https://solidwolfe.xyz/ 178.201.42.41, 108.162.229.242
server_1  | [2021-01-06 20:33:11] szurubooru.middleware.request_logger POST /user-token/SolidWolfe (user=SolidWolfe, queries=4)
client_1  | 192.168.0.1 -> POST /api/user-token/SolidWolfe HTTP/1.1 [200] - referer: https://solidwolfe.xyz/login 178.201.42.41, 108.162.229.242
server_1  | [2021-01-06 20:33:11] szurubooru.middleware.request_logger GET /pool-categories (user=SolidWolfe, queries=1)
client_1  | 192.168.0.1 -> GET /api/pool-categories HTTP/1.1 [200] - referer: https://solidwolfe.xyz/ 178.201.42.41, 108.162.229.242
server_1  | [2021-01-06 20:33:11] szurubooru.middleware.request_logger GET /info (user=SolidWolfe, queries=14)
client_1  | 192.168.0.1 -> GET /api/info HTTP/1.1 [200] - referer: https://solidwolfe.xyz/ 178.201.42.41, 108.162.229.242
server_1  | [2021-01-06 20:33:16] szurubooru.middleware.request_logger POST /uploads (user=SolidWolfe, queries=1)
client_1  | 192.168.0.1 -> POST /api/uploads HTTP/1.1 [500] - referer: https://solidwolfe.xyz/upload 178.201.42.41, 108.162.229.242
`

The website says: 
Could not extract content location from https://www.instagram.com/p/CJqw7R_lgjD/?utm_source=ig_web_copy_link

Not one error :(

**Comment by sgsunder** [comment]
The error is logged in this line: `192.168.0.1 -> POST /api/uploads HTTP/1.1 [500]`. You won't see a stack trace because there is an exception handler for the youtube-dl error.

The issue is that szurubooru is running the command
`youtube-dl --format best <--user-agent x> --get-url https://www.instagram.com/p/CJqw7R_lgjD/?utm_source=ig_web_copy_link`, but that command exits with a failure condition for some reason.

For me, the command works fine without a user agent specified. Are you defining a User Agent in the config?

**Comment by Kille250** [comment]
No, the user agent is left blank :c

**Comment by sgsunder** [comment]
What is the output of this command on your system?
```
docker run --rm szurubooru/server:latest youtube-dl --format best --get-url "https://www.instagram.com/p/CJqw7R_lgjD/\?utm_source\=ig_web_copy_link"
```
It should just return the instagram content URL without any errors, that is what happens for me

**Comment by Kille250** [comment]
`ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/instagram.py", line 216, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1128, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. `

yea, it cant extract the name. 😅

**Comment by sgsunder** [comment]
I have a feeling you might not have pulled the latest container

**Comment by Kille250** [comment]
You pull the latest image with docker-compose pull or am I wrong?

**Comment by Kille250** [comment]
![grafik](https://user-images.githubusercontent.com/10377034/103917824-55742880-510e-11eb-8d97-8857a451b5d7.png)

**Comment by sgsunder** [comment]
Ok I have no idea what is going wrong then. I'd have to defer you to asking the `youtube-dl` guys about the stack trace. The youtube-dl version in the current version of szurubooru is `2021.01.03`
