### ISSUE TITLE
Feature request: Retain uploaded filename as data field or upload filename parsing

### ISSUE THREAD

**Issue by 404Fox** [rr-/szurubooru#379]
Often, I upload files that have relevant source information in the filename.
It would be nice to retain those filenames for adding the source link later on.

Alternatively, the upload page could allow you to provide a parser string.

**Comment by sgsunder** [comment]
I'm cautious about adding and maintaining features for every single user case like this. It becomes hard to maintain and introduces potential failure points for a feature that only a handful would use. The open REST API is perfect for cases such as this.

I would suggest writing a script that parses the filenames and generates appropriate tags for them, then pushes the tags along with the file content to the REST API. That way, it can be tailored to fit your specific use case better than me trying to make a generalized solution.
