### ISSUE TITLE
Feature request: Support animated PNG

### ISSUE THREAD

**Issue by 404Fox** [rr-/szurubooru#381]
Currently, trying to upload an animated PNG results in "Unable to generate image hash data."

**Comment by sgsunder** [comment]
Hmm, I just tried an animated PNG and it worked fine. Can you give a failing example? Perhaps the file was corrupted?

**Comment by 404Fox** [comment]
Okay, this seems to only happen with animated pngs generated by an older version of pixivutil2. I can view them fine but only encounter an issue uploading them.
I can fix this on my side by replacing them.
