### ISSUE TITLE
Special characters in tags

### ISSUE THREAD

**Issue by SkandhaR** [rr-/szurubooru#383]
I have a tag for rosario+vampire. If I click on the tag, posts will display successfully.
![image](https://user-images.githubusercontent.com/34901480/112385164-85ae7a80-8cac-11eb-9e2b-041dc92a8472.png)
But I try to open the tag info, it leads to this error:
![image](https://user-images.githubusercontent.com/34901480/112385258-a1b21c00-8cac-11eb-973b-cc04201ee092.png)

**Comment by SkandhaR** [comment]
Wait... This seems like an error caused by how I'm accessing szurubooru. I'm accessing it through a reverse proxy on Windows IIS. 
![image](https://user-images.githubusercontent.com/34901480/112385723-30269d80-8cad-11eb-9b34-cbe120b137df.png)
I'll see if I can figure it out. If any of you have ideas please let me know, I'm a sysadmin but not much of a web guy.

**Comment by neobooru** [comment]
I vaguely remember having this issue too, though with a different reverse proxy. You could try [making this change to your config](https://confluence.atlassian.com/confkb/urls-with-a-plus-character-trigger-a-404-error-when-using-an-iis-reverse-proxy-server-312740228.html). If that doesn't work then please open the browser's debug console to show us the error code in the "Network" tab.

**Comment by SkandhaR** [comment]
> I vaguely remember having this issue too, though with a different reverse proxy. You could try [making this change to your config](https://confluence.atlassian.com/confkb/urls-with-a-plus-character-trigger-a-404-error-when-using-an-iis-reverse-proxy-server-312740228.html). If that doesn't work then please open the browser's debug console to show us the error code in the "Network" tab.

Bingo, that fixed the issue! Thank you!

    <security>
      <requestFiltering allowDoubleEscaping="true" />
    </security>
