### ISSUE TITLE
Problems with escaping periods in tags

### ISSUE THREAD

**Issue by Fernsicles** [rr-/szurubooru#385]
Related to #97
As far as I can tell, tags with periods in them aren't escaped properly.
A tag that is just `..` ends up breaking completely, and will link to the base domain.
Video:

https://user-images.githubusercontent.com/22437119/112930722-ac671980-90cf-11eb-9adb-a87f7c97407d.mp4

**Comment by neobooru** [comment]
In my PR I explained why `.` and `..` probably don't work. Probably because `.` = `{this directory}` and `..` = `{parent directory}`. I'd argue that having `..` as a tag seems a bit silly, but maybe you can give a real life use case for this?

**Comment by Fernsicles** [comment]
I don't see much point being able to use `.` or `..` either, but the fact that I can add them and then can't remove them using the gui seems like an issue.

**Comment by neobooru** [comment]
Good point. I assume that all tags that consists only out of dots should be disallowed? E.g. `...` should also not be allowed.
In your opinion, should tags like test..test or test.test be allowed?

**Comment by Fernsicles** [comment]
I think everything other than `.` and `..` can work if escaped properly, and in my case, `...` is actually a tag. For example, `...` doesn't work when searching, but `\.\.\.` works fine. In my opinion, `.` and `..` should be forbidden from being entered in the gui, and dots should be escaped when clicking on links otherwise.

**Comment by neobooru** [comment]
Alright 👍
I'll also try to implement auto-escaping whenever you click/input an auto-completed tag. That seems like an useful feature too.
![image](https://user-images.githubusercontent.com/50623835/114323246-daa71900-9b13-11eb-808f-e84310fa6880.png)

Small disclaimer, it's still up to the owners on whether they accept my PR, so I can't guarantee that everything discussed will make it in.

**Comment by Fernsicles** [comment]
Cool, thanks! I think there were a few commits that added escaping for other special characters, like https://github.com/rr-/szurubooru/commit/93910a1655f0f536d8927415935ab316bcad376f.

**Comment by neobooru** [comment]
In the PR I added a commit which automatically escapes the dots in your search term when you use the autocomplete feature. I also added a check which disallows the use of `.` and `..`
However the existing tags will not be removed, so you'll have to remove those two manually (probably through the API, but looking at your profile I think you can manage that).

**Comment by sgsunder** [comment]
I think that this can be considered resolved now that #390 is merged.
