### ISSUE TITLE
Feature request: Support .svg files

### ISSUE THREAD

**Issue by Metal-Mighty** [rr-/szurubooru#386]
I am setting up a Szurubooru instance as a kind of archive for game artworks for my website and some arts are in the SVG format. Would it be possible to add the support for SVG file upload ?

I checked the code and it shouldn't be too hard to implement, the "toughest" part being to detect correct SVG files in [server/szurubooru/func/posts.py](https://github.com/rr-/szurubooru/blob/7b54551b8e9dd8b9258ad1e0469a3a1264f29873/server/szurubooru/func/posts.py#L607), I don't think `get_mime_type` can be used with it since it's a XML structure and not a binary file like the other formats.

**Comment by sgsunder** [comment]
Would be pretty complicated to implement. Backend uses Pillow and ffmpeg for image processing and manipulation, which only work with raster images. The reverse image search algorithm also only works with raster images.
