### ISSUE TITLE
Filter posts by containing tag with category?

### ISSUE THREAD

**Issue by 404Fox** [rr-/szurubooru#438]
Is it possible to filter posts by whether or not it contains any tags within a category?
For example, I have a artist category and I want to filter out images that have any tag belonging to that category, so that the remaining images are those which don't have an artist tag.

If not, would it be possible to implement?
I imagine the simple way is to get a table containing all artist tags then filter all of those tags against posts. Then, a new token like `tagged-with-category` or `has-tags-from-category`
I probably don't know what I'm talking about, I only took an SQL class.

**Comment by neobooru** [comment]
Yeah, I think this would be a good idea. For tags you can already search for `category:artist`, but again that only works when searching for tags.

Not too sure about what the keyword should be called, maybe just `category:{tagname}` just like when searching for tags? Taking suggestions.

**Comment by brandonquirarte** [comment]
I actually came here today to request this feature. Nice to see at least someone else wants it.

@neobooru I think keeping a common naming convention sounds like a good idea. You could also create aliases if you want to make things more clear.
