### ISSUE TITLE
Docker Hub Autobuilds not working

### ISSUE THREAD

**Issue by sgsunder** [rr-/szurubooru#439]
@rr- 
@neobooru 

So it seems that a ToS change from Docker Hub might have prevented us from using the autobuild feature on the free plan. :(

I haven't done much digging in to it yet but we may want to explore GitHub's Container registry as an alternate.

Worst case, I could maybe host a CI/CD runner on my home server, of course I won't be able to the uptime/stability of a proper service...

**Comment by rr-** [comment]
Hrmm
Would GitHub actions help? I have a few projects where we've been using GH actions to build the app with docker and push the artifacts to the GH releases. I don't see why we shouldn't be able to docker push to DockerHub.

**Comment by noirscape** [comment]
I've seen it used as an alternative, but GH actions has a limited plan of 2000 free minutes on the account hosting it across all projects per month, then it starts billing.

If we assume a build takes ~20 minutes at most, you get 100 builds a month. There's also an account-wide 500mb storage cap for free accounts (includes action cache and container registry), which might interfere? I'm not 100% on how big the repo is when you add all the deps and stuff (not to mention history).

Some things to perhaps consider. A custom CI/CD runner wouldn't have that problem of course.

**Comment by sgsunder** [comment]
It looks like GH actions is free for public repos so we should be good. ([link](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions), see first para.)

I'll start authoring a commit to migrate our current build/test hooks to the GitHub runner syntax

**Comment by neobooru** [comment]
> 
> 
> It looks like GH actions is free for public repos so we should be good. ([link](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions), see first para.)
> 
> I'll start authoring a commit to migrate our current build/test hooks to the GitHub runner syntax

Yeah I just found about that too. GH Actions would be the most logical alternative imo.

I already tested a very basic setup yesterday, [which can be found here](https://github.com/neobooru/szurubooru/blob/master/.github/workflows/docker-hub-build-push.yml). The only thing missing is that it also creates tags like `2.5-latest` etc.

**Comment by sgsunder** [comment]
I have a commit ready for push, but @rr- needs to include the DockerHub access credentials as a repository secret first.

You need the following secrets (see [here](https://github.com/marketplace/actions/docker-login#docker-hub) for ref.):
- `DOCKERHUB_USERNAME`: I think this can just be `szurubooru` since we have an org account
- `DOCKERHUB_TOKEN`: See [here](https://docs.docker.com/docker-hub/access-tokens/#create-an-access-token) for instructions. Should be made under the szurubooru org account, and should have read+write permissions. (No delete)

Instructions on how to add secrets to GitHub repos [here](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository).

**Comment by sgsunder** [comment]
I've also been able to create a working implementation of #309 through Actions, so we can now build multi-arch containers for our Raspberry Pi users as well.

**Comment by sgsunder** [comment]
@rr- have you had a chance to add the DockerHub credentials?

**Comment by rr-** [comment]
I've added them now to GH secrets:
DOCKERHUB_PASSWORD
DOCKERHUB_USERNAME

**Comment by sgsunder** [comment]
@rr- seems like we're getting an issue logging in with those credentials. See the log in this project's Actions tab

**Comment by rr-** [comment]
@sgsunder can you please try again?

**Comment by sgsunder** [comment]
Looks like it's working now! Will try now to push the multi-arch container build

**Comment by sgsunder** [comment]
Multi-arch builds are also working! Closing
