### ISSUE TITLE
Feature Request: Mass deletion of posts 

### ISSUE THREAD

**Issue by FlipperLP** [rr-/szurubooru#456]
Would it be possible to implement a mass deletion-feature? 

I recently made an automation to add posts from my submission box on furaffinity. But sometimes it's necessary to clean up some posts, so wanted to ask if there is any chance to add a mass deletion-feature. It would function the same way as Mass Tag or Mass edit safety.

**Comment by neobooru** [comment]
I started working on the frontend for this. How does this look? The "Delete x posts" button looks a bit out of place imo, but I wouldn't know where else to put it.

![img](https://user-images.githubusercontent.com/50623835/149601372-bddfd3a9-6d56-4a82-b3cb-afde4e05e057.png)
![img](https://user-images.githubusercontent.com/50623835/149601379-56e8a075-3c2a-42e9-adfc-59545f1cc90d.png)

**Comment by FlipperLP** [comment]
I think the other 2 buttons feel out of place as well, maybe they should be moved in the future, but for now I think it's fine to keep them where they are.
Thank you for visualizing it!

**Comment by pink-red** [comment]
> The "Delete x posts" button looks a bit out of place imo

Maybe moving everything but "Syntax help" to the right side of the page would help? So that there's everything search-related on the left and bulk actions on the right.

But overall I would agree with @FlipperLP that this is already fine.

**Comment by pink-red** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/94079189/149638741-f39aa66c-3fe7-44ff-836e-240748d95561.png)
![image](https://user-images.githubusercontent.com/94079189/149638776-0609593c-13ef-48d1-869d-c785954269b3.png)

**Comment by studiomav** [comment]
Any such solution would be greatly appreciated...

**Comment by panda-lsy** [comment]
Any such solution would be greatly appreciated❤

**Comment by neobooru** [comment]
#459 has been merged, so I'll close this issue. Please create a new issue if something is broken or can be improved.
