### ISSUE TITLE
Error 'Request Entity Too Large' when uploading somewhat bigger files

### ISSUE THREAD

**Issue by chris2467** [rr-/szurubooru#478]
I'm receiving the error "Request Entity Too Large" when uploading somewhat bigger files.
I have already increased the value of 'client_max_body_size' in client's nginx.conf.docker file but the error remains.

Is there anything I'm missing?

**Comment by neobooru** [comment]
The nginx.conf.docker file is not actually used (unless you build the client image yourself), and I believe the default max body size is 1GB (imo a bit too large even). Are you perhaps using your own reverse proxy where you might need to change the parameter as well? I just tried the default installation and I could upload a 260MB file just fine.

If you are not using a reverse proxy then please ensure that you are on the latest version by running:
```
docker-compose pull
docker-compose up -d
```

**Comment by chris2467** [comment]
The file I'm trying to upload is a little over 1GB, can I change the default max body size?

**Comment by neobooru** [comment]
Ah sorry, I assumed that 1GB would be enough. Yes you can change the max body size, but this requires you to rebuild both the server and client locally. Additionally szurubooru isn't designed/tested with files this big, so you might run into unexpected issues. After you upload a large file it might look like it is stuck, but it's actually just searching for duplicates/similar posts. This can take a moment so just leave it be.

This commit shows you which changes you have to make https://github.com/neobooru/szurubooru/commit/8b344ab8c163c6029bc5dbd7932125c8586666c3 
After this just run `docker-compose up` in the project root and you should be good to go.

**Comment by chris2467** [comment]
Hi neobooru, thank you for your help, much appreciated.
I however receive the following error when I perform the changes and run docker-compose up:
Step 5/31 : COPY ./ /opt/app/
 ---> c1dd331dc3f8
Step 6/31 : RUN rm -rf /opt/app/szurubooru/tests
 ---> Running in 59ad47dc7a6c
Removing intermediate container 59ad47dc7a6c
 ---> 8acf0f397a23
Step 7/31 : FROM --platform=$BUILDPLATFORM prereqs as testing
ERROR: Service 'server' failed to build: failed to parse platform : "" is an inv                                                                                                                                                             alid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$"                                                                                                                                                             : invalid argument

**Comment by chris2467** [comment]
Nevermind, said error was documented in the installation guide

**Comment by neobooru** [comment]
I haven't tested this yet, but it might work.
Try adding the following lines below your `client_max_body_size` entry in the nginx config.
```
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;
```
You can replace 600 with any other number, it uses seconds as time unit. In this example the timeout should be 10 minutes.

If this still doesn't work then please share your `docker-compose logs` output.

**Comment by chris2467** [comment]
That solved it, thank you neobooru
