### ISSUE TITLE
Help setting up szuru outside of docker

### ISSUE THREAD

**Issue by ziimro** [rr-/szurubooru#480]
A really dumb issue post i know.
I dont have a lot of experience with setting up api's and apps on a webserver.
I have gotten to [this point](https://github.com/rr-/szurubooru/wiki/Installation-without-Docker#wiring-szurubooru-to-the-web-server) in the guide but have no idea what to do next to actually run the server on my localhost

**Comment by neobooru** [comment]
What exactly are you asking? At that point in the guide you have to configure either nginx or apache2 to server the static files and redirect the /api calls to the python backend. It doesn't matter whether you use nginx or apache2, though obviously only use one.

If you tell us more about your webserver (linux or windows, and if linux which distro) and which steps you did so far (including where you placed the files and which settings you changed) then we'll be able to better help you.
