### ISSUE TITLE
Szurubooru build update fails

### ISSUE THREAD

**Issue by chris2467** [rr-/szurubooru#510]
Hi,

In docker-compose.yml I have configured to build because I made some changes to facilitate upload of larger files to szurubooru.
Now I'm trying to update my szurubooru but it fails with the following error:
szurubooru@szurubooru:~/szuru$ sudo docker-compose up --force-recreate --build -d
Building server
Sending build context to Docker daemon  1.006MB
Step 1/31 : ARG ALPINE_VERSION=3.13
Step 2/31 : FROM alpine:$ALPINE_VERSION as prereqs
 ---> 6b5c5e00213a
Step 3/31 : WORKDIR /opt/app
 ---> Using cache
 ---> eaaadbf7b1e9
Step 4/31 : RUN apk --no-cache add         python3         python3-dev         py3-pip         build-base         libheif         libheif-dev         libavif         libavif-dev         ffmpeg         py3-yaml         py3-psycopg2         py3-sqlalchemy         py3-certifi         py3-numpy         py3-pillow         py3-pynacl         py3-tz         py3-pyrfc3339  && pip3 install --no-cache-dir --disable-pip-version-check         "alembic>=0.8.5"         "coloredlogs==5.0"         "pyheif==0.6.1"         "heif-image-plugin>=0.3.2"         youtube_dl         "pillow-avif-plugin>=1.1.0"  && apk --no-cache del py3-pip
 ---> Using cache
 ---> b97bbcfdad60
Step 5/31 : COPY ./ /opt/app/
 ---> Using cache
 ---> 778de13e3ad6
Step 6/31 : RUN rm -rf /opt/app/szurubooru/tests
 ---> Using cache
 ---> 63ceb465bca2
Step 7/31 : FROM --platform=$BUILDPLATFORM prereqs as testing
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
ERROR: Service 'server' failed to build : Build failed
szurubooru@szurubooru:~/szuru$

What should I do to resolve this and update my container?

**Comment by noirscape** [comment]
This is in the install document: https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md#building

See step 2 under building. You need to export docker buildkit flags.

**Comment by chris2467** [comment]
I did, that didn't fix it:

szurubooru@szurubooru:~/szuru$ export DOCKER_BUILDKIT=1; export COMPOSE_DOCKER_CLI_BUILD=1
szurubooru@szurubooru:~/szuru$ sudo docker-compose up --force-recreate --build -d
Building server
Sending build context to Docker daemon  1.006MB
Step 1/31 : ARG ALPINE_VERSION=3.13
Step 2/31 : FROM alpine:$ALPINE_VERSION as prereqs
 ---> 6b5c5e00213a
Step 3/31 : WORKDIR /opt/app
 ---> Using cache
 ---> eaaadbf7b1e9
Step 4/31 : RUN apk --no-cache add         python3         python3-dev         py3-pip         build-base         libheif         libheif-dev         libavif         libavif-dev         ffmpeg         py3-yaml         py3-psycopg2         py3-sqlalchemy         py3-certifi         py3-numpy         py3-pillow         py3-pynacl         py3-tz         py3-pyrfc3339  && pip3 install --no-cache-dir --disable-pip-version-check         "alembic>=0.8.5"         "coloredlogs==5.0"         "pyheif==0.6.1"         "heif-image-plugin>=0.3.2"         youtube_dl         "pillow-avif-plugin>=1.1.0"  && apk --no-cache del py3-pip
 ---> Using cache
 ---> b97bbcfdad60
Step 5/31 : COPY ./ /opt/app/
 ---> Using cache
 ---> 778de13e3ad6
Step 6/31 : RUN rm -rf /opt/app/szurubooru/tests
 ---> Using cache
 ---> 63ceb465bca2
Step 7/31 : FROM --platform=$BUILDPLATFORM prereqs as testing
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
ERROR: Service 'server' failed to build : Build failed

**Comment by neobooru** [comment]
Please try this command
```sh
sudo DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
```
or this one
```sh
export DOCKER_BUILDKIT=1; export COMPOSE_DOCKER_CLI_BUILD=1
sudo -E docker-compose build
```

When using `sudo` your environment variables (DOCKER_BUILDKIT and COMPOSE_DOCKER_CLI_BUILD) don't get passed to the command (unless you use the -E flag).
