### ISSUE TITLE
Add Text on Home footer

### ISSUE THREAD

**Issue by xShoalKing** [rr-/szurubooru#512]
I need to add a text and a link on Home footer (links for example) but when i edit the file home_footer.tpl (in szuru/client/html)
but when i do the changes, nothing happens or shows :(

**Comment by neobooru** [comment]
You need to rebuild the docker szurubooru/client image. [These instructions](https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md#building) will show you how to do that.

**Comment by xShoalKing** [comment]
can't run it cause it says client failed to build: stage name already used, now i can't even put it back on :(

**Comment by neobooru** [comment]
What changes did you make and which command did you run?
You only need to change `image: szurubooru/client:latest` to `build: client` inside docker-compose.yml, and then run `docker-compose build`
If that doesn't work then please show me your docker-compose.yml and the full command output.

**Comment by xShoalKing** [comment]
Yep, changed Dockerfile too here's the Docker-compose.yml + Dockerfile:

Dockerfile edits:
```
# Example
FROM --platform=$BUILDPLATFORM node:lts as builder
# becomes
FROM node:lts as builder

`## Example Docker Compose configuration
##
## Use this as a template to set up docker-compose, or as guide to set up other
## orchestration services
version: '2'
 
```
services:
 
  server:
    build: server
    depends_on:
      - sql
    environment:
      ## These should be the names of the dependent containers listed below,
      ## or FQDNs/IP addresses if these services are running outside of Docker
      POSTGRES_HOST: sql
      ## Credentials for database:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      ## Commented Values are Default:
      #POSTGRES_DB: defaults to same as POSTGRES_USER
      #POSTGRES_PORT: 5432
      #LOG_SQL: 0 (1 for verbose SQL logs)
      THREADS:
    volumes:
      - "${MOUNT_DATA}:/data"
      - "./server/config.yaml:/opt/app/config.yaml"
 
  client:
    build: client
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
      BASE_URL:
    volumes:
      - "${MOUNT_DATA}:/data:ro"
    ports:
      - "${PORT}:80"
 
  sql:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"
 `

**Comment by xShoalKing** [comment]
If I restore Dockerfile to the original state I get:
`ERROR: Service 'server' failed to build: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument`
even with
`export DOCKER_BUILDKIT=1; export COMPOSE_DOCKER_CLI_BUILD=1`
and the command bundled with `docker-compose build --no-cache`

**Comment by neobooru** [comment]
Okay that is weird, could you give me the output of the following commands?
```
cat /etc/os-release
docker version
docker-compose version
```

I guess you could also try `COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build`, but I don't really expect that to work.

**Comment by xShoalKing** [comment]
Can't run cat /ect/os-release it says no such file or directory

This is Docker version
```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Dec 18 12:33:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false
 
Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false

```
This is docker-compose version
```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by neobooru** [comment]
That's a a pretty ancient version of docker and docker compose. I assume you are using linux? Which distro are you using? 
I think you could solve your issue by updating your docker + docker-compose, but depending on which distro you are using this could be somewhat difficult.

**Comment by xShoalKing** [comment]
Ubuntu 16.04 64bit with LXDE Desktop
tbh, before doing bullshits to try fixing the updates not showing it was working :(

**Comment by xShoalKing** [comment]
I did a fresh install, but if i edit something and follow the instruction like this

```
server:
- image: szurubooru/server:latest
+ build: server
...
client:
- image: szurubooru/client:latest
+ build: client
```
This happens

`ERROR: Service 'server' failed to build: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument`

**Comment by neobooru** [comment]
What do you mean with a fresh install? A newer ubuntu install or just a clean installation of szurubooru?

If you don't change those lines (e.g. keep `image: szurubooru/server:latest`) then it will work just fine, because then it uses a pre-built image. The downside to this is that it won't have your changes. If you want your changes to actually go through then you need to build your own custom image, which (probably) requires a newer version of docker-compose (and maybe docker too, idk).

You could try [this](https://docs.docker.com/compose/install/other), but ideally you'd have to use a newer ubuntu version.

**Comment by xShoalKing** [comment]
So, I have some news;
I completely uninstalled "Docker" and reinstalled every core component with .deb + last Docker compose version with your link

Now the setting in Docker-compose.yml no loger generate error when `docker-compose build --no-cache`:
Docker-compose.yml setting is:
```
server:
- image: szurubooru/server:latest
+ build: server
...
client:
- image: szurubooru/client:latest
+ build: client
```

Although the edits I did in in /root/szuru/client/html/home.tpl and home_footer.tpl still doesn't reflect on website

**Comment by xShoalKing** [comment]
New update!
`Docker-compose client up -d` worked, changes now reflects on website

Problem solved, thanks for your help @neobooru!

**Comment by neobooru** [comment]
Good to hear that. If for some reason this issue still isn't resolved then feel free to reopen it.
