### ISSUE TITLE
problem with html

### ISSUE THREAD

**Issue by IlyaKangin** [rr-/szurubooru#515]
After changing files in html, nothing changed in the end
I tried to build docker-compose again, without success

**Comment by skybldev** [comment]
Are you making sure to configure docker-compose.yml accordingly? If so and it still fails, what errors are you getting exacty?

**Comment by IlyaKangin** [comment]
i don't get errors, I don't change the site, although I change the code as-want

**Comment by skybldev** [comment]
I don't completely understand what you mean. How exactly are you editing the HTML?

**Comment by IlyaKangin** [comment]
I am editing a file in /client/html/home.tpl

**Comment by IlyaKangin** [comment]
i have tutorial of colors, get normal build. i close this issue.
