### ISSUE TITLE
How to remove a post from featured?

### ISSUE THREAD

**Issue by UsualVII** [rr-/szurubooru#517]
I featured one post by mistake, how i can remove it?

**Comment by neobooru** [comment]
At the moment you can't. If you feature another post then it will overwrite the previous one, but there is not way to remove all featured posts from the homepage (other than deleting the featured posts).

---

There is a way remove **all featured posts history**, after which there will be no post on the frontpage.
This however requires you to directly interact with the database, which is a bit tricky.
You can follow these instructions (these only work for the default docker setup) to remove all featured posts history.

**Keep in mind that this is unsupported and mostly untested! 
It seemed to work fine on my pc, but no guarantees!**

```sh
# Go to the szurubooru root folder
cd whatever/szurubooru

# Ensure that the containers are running
docker-compose ps

# Example output
# NAME                  COMMAND                  SERVICE             STATUS              PORTS
# szurubooru-client-1   "/docker-entrypoint.…"   client              running             0.0.0.0:8080->80/tcp
# szurubooru-server-1   "/opt/app/docker-sta…"   server              running             6666/tcp
# szurubooru-sql-1      "docker-entrypoint.s…"   sql                 running             5432/tcp

# Open the python prompt in the szurubooru-server container
# The name might differ slightly, use the output from the prev command
docker exec -it szurubooru-server-1 python3
```
```py
# Execute/paste this code
from szurubooru import db, model
# Warning again: this will remove all post feature history! It will NOT delete the post.
db.session.query(model.PostFeature).delete()
db.session.commit()
exit()
```
