### ISSUE TITLE
how to edit this page

### ISSUE THREAD

**Issue by IlyaKangin** [rr-/szurubooru#520]
![изображение](https://user-images.githubusercontent.com/60034226/198846847-e2d9fc31-1472-4b7b-a10c-e0b5f90250a2.png)

**Comment by skybldev** [comment]
https://github.com/rr-/szurubooru/blob/master/client/html/help_about.tpl

For people in the future reading this please explore `client/html` instead of raising an issue here. You will usually find what you're looking for there.
