### ISSUE TITLE
Deleted and Merged Posts Are Still On Filesystem.

### ISSUE THREAD

**Issue by BobHassok** [rr-/szurubooru#530]
I'm not sure if I'm not doing something correctly; if there's some hidden step I need to do; or I have some strange permission error.
However whenever I delete a post or merge 2 posts, the image (from the now-deleted post) is still on my filesystem. So I have dozens of files that do not have any posts associated with them and they're taking up space on my disk. Am I supposed to run some kind of purge command to have them removed or are they supposed to be deleted when the post associated with them is deleted?

**Comment by neobooru** [comment]
This is probably because of the "griefing protection". You can disable this by setting `delete_source_files` to `yes` inside [config.yaml](https://github.com/rr-/szurubooru/blob/master/server/config.yaml.dist#L14)

**Comment by BobHassok** [comment]
Yes, this is 100% what I'm looking for. Since I'm the only user, I don't need the protection. Thank you!
