### ISSUE TITLE
Help uploading large files

### ISSUE THREAD

**Issue by Anbosuki** [rr-/szurubooru#532]
Hello,
Recently I wanted to upload a file with size ~1.1GB which exceeds the configured size of 1024m. So I adjusted the value for it in `client/nginx.conf.docker` like so:
```
http {
    ...
    client_max_body_size 2048m;
    ...
}
```

I also removed the line from the server directive. Now when trying to upload the file I get either `502 Failed to connect to szurubooru REST API` or
```
413

Request Entity Too Large

exceeds max_body of 1073741824

(generated by waitress)
```
which would be the default value of the configuration file. I also dumped the nginx config at runtime, but couldn't find any hint of that specific value.

The instance is running on an Ubuntu 22 server with Nginx and Apache2.

Any idea?

Thanks for any kind of help :)

**Comment by mavanmanen** [comment]
Thanks for the info.
I have it working for myself as well now, seems cloudflare was also giving me some trouble, never considered that would be a factor.
