### ISSUE TITLE
Feature Request: Ability to view random post.

### ISSUE THREAD

**Issue by BobHassok** [rr-/szurubooru#540]
I know other booru apps have this function, and if Szurubooru has it I have no idea how to set it up. I would love to be able to just click a link and get a random post from my Booru.

**Comment by noirscape** [comment]
This has been asked before; searching `sort:random` reorders the post list to be randomized.

**Comment by BobHassok** [comment]
> 

Oh, good. I couldn't find this in the documentation. Now I need to figure out how to edit the page to insert that as a button. Do you happen to know if the interface is written in HTML?

**Comment by noirscape** [comment]
No it's javascript and custom framework.

As for inserting stuff on the top bar, your easiest bet would probably to look into [top_navigation.js](https://github.com/rr-/szurubooru/blob/7b54551b8e9dd8b9258ad1e0469a3a1264f29873/client/js/models/top_navigation.js) or [home.tpl](https://github.com/rr-/szurubooru/blob/master/client/html/home.tpl) if you want to put it in the frontend.

Keep in mind that if you're looking to deploy with docker, that you will need to rebuild the frontend repo on your own (and need to keep it in sync with the upstream); instructions for that are [here](https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md#building).

**Comment by BobHassok** [comment]
Thanks for the info! I'll probably just take the lazy method and export the files from the docker container, edit them, then import them back to the container. Just have to do that every time I update.

**Comment by BobHassok** [comment]
@parallax4 That is very good info, thanks! I may just switch to their fork instead of using my janky edits.
