### ISSUE TITLE
How to link to a tag with special characters?

### ISSUE THREAD

**Issue by Chattille** [rr-/szurubooru#547]
I tried to link to tag `foo*bar` in the tag description area, which should have create a link to `/posts/query=foo*bar`.
I tried `#foo*bar` but the parser created a link to `#foo` and `*bar` was ignored. I tried `[foo*bar](#foo*bar)` but it linked to `/#foo*bar`. I tried `#foo\*bar`, `[foo*bar](#foo\*bar)`, `[foo*bar](#foo%2Abar)` and none of them worked.
It seems that the only way to link to it is to use a URL `[foo*bar](/posts/query=foo*bar)`. Is there a cleaner or a simpler way to do this?

**Comment by po5** [comment]
That is caused by regexes in markdown.js only accepting a-zA-Z0-9_-
https://github.com/rr-/szurubooru/blob/782f0690318d21e9e09ac88984afc59a1812b888/client/js/util/markdown.js#L66-L77

**Comment by Chattille** [comment]
Thanks! I changed regexes and rebuild the image and now it works.
