### ISSUE TITLE
Use local file instead of uploading?

### ISSUE THREAD

**Issue by 59716123** [rr-/szurubooru#554]
Hi, is it possible to use a local file (as in **_move_** the file from e.g. `/usr/downloads/` to `/var/local/szurubooru/data/posts`) instead of uploading?  
I have downloaded the images / videos beforehand anyway, and uploading it via http is unnecessary time consuming, especially when using many files and low end hardware (raspi 4 in my case).  
Tags and stuff would be added later then.

**Comment by skybldev** [comment]
Moving the file directly is not possible; there is no mechanism that detects new files in the data directory. The upload process is necessary for determining file metadata and creating entries in the database. A file is also renamed to a random alphanumeric string for security purposes once it is uploaded.

If uploading through the web interface is slow for you, [the project's API has comprehensive documentation](https://github.com/rr-/szurubooru/blob/master/doc/API.md#file-uploads) that you can reference to write a script that does it for you. (if you like, I can write one for you in Deno JavaScript) However, all the processes that take place behind the scenes are non-negotiable and must happen.

**Comment by neobooru** [comment]
Another solution would be to edit the [szuru-admin](https://github.com/rr-/szurubooru/blob/master/server/szuru-admin) to import all files in a directory. You probably need to copy/paste some code from the [api/post_api.py:create_post function](https://github.com/rr-/szurubooru/blob/master/server/szurubooru/api/post_api.py#L54) (e.g. `postfuncs.create_post`, etc), but I haven't tried that so I can't really help with that.

But yeah, currently there exists no such functionality.

**Comment by 59716123** [comment]
I've found out that you can move your files to `/var/local/szurubooru/data/temporary-uploads`   
(or your equivalent thereof), name it e.g. `yourname.dat`   
and then use the API to create a post (`POST /posts/`) with the metadata of 
```  
{  
    "tags":      [<tag1>, <tag2>, <tag3>],  
    "safety":    <safety>,  
    "source":    <source>,                    // optional  
    "contentToken": <yourname> // <-- from yourname.dat without the .dat  
}
```  
and omitting the `content` file upload  
  
  
If you're using this, be aware that szurubooru will delete those files after 60 minutes.
