### ISSUE TITLE
Unable to import from several sites

### ISSUE THREAD

**Issue by myalow** [rr-/szurubooru#555]
Recently I've noticed that several URLs return a 403 Forbidden when I try to import them in my Szurubooru instance. The sites I've noticed that cause this issue are:
- Gelbooru
- Sankaku Complex
- Discord
- Rule34.US

As said, when I input an image URL from any of these sites, it returns a 403. Firefox's debugger also gives me this:
```
-----------------------------412815100230570727603151058056
Content-Disposition: form-data; name="metadata"; filename="blob"
Content-Type: application/octet-stream

{"contentUrl":"<URL TO IMG>"}
-----------------------------412815100230570727603151058056--
```

It's worth noting as well, some sites, like Danbooru, Reddit, Imgur, allow me to import just fine. Honestly, I have no idea what the issue could be caused by, but I'm more than willing to help diagnose anything if anyone has any ideas.

**Comment by nateify** [comment]
I don't have enough knowledge to read the szurubooru codebase to see if this is the case, but I believe those sites ban hotlinking so this could be due to szurubooru not sending the correct referrer.

**Comment by noirscape** [comment]
Configure a user agent in `server.config.yaml`.

All except for Sankaku filter against having no user agent. Merely setting one should be enough for most, but if that fails, set one that matches a common browser. Sankaku does more intensive anti-hotlinking checks, so no dice there.

**Comment by neobooru** [comment]
Closing this as setting the user-agent should solve the issue. Though feel free to reopen if it does not solve the issue.
Iirc you have to set the `Referer` header for Sankaku to work, but that is not something which szurubooru currently supports.
