### ISSUE TITLE
Whenever I try to rebuild or modify the server, I get this error.

### ISSUE THREAD

**Issue by sparkplug12** [rr-/szurubooru#586]
When I first set up the server, on AWS (amazon linux 2023). I can get the site to run. However whenever I modify it or restart the instance I get this error. I know I have the postgres_user set and its identical to the RDS database, the database uses mySQL8.0. Also when I try to load the webpage after I modify it. The browser says it couldn't fetch the server info.

''' 
When I do "docker-compose up" I get this error:

[ec2-user@ip-172-31-11-202 szuru]$ docker-compose pull
[+] Pulling 3/3
 ✔ server Skipped - No image to be pulled                                                                                                                                                                    0.0s
 ✔ client Skipped - No image to be pulled                                                                                                                                                                    0.0s
 ✔ sql Pulled                                                                                                                                                                                                0.3s
[ec2-user@ip-172-31-11-202 szuru]$ docker-compose up -d sql
[+] Building 0.0s (0/0)
[+] Running 1/0
 ✔ Container szuru-sql-1  Running                                                                                                                                                                            0.0s
[ec2-user@ip-172-31-11-202 szuru]$ docker-compose up -d
[+] Building 0.0s (0/0)
[+] Running 3/3
 ✔ Container szuru-sql-1     Running                                                                                                                                                                         0.0s
 ✔ Container szuru-server-1  Started                                                                                                                                                                         0.7s
 ✔ Container szuru-client-1  Started                                                                                                                                                                         1.5s
[ec2-user@ip-172-31-11-202 szuru]$ docker-compose up
[+] Building 0.0s (0/0)
[+] Running 3/0
 ✔ Container szuru-sql-1     Running                                                                                                                                                                         0.0s
 ✔ Container szuru-server-1  Running                                                                                                                                                                         0.0s
 ✔ Container szuru-client-1  Created                                                                                                                                                                         0.0s
Attaching to szuru-client-1, szuru-server-1, szuru-sql-1
szuru-client-1  | Traceback (most recent call last):
szuru-client-1  |   File "/usr/bin/alembic", line 8, in <module>
szuru-client-1  |     sys.exit(main())
szuru-client-1  |   File "/usr/lib/python3.8/site-packages/alembic/config.py", line 632, in main
szuru-client-1  |     CommandLine(prog=prog).main(argv=argv)
szuru-client-1  |   File "/usr/lib/python3.8/site-packages/alembic/config.py", line 626, in main
szuru-client-1  |     self.run_cmd(cfg, options)
szuru-client-1  |   File "/usr/lib/python3.8/site-packages/alembic/config.py", line 603, in run_cmd
szuru-client-1  |     fn(
szuru-client-1  |   File "/usr/lib/python3.8/site-packages/alembic/command.py", line 385, in upgrade
szuru-client-1  |     script.run_env()
szuru-client-1  |   File "/usr/lib/python3.8/site-packages/alembic/script/base.py", line 582, in run_env
szuru-client-1  |     util.load_python_file(self.dir, "env.py")
szuru-client-1  |   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
szuru-client-1  |     module = load_module_py(module_id, path)
szuru-client-1  |   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
szuru-client-1  |     spec.loader.exec_module(module)  # type: ignore
szuru-client-1  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
szuru-client-1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
szuru-client-1  |   File "szurubooru/migrations/env.py", line 22, in <module>
szuru-client-1  |     import szurubooru.config  # noqa: E402
szuru-client-1  |   File "/opt/app/szurubooru/migrations/../../szurubooru/config.py", line 65, in <module>
szuru-client-1  |     config = _read_config()
szuru-client-1  |   File "/opt/app/szurubooru/migrations/../../szurubooru/config.py", line 61, in _read_config
szuru-client-1  |     ret = _merge(ret, _docker_config())
szuru-client-1  |   File "/opt/app/szurubooru/migrations/../../szurubooru/config.py", line 28, in _docker_config
szuru-client-1  |     raise errors.ConfigError(
szuru-client-1  | szurubooru.errors.ConfigError: Environment variable "POSTGRES_USER" not set
szuru-client-1 exited with code 1
'''

**Comment by noirscape** [comment]
Before I comment further: MySQL isn't supported. The database is in Postgres and I think we use quite a few Postgres specific things? Don't deploy with a MySQL server.

What you probably forgot to do was set up the `.env` file correctly. Check the `doc/INSTALL.md` file for installation steps.

**Comment by sparkplug12** [comment]
I set the files exactly. However I got it to work by removing everything. I also swapped the DB with postgreSQL and installed PostgreSQL onto the EC2 instance
