### ISSUE TITLE
Issues with file permissions on windows

### ISSUE THREAD

**Issue by CrewMonkey** [rr-/szurubooru#605]
Hi, I'm sorry to bother you with this kind of stuff, but I'm trying to run szuru on the only pc I have right now that's essentially a potato pc running windows, which means it would be preferable to avoid using a virtual machine to host the whole thing under linux only to be able to edit folder permissions the right way. And that's the problem I'm facing. I have the "internal server error" issue, and can't figure out from internet or the other opened issues how to solve that problem. Could you guys help me ?
Just in case the issue isn't where I think it is, here are some logs when trying to upload files :
`szurubooru-25-client-1  | 2023/10/15 21:04:59 [warn] 10#10: *1 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000002, client: 172.26.0.1, server: , request: "POST /api/uploads HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/upload"
szurubooru-25-server-1  |   File "/opt/app/szurubooru/rest/app.py", line 104, in application
szurubooru-25-client-1  | 172.26.0.1 -> POST /api/uploads HTTP/1.1 [500] - referer: http://127.0.0.1/upload -
szurubooru-25-server-1  |     response = handler(ctx, match.groupdict())
szurubooru-25-client-1  | 172.26.0.1 -> GET /api/info HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szurubooru-25-server-1  |   File "/opt/app/szurubooru/api/upload_api.py", line 19, in create_temporary_file
szurubooru-25-client-1  | 172.26.0.1 -> GET /settings HTTP/1.1 [200] - referer: - -
szurubooru-25-client-1  | 172.26.0.1 -> GET /api/info HTTP/1.1 [200] - referer: http://127.0.0.1/settings -
szurubooru-25-server-1  |     token = file_uploads.save(content)
szurubooru-25-client-1  | 172.26.0.1 -> GET /api/info HTTP/1.1 [200] - referer: http://127.0.0.1/settings -
szurubooru-25-client-1  | 172.26.0.1 -> GET /api/user/mudwalker?bump-login=true HTTP/1.1 [200] - referer: http://127.0.0.1/settings -
szurubooru-25-server-1  |   File "/opt/app/szurubooru/func/file_uploads.py", line 29, in save
szurubooru-25-client-1  | 172.26.0.1 -> GET /api/tag-categories HTTP/1.1 [200] - referer: http://127.0.0.1/settings -
szurubooru-25-server-1  |     files.save(path, content)
szurubooru-25-server-1  |   File "/opt/app/szurubooru/func/files.py", line 41, in save
szurubooru-25-server-1  |     os.makedirs(os.path.dirname(full_path), exist_ok=True)
szurubooru-25-client-1  | 172.26.0.1 -> GET /api/pool-categories HTTP/1.1 [200] - referer: http://127.0.0.1/settings -
szurubooru-25-server-1  |   File "/usr/lib/python3.8/os.py", line 223, in makedirs
szurubooru-25-client-1  | 172.26.0.1 -> GET /settings HTTP/1.1 [304] - referer: - -
szurubooru-25-server-1  |     mkdir(name, mode)
szurubooru-25-client-1  | 172.26.0.1 -> GET /api/info HTTP/1.1 [200] - referer: http://127.0.0.1/settings -
szurubooru-25-server-1  | PermissionError: [Errno 13] Permission denied: '/data/temporary-uploads'
szurubooru-25-server-1  | [2023-10-15 21:04:59] szurubooru.middleware.request_logger POST /uploads (user=mudwalker, queries=1)`
Also, I tried moving the repos to another drive and after rebuilding, deleting via docker desktop and command line and rebuilding it doesn't work, there's no element to be considered in this second problem as far as I'm aware.
Thanks for your attention.

**Comment by TiredSysOp** [comment]
Post your config files and strip anything sensitive. If you're using docker desktop for windows everything should be under the dirtiest of permissions which is 777. I want to see how your volumes or mount points are setup.

**Comment by noirscape** [comment]
Your mount permissions are incorrect; I have no idea how Docker for Windows works but the error indicates that the server can't write uploaded files to the disk.

**Comment by CrewMonkey** [comment]
> Post your config files and strip anything sensitive. If you're using docker desktop for windows everything should be under the dirtiest of permissions which is 777. I want to see how your volumes or mount points are setup.

Here is my .env config :
[.env.txt](https://github.com/rr-/szurubooru/files/13056375/default.env.txt)
And here is my config.yaml :
[config.yaml.txt](https://github.com/rr-/szurubooru/files/13056397/config.yaml.txt)
I didn't do any advanced config on these. I have no idea how permissions work on windows, tried fidgeting with the gui but will search that up.
I could send you the whole folder for further exam but I'm not sure how this whole thing is organized and if there is anything sensitive in the logs or something related to dockers, sorry.

**Comment by CrewMonk33** [comment]
Hi again, had to create a new account because github can get dumb sometimes. I solved the problem, it was because "read only" was checked (by default ?) in the file properties. It's working fine now, although unchecking the box gave me a warning about safety so I'm still wondering if there isn't a more precise solution. Still thanks for spending time on that problem.
