### ISSUE TITLE
Mass Remove Tag

### ISSUE THREAD

**Issue by gljames24** [rr-/szurubooru#630]
Can the mass edit tag option allow the negation of a tag to remove the tag instead of add it?
For example if I look up "tag-count:15.. tagme" and want to remove tagme on all posts with more than or 15 tags, I would want to be able to click mass tag and put in "-tagme" and it would remove tagme from those posts.

**Comment by G1org1owo** [comment]
If I got what what you said right, this feature is already there.

If you put `tagme` in the mass tag text field, the posts that are tagged as `tagme` will have a green '+' instead of a red '-', by clicking on that button it will remove the tag(s) from the post.
