### ISSUE TITLE
Suggestion/Autocomplete for tags does not work if you are not registered...

### ISSUE THREAD

**Issue by MahdeenSky** [rr-/szurubooru#634]
Unregistered
![image](https://github.com/rr-/szurubooru/assets/49484385/d4755f3e-80c5-4f8f-aba0-312b53c8faff)

Registered
![image](https://github.com/rr-/szurubooru/assets/49484385/e39dcc71-970d-4469-8e35-8622b1f16810)

**Comment by neobooru** [comment]
You can fix this by changing `'tags:list': anonymous` in server/config.yaml. By default only 'regular' logged-in users can list (and therefore search/autocomplete) tags. I guess that is maybe not the expected default value though. You might also want to set other permissions to anonymous, such as `tag_categories:list` and `tags:view`.
If you want a public booru (where an account is not required) then you could consider settings all `xxx:list` and `xxx:view` permissions to anonymous.
