### ISSUE TITLE
Changing the favicon

### ISSUE THREAD

**Issue by Stormlashbd** [rr-/szurubooru#680]
Hello, and sorry for the newbie issue. 

I've decided to host a booru for a small community, with 0 prior knowledge. I purchased the (VPS) hosting, followed the instructions, no issues so far. With a bit of assistance from ChatGPT, I used a FTP client to replace "app.png", "favicon.png" and "splash.png" inside /szuru/client/img, followed by `docker-compose down` and `docker-compose up -d` respectively, but with no success.

I looked up the past issues and found one similar, but I'm not entirely sure what steps I should take without making a mess. If there's anything I need to share in order to facilitate solving this problem, let me know. 

Thank you in advance for any and all assistance!

**Comment by liamw1** [comment]
`docker-compose pull` pulls pre-built images images from a central registry, so any changes you make to your local files won't have any effect. To change the icons (or any other custom change to the client/server), you'll need to build the containers yourself:

1. Make the necessary changes to the `docker-compose.yml` described [here](https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md#building)
2. Run `docker-compose build`
3. Run `docker-compose up -d`

**Comment by Stormlashbd** [comment]
How silly of me, I completely missed that step there at the end. ChatGPT was sending me on a weird chase of adding extra lines in the file because of "caching issues". Guess that's a good lesson as any to blindly trust AI.
Thanks again!
