### ISSUE TITLE
how to enable splash on homepage?

### ISSUE THREAD

**Issue by qlunc** [rr-/szurubooru#704]
no information on it anywhere

**Comment by TiredSysOp** [comment]
Edit a post and there should be a button to feature it somewhere. My instance is down so I can't quite post a screen shot.

Keep in mind that it can't completely disable it afterwards and you can only change the featured post from there on.

**Comment by neobooru** [comment]
![image](https://github.com/user-attachments/assets/e1838415-43e0-4840-9656-881df76513c6)

You might be able to disable the featured post by setting the 'posts:view:featured' permission to 'nobody' in config.yaml, but I haven't tried it.
