### ISSUE TITLE
Installation instructions are outdated

### ISSUE THREAD

**Issue by kotcrab** [rr-/szurubooru#78]
I'm trying to install Szurubooru on my local server but looks like the installation instructions are outdated. Eg. [INSTALL.md](https://github.com/rr-/szurubooru/blob/master/INSTALL.md) states that  `pdo_sqlite` is needed but sqlite support was dropped in 9ca712cc6d258b74dfa53067ae72c1af8898eda6. 
Instructions on wiki seems even more outdated, they mention non existent `init.php` script.

**Comment by rr-** [comment]
Oh boy, I haven't visited wiki for this repo in *ages*. Gonna fix it asap once I familiarize myself with the current installation procedures using a bare machine as a reference.

**Comment by kotcrab** [comment]
Heh that's ok, that sqlite part confused me for a while when I saw MySQL in config ;) While you are at it you can also update/remove [instructions for nginx](https://github.com/rr-/szurubooru/wiki/Using-nginx-with-Szurubooru).

**Comment by rr-** [comment]
Updated the installation guide and removed obsolete `nginx` instructions (which were donated by some unaffiliated user in 2013).

**Comment by kotcrab** [comment]
Might be worth mentioning that MySQL is needed in [Prerequisites](https://github.com/rr-/szurubooru/blob/master/INSTALL.md#prerequisites).

Thanks for doing that, I'll try to finish installing tomorrow. Maybe I'll try to create some installation script if I find some time.
