### ISSUE TITLE
Endless scroll does not allow to scroll up

### ISSUE THREAD

**Issue by kotcrab** [rr-/szurubooru#80]
Endless scroll could be improved, eg. if you go to `#/posts/page=2` you will be on page 2 without option to scroll up, you can only scroll down. Would be nice if scrolling up would also be supported.

I also found an issue that this creates:
1. Enable endless scroll in settings
2. Go to post list
3. Click any of green/yellow/red buttons to filter posts, click it again. You will be on page 2 without option to scroll up. Click it again twice and you will get to page 3. You can do it until you are on last page.

**Comment by rr-** [comment]
This is kind of unrelated, but I'm considering technology shift (C#+ServiceStack+NHibernate for the backend, and something statically typed with as few dependencies as possible for the frontend). What is your opinion on this?

**Comment by kotcrab** [comment]
You can always create new issue and call someone with @kotcrab, I'm not really the best person to ask since I don't have much experience with webdev. Personally I like the simplicity of running PHP app, eg. compared to Danbooru which I couldn't even mange to run because of some obscure Ruby errors but hey if that's what you really want to do then go for it.

**Comment by rr-** [comment]
Both issues appear to be solved in 2.x and can be tested on the user list. Sorry for all the trouble with the repository rotation, it should be pretty stable from now on.

**Comment by kotcrab** [comment]
I haven't setup 2.x yet so I can't test it. I think this issue can be closed if you don't intend to fix this in 1.x.

> Sorry for all the trouble with the repository rotation, it should be pretty stable from now on.

No problem.

**Comment by rr-** [comment]
Closing as 1.x is no longer supported
