### ISSUE TITLE
Javascript from "localhost": Fatal Authentication Error.

### ISSUE THREAD

**Issue by princessGasmask** [rr-/szurubooru#86]
I got this error after installing. The site appears to be loading and I can see the "Home", "Login", "Register" and "Help" buttons, but none of them do anything. I'm installing version 1.1 on windows 10 using XAMPP if that helps.

**Comment by rr-** [comment]
What browser are you using? Does the developer console show anything out of ordinary?

**Comment by princessGasmask** [comment]
I'm using Vivaldi. My console has 3 errors.
http://puu.sh/oqgac/d47d5fe498.png

**Comment by rr-** [comment]
Looks like 

1. You haven't enabled `mod_rewrite` in Apache - please [try these instructions](https://github.com/rr-/szurubooru/blob/1.x/INSTALL.md#enabling-required-modules-in-apache)
2. You haven't compiled the assets (such as fonts etc.) - please [try running `grunt`](https://github.com/rr-/szurubooru/blob/1.x/INSTALL.md#compiling-assets). `grunt` should be included after you've installed `npm` package manager and fetched szurubooru's dependencies as described [here](https://github.com/rr-/szurubooru/blob/1.x/INSTALL.md#running-grunt-tasks).
3. Just in advance, you're also going to need a local MySQL database.

**Comment by princessGasmask** [comment]
mod_rewrite should already be active. Also, I've already run composer update and npm update within the szuru directory, unless there was something I was supposed to do beforehand. Also, mod_rewrite should already be active.
http://puu.sh/oqgpM/2af3aad9f4.png

**Comment by princessGasmask** [comment]
Not sure if I did this part right, but grunt upgrade and build do work with no errors. 
http://puu.sh/oqham/928c44c2b4.png

**Comment by rr-** [comment]
I apologize, but I'm afraid I don't know how to help you. From the info you've posted, looks like everything should work - at the very least, the calls to the API shouldn't return 404.

**Comment by princessGasmask** [comment]
I figured it was just a wonky thing with me specifically. I've had similar issues with things that use Node where they appear to be setup properly but simply don't work for unexplained reasons. I appreciate you trying to help anyways. :)
