### ISSUE TITLE
I'm back.

### ISSUE THREAD

**Issue by princessGasmask** [rr-/szurubooru#87]
I reinstalled everything fresh and got the booru to install finally. However, now that it is installed, I can see the "Home", "Login", "Register" and "Help" buttons (with icons this time, which didn't load the first time), however, none of the buttons do anything when clicked. Checking the errors within my browser only calls one: "Uncaught TypeError: b.match is not a function."

http://puu.sh/ot7WV/56277bf549.png

**Comment by rr-** [comment]
Can you show network communication between the client and the server?

**Comment by princessGasmask** [comment]
It appears to be loading, gets to about 90 percent in the progress bar and never finishes.

**Comment by rr-** [comment]
I meant the network tab in the developer tools, which should show the details what's happening.

**Comment by princessGasmask** [comment]
This is the network tab in fullscreen.
http://puu.sh/otTT7/19a1e472fe.png

**Comment by rr-** [comment]
What does `/login` return? (You can check this by clicking on it)

**Comment by princessGasmask** [comment]
http://puu.sh/otUGA/dd8b0dd3cf.png

**Comment by rr-** [comment]
Are there no further details? In my browser, it looks like this:
![20160424_153225_vbt](https://cloud.githubusercontent.com/assets/1045476/14767915/6c691172-0a32-11e6-80a8-0783550bb269.png)

**Comment by princessGasmask** [comment]
Which browser are you using? I can download it so there's more detail.

**Comment by rr-** [comment]
It's Mozilla Firefox; Chrome should have similar capabilities.

**Comment by princessGasmask** [comment]
http://puu.sh/ou4vc/476c38e604.png

**Comment by rr-** [comment]
1.x is no longer supported, closing
