### ISSUE TITLE
Tags.json missing on fresh install?

### ISSUE THREAD

**Issue by kotcrab** [rr-/szurubooru#89]
I have successfully compiled frontend and started backend server. After opening browser I got page with top bar only and nothing else is working. I opened debug console to see `TypeError: response.body is null` in method:
```javascript
function refreshExport() {
    return new Promise(function (resolve, reject) {
        request.get('/data/tags.json').end(function (error, response) {
            if (error) {
                _tags = new Map();
                _categories = new Map();
                reject(error);
            }
            _tags = _tagsToMap(response.body.tags);
            _categories = _tagCategoriesToMap(response.body.categories);
            _refreshStylesheet();
            resolve();
        });
    });
}
```
I checked `data` directory and found out that `tags.json` does not exist, after creating empty file the error changed to `TypeError: tags is undefined`.

**Comment by rr-** [comment]
Have you built the frontend? It won't work without it

**Comment by kotcrab** [comment]
Yeah, I ran `npm run build`. That file was not created.
```
[root@archlinux client]# npm run build

> szurubooru@ build /root/szuru/client
> node build.js

Bundled HTML
Bundled CSS
Bundled app JS
Bundled vendor JS
[root@archlinux client]#
```

**Comment by rr-** [comment]
Please tell me if https://github.com/rr-/szurubooru/commit/aa95afb989b4caf0fc6f5de3b07907790e84da16 works for you. The `tags.json` should be created with first edit to tag categories.

**Comment by kotcrab** [comment]
Thanks, it works now. I was able to register and `tags.json` was created after adding category.
