### ISSUE TITLE
Expose server time in global info

### ISSUE THREAD

**Issue by kotcrab** [rr-/szurubooru#91]
I think it would be good idea to include current server time in `/info`.

**Comment by rr-** [comment]
Isn't this returned in HTTP headers?
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.18

**Comment by kotcrab** [comment]
Ow, you are right. I didn't know about this. Still it's worth considering doing it - date format would be consistent with others API methods that returns date in RFC 3339 format. Fell free to close this.

**Comment by rr-** [comment]
Implemented in https://github.com/rr-/szurubooru/commit/162904bfc308124d33f45c51a0e5c8c7ca038e6e
