### ISSUE TITLE
Include more characters in default tag name regex

### ISSUE THREAD

**Issue by kotcrab** [rr-/szurubooru#92]
Any reason for not including characters like `( ) [ ] / \ :` in tag name regex? They seems to be quite common in Danbooru tags. 

This also made me wonder how should I protect against not matching tags in auto tagger. API to obtain `tag_name_regex` would be nice.

**Comment by rr-** [comment]
True, things like that get compiled into frontend. I'll expose them via `/info` this weekend.

The reason for not including `:` is simple - it breaks search token parsing (e.g. `safety:sketchy`, `sort:random` etc. - it's impossible without extra queries to the DB to tell tag from named token).

As for the other characters, it requires some extra testing, esp. for `/` character that I believe will not play nicely with the current client router.

**Comment by kotcrab** [comment]
I got full list of Danbooru tags and did some checks. Most commons characters are `( )` with 54800 occurrences. 
`:` 656 occurrences
`/` actually appears only 401 times. Not worth modifying router just for this if it requires a lot of work or extra checks.
`\` 11 occurrences
`[` 21 occurrences
So I think only `( )` should be added, I can make auto tagger replace others with `_`

**Comment by rr-** [comment]
Superb :+1:
Anyway I'm a little busy right now refactoring the client, so this issue will need to wait till tomorrow / Saturday (not sure if I have the time to test everything).

**Comment by kotcrab** [comment]
By the way [API.md#updating-tag](https://github.com/rr-/szurubooru/blob/master/API.md#updating-tag) should be `PUT /tag/<name>`.

**Comment by rr-** [comment]
Fixed

**Comment by rr-** [comment]
Today aftermatch - I still need to refactor post sidebar so that it doesn't talk to API directly. After this and a quick round of tests, I should be able to push my refactors and fix this issue.

**Comment by kotcrab** [comment]
Sounds nice. I'm actually doing something similar in auto tagger. Returned JSON is wrapped in its model class and is lazy parsed when some field is needed.

I noticed weird thing about tags. I have tag that starts with `:` eg. `:3`. It doesn't have any others names, implications or suggestions. I can go to `http://szurubooru.local/tag/:3` and I see tag page but the same page is shown when I go to `http://szurubooru.local/tag/_3`. Is this intentional?

**Comment by rr-** [comment]
Nope, I'll investigate it. Sounds like a problem with client router.
Pushed  fix for this issue.

**Comment by rr-** [comment]
Actually, it's a problem with SQL... `_` gets interpreted as "any character" because I use `ILIKE`. In fact it's possible to crash the server with query such as `____`:

    sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

Fixing it in a sec.
