### ISSUE TITLE
Tag's alias can be added repeatedly

### ISSUE THREAD

**Issue by tehoko** [rr-/szurubooru#93]
If a tag has an alias, it can be added endlessly to the list in edit mode.

Example: the `K-On!` tag has a `K-On` alias:

![alias01](https://cloud.githubusercontent.com/assets/2924029/18611140/422563d0-7d31-11e6-9800-3fa85929ebff.gif)

The same can be done using suggestions that have the given tag implied (here, adding multiple K-On! characters would add the `K-On!` tag multiple times).

Note that the alias is also shown in the autocomplete list (visible in the gif above).

After adding the tag multiple times, it **cannot be deleted** using the `x` button.

This issue **does not** persist after saving the changes - the post only displays one occurrence of the tag. Entering the edit mode again also only shows one tag.

**Comment by rr-** [comment]
This is some seriously sloppy programming and I'll fix it once I get sober.
