### ISSUE TITLE
Stopped mass tag starts again when searching posts

### ISSUE THREAD

**Issue by tehoko** [rr-/szurubooru#94]
Steps to reproduce:

1. Open post list.
2. Start mass tag with any input.
3. Stop mass tag.
4. Click `Search`.
5. Mass tag buttons appear again, and the URL now has mass tag stuff in it.

![masstag](https://cloud.githubusercontent.com/assets/2924029/18611377/2bb23a64-7d37-11e6-899d-e5843887d30a.gif)

The only way to truly exit tagging is to clear mass tag's input field and click `Start tagging`.

I thought endless scroll could have something to do with this, but the issue also occurs when the paged view is enabled.

**Comment by rr-** [comment]
This is weird and I'll look into it ASAP
