### ISSUE TITLE
Underscore acts as wildcard character in search

### ISSUE THREAD

**Issue by tehoko** [rr-/szurubooru#98]
Searching for `____` (4x `_`) will return posts tagged with a four-character tag. This works for any positive number of underscores.

Same for tag search (underscore count = tag name length) and user search (underscore count = user name length).

**Comment by tehoko** [comment]
Speaking of wildcards, the `*` character is completely ignored, as if no character was in its place.

Searching for `;*)` returns `;)`.

**Comment by rr-** [comment]
>Speaking of wildcards, the * character is completely ignored, as if no character was in its place.

>Searching for ;*) returns ;).

It's not. `*madoka*` will match `madoka` *and* `kaname_madoka` *and* `puella_magi_madoka_magica` like it's supposed to.

**Comment by rr-** [comment]
>Searching for `____` (4x `_`) will return posts tagged with a four-character tag. This works for any positive number of underscores.

>Same for tag search (underscore count = tag name length) and user search (underscore count = user name length).

I fixed this one
